#![cfg_attr(not(kani), feature(register_tool))]
#![register_tool(tigerstyle)]
//! crunch-build: Build pipeline for crunch.
//!
//! Translates `nix_compat::Derivation` structs into `snix_build::BuildRequest`,
//! executes builds in a sandbox, and persists results in the store.
//!
//! Pipeline: `Derivation` → `BuildRequest` → sandbox → `BuildResult` → `PathInfo`

pub mod action_result;
pub mod artifact_auth;
mod build_request;
pub mod ca_mapping;
pub mod ca_plan;
pub mod dispatch_build_service;
pub mod distributed;
pub mod dynamic;
pub mod dynamic_plan;
mod environment_policy;
mod error;
mod execution_profile;
pub mod export;
pub mod fetch_build_service;
pub mod fetcher;
mod fod;
pub mod goal;
mod hash;
mod hermeticity;
mod network_policy;
mod orchestrate;
mod references;
pub mod registry;
pub mod rewrite;
pub mod scheduling;
pub mod signing;
#[cfg(test)]
pub(crate) mod test_support;
pub mod worker;
pub mod workspace;
pub mod workspace_shell;

pub use action_result::ActionResultRuntimeReport;
pub use action_result::ActionResultTransferEvidence;
pub use build_request::BuildRequestEnvelope;
pub use build_request::WORKSPACE_LEASE_ENV;
pub use build_request::WORKSPACE_POLICY_ENV;
pub use build_request::derivation_to_build_request;
pub use dispatch_build_service::DispatchBuildService;
pub use distributed::LocalBuildServiceRealizer;
pub use distributed::RealizerProfileFacts;
pub use distributed::RemoteBuildFallbackPolicy;
pub use distributed::RemoteBuildServiceAdapter;
pub use distributed::RemoteFirstBuildService;
pub use dynamic::DynamicDrv;
pub use dynamic::is_drv_output;
pub use dynamic::parse_drv_bytes;
pub use dynamic::register_dynamic_drv;
pub use environment_policy::BUILD_ENVIRONMENT_DIGEST_ALGORITHM;
pub use environment_policy::BuildDeterminismControl;
pub use environment_policy::BuildDeterminismNormalizationReport;
pub use environment_policy::BuildEnvironmentRejection;
pub use environment_policy::BuildEnvironmentReport;
pub use environment_policy::BuildOutputDivergenceDiagnostic;
pub use environment_policy::BuildSearchPathAlias;
pub use environment_policy::BuildSearchPathEntry;
pub use environment_policy::BuildSearchPathReport;
pub use environment_policy::DETERMINISM_ENFORCEMENT_UNSUPPORTED;
pub use environment_policy::DETERMINISM_NORMALIZATION_DIGEST_ALGORITHM;
pub use environment_policy::DeniedEnvironmentVariable;
pub use environment_policy::DeterminismNormalizationError;
pub use environment_policy::DeterminismNormalizationRequest;
pub use environment_policy::ENV_REJECTION_COMPILER_WRAPPER;
pub use environment_policy::ENV_REJECTION_DYNAMIC_LINKER;
pub use environment_policy::ENV_REJECTION_LOCALE;
pub use environment_policy::ENV_REJECTION_PROXY;
pub use environment_policy::ENV_REJECTION_SECRET;
pub use environment_policy::ENV_REJECTION_TEMP_ROOT;
pub use environment_policy::SEARCH_PATH_DIGEST_ALGORITHM;
pub use environment_policy::classify_denied_environment_variable;
pub use environment_policy::normalized_environment_digest_blake3;
pub use environment_policy::output_divergence_diagnostic;
pub use environment_policy::plan_determinism_normalization;
pub use error::Error;
pub use execution_profile::EXECUTION_PROFILE_BINDING_ENV;
pub use execution_profile::EXECUTION_PROFILE_SCHEMA;
pub use execution_profile::ExecutionEnvironmentMode;
pub use execution_profile::ExecutionNetworkMode;
pub use execution_profile::ExecutionProfile;
pub use execution_profile::ExecutionProfileError;
pub use execution_profile::ExecutionProfileScope;
pub use execution_profile::ExecutionResourceLimits;
pub use execution_profile::bind_execution_profile;
pub use execution_profile::declared_profile_environment;
pub use execution_profile::execution_profile_digest;
pub use execution_profile::foreign_profile_for_producer;
pub use execution_profile::validate_derivation_profile_surface;
pub use execution_profile::validate_execution_profile;
pub use execution_profile::verify_execution_profile_binding;
pub use fetch_build_service::FETCH_BUILDER;
pub use fetch_build_service::FetchBuildService;
pub use fetch_build_service::FetchSourceOverride;
pub use fetch_build_service::FetchSourceOverrideKind;
pub use fetch_build_service::FetchSourcePolicy;
pub use fetch_build_service::is_fetch_request;
pub use fetcher::Fetch;
pub use fetcher::FetchError;
pub use goal::Goal;
pub use goal::GoalRegistry;
pub use goal::GoalState;
pub use hermeticity::HermeticityAuditEvent;
pub use hermeticity::HermeticityAuditKind;
pub use hermeticity::HermeticityMode;
pub use network_policy::BuildNetworkPolicyReport;
pub use network_policy::CompatibilityNetworkPolicy;
pub use network_policy::ENV_NETWORK_AUDIT_CLASS;
pub use network_policy::ENV_NETWORK_CAPABILITY;
pub use network_policy::ENV_NETWORK_POLICY_BASIS;
pub use network_policy::FixedOutputNetworkDeclaration;
pub use network_policy::NETWORK_CAPABILITY_BUILD_TIME;
pub use network_policy::NETWORK_MODE_COMPATIBILITY_CAPABILITY;
pub use network_policy::NETWORK_MODE_FIXED_OUTPUT_FETCHER;
pub use network_policy::NETWORK_MODE_OFFLINE;
pub use network_policy::NETWORK_RESULT_ALLOWED;
pub use network_policy::NETWORK_RESULT_BLOCKED;
pub use network_policy::NETWORK_RESULT_DENIED;
pub use network_policy::NETWORK_RETRY_POLICY_BOUNDED_TRANSIENT_FETCH;
pub use network_policy::NetworkPolicyDenied;
pub use network_policy::plan_network_policy;
pub use orchestrate::BuildOutcome;
pub use orchestrate::Builder;
pub use registry::DerivationRegistry;
pub use registry::RegistryEntry;
pub use registry::populate_registry;
pub use scheduling::ContentLocalityClass;
pub use scheduling::DurationClass;
pub use scheduling::DurationHistorySnapshot;
pub use scheduling::EligiblePreferenceFacts;
pub use scheduling::HardEligibilityFacts;
pub use scheduling::HistoryBasis;
pub use scheduling::HistoryInput;
pub use scheduling::IneligibleReason;
pub use scheduling::KnownGoalFacts;
pub use scheduling::KnownGraphFacts;
pub use scheduling::KnownGraphPressure;
pub use scheduling::OperatorPolicyClass;
pub use scheduling::PreferenceField;
pub use scheduling::PressureUpdate;
pub use scheduling::PriorityCandidateEvidence;
pub use scheduling::PriorityDecisionEvidence;
pub use scheduling::PrioritySelectionReason;
pub use scheduling::ReadyGoalFacts;
pub use scheduling::ResourceFitClass;
pub use scheduling::SchedulingError;
pub use scheduling::SchedulingPolicy;
pub use scheduling::StarvationClass;
pub use scheduling::TransferCostClass;
pub use scheduling::advance_scheduling_epoch;
pub use scheduling::normalize_eligible_preference;
pub use scheduling::priority_decision_evidence;
pub use scheduling::rank_ready_goals;
pub use scheduling::recompute_affected_pressure;
pub use signing::KeyPair;
pub use signing::VerifyResult;
pub use signing::build_trusted_keys;
pub use signing::generate_keypair;
pub use signing::load_keypair;
pub use signing::sign_pathinfo;
pub use signing::sign_pathinfo_with_store_dir;
pub use signing::verify_pathinfo_signatures;
pub use signing::verify_pathinfo_signatures_with_store_dir;
pub use worker::EvalMessage;
pub use worker::FailedGoal;
pub use worker::NativeDynamicPlanReport;
pub use worker::Worker;
pub use worker::WorkerResult;
pub use workspace::*;
pub use workspace_shell::*;
