//! Generate `.crunch/inputs.ncl` from a resolved lockfile.
//!
//! The generated file is a plain Nickel record where each field is a
//! locked input's metadata (url, hash, rev, mirrors). Package code
//! imports this file and passes the data to fetch helpers.
//!
//! Pure string generation. No I/O, no Nickel eval.

use alloc::format;
use alloc::string::String;
use alloc::string::ToString;

use crate::lock::LockEntry;
use crate::lock::LockedKind;
use crate::lock::LockedPatch;
use crate::lock::LockedPatchSource;
use crate::lock::Lockfile;
use crate::manifest::DarcsSelector;
use crate::manifest::FossilSelector;
use crate::manifest::PijulSelector;

/// Maximum number of inputs to generate (guard against runaway locks).
const MAX_GENERATED_INPUTS: u32 = 4096;

/// Maximum number of locked patches to render.
const MAX_GENERATED_PATCHES: u32 = 1024;

/// Header comment for the generated file.
const HEADER: &str = "# Generated by crunch from crunch.lock. DO NOT EDIT.\n";

struct RenderedStringField<'a> {
    indent: &'a str,
    name: &'a str,
    value: &'a str,
}

struct RenderedStringArray<'a> {
    indent: &'a str,
    name: &'a str,
    values: &'a [String],
}

struct UrlKindFields<'a> {
    kind_name: &'a str,
    url: &'a str,
}

struct GitKindFields<'a> {
    repository: &'a str,
    rev: &'a str,
    ref_name: Option<&'a str>,
}

/// Generate the `.crunch/inputs.ncl` content from a lockfile.
///
/// Each lock entry becomes a record field with its resolved metadata.
/// The output is valid Nickel that can be imported by package code.
pub fn generate_inputs_ncl(lock: Lockfile) -> String {
    assert_input_limits(&lock);
    assert_patch_references_are_locked(&lock);

    let mut out = String::with_capacity(1024);
    out.push_str(HEADER);
    out.push_str("{\n");

    for (index_u32, (name, entry)) in lock.inputs.iter().enumerate() {
        if index_u32 > 0 {
            out.push('\n');
        }
        generate_entry(&mut out, name, entry);
    }

    generate_locked_patches(&mut out, &lock);
    out.push_str("}\n");
    out
}

fn assert_input_limits(lock: &Lockfile) {
    assert!(
        lock.inputs.len() as u64 <= MAX_GENERATED_INPUTS as u64,
        "too many inputs to generate: {}",
        lock.inputs.len()
    );
    assert!(
        lock.patches.len() as u64 <= MAX_GENERATED_PATCHES as u64,
        "too many patches to generate: {}",
        lock.patches.len()
    );
}

fn assert_patch_references_are_locked(lock: &Lockfile) {
    for (input_name, entry) in &lock.inputs {
        for patch_name in &entry.patches {
            assert!(
                lock.patches.contains_key(patch_name),
                "input '{input_name}' references unlocked patch '{patch_name}'"
            );
        }
    }
}

/// Emit the `_patches` record for locked patch sources and hashes.
fn generate_locked_patches(out: &mut String, lock: &Lockfile) {
    if lock.patches.is_empty() {
        return;
    }

    out.push('\n');
    out.push_str("  _patches = {\n");
    for (name, patch) in &lock.patches {
        generate_locked_patch(out, name, patch);
    }
    out.push_str("  },\n");
}

fn generate_locked_patch(out: &mut String, name: &str, patch: &LockedPatch) {
    assert!(!name.is_empty(), "patch name must not be empty");
    assert!(!patch.hash.value.is_empty(), "patch hash must not be empty");
    let field_name = render_field_name(name);
    out.push_str(&format!("    {field_name} = {{\n"));
    generate_patch_source_fields(out, &patch.source);
    push_string_field(out, RenderedStringField {
        indent: "      ",
        name: "hash",
        value: &patch.hash.value,
    });
    push_string_field(out, RenderedStringField {
        indent: "      ",
        name: "algo",
        value: &patch.hash.algo.to_string(),
    });
    out.push_str("    },\n");
}

fn generate_patch_source_fields(out: &mut String, source: &LockedPatchSource) {
    match source {
        LockedPatchSource::Local { path } => {
            push_string_field(out, RenderedStringField {
                indent: "      ",
                name: "type",
                value: "local",
            });
            push_string_field(out, RenderedStringField {
                indent: "      ",
                name: "path",
                value: path,
            });
        }
        LockedPatchSource::Remote { url } => {
            push_string_field(out, RenderedStringField {
                indent: "      ",
                name: "type",
                value: "remote",
            });
            push_string_field(out, RenderedStringField {
                indent: "      ",
                name: "url",
                value: url,
            });
        }
    }
}

/// Generate a single input entry as a Nickel record field.
fn generate_entry(out: &mut String, name: &str, entry: &LockEntry) {
    assert!(!name.is_empty(), "entry name must not be empty");
    assert!(!entry.hash.value.is_empty(), "entry hash must not be empty");
    let field_name = render_field_name(name);
    out.push_str(&format!("  {field_name} = {{\n"));

    generate_kind_fields(out, &entry.kind);
    push_string_field(out, RenderedStringField {
        indent: "    ",
        name: "hash",
        value: &entry.hash.value,
    });
    push_string_field(out, RenderedStringField {
        indent: "    ",
        name: "algo",
        value: &entry.hash.algo.to_string(),
    });
    push_string_array(out, RenderedStringArray {
        indent: "    ",
        name: "mirrors",
        values: &entry.mirrors,
    });
    push_string_array(out, RenderedStringArray {
        indent: "    ",
        name: "patches",
        values: &entry.patches,
    });
    push_string_field(out, RenderedStringField {
        indent: "    ",
        name: "fetch_policy",
        value: entry.fetch_policy.as_str(),
    });
    if let Some(freshness) = &entry.freshness {
        push_string_field(out, RenderedStringField {
            indent: "    ",
            name: "freshness_value_digest",
            value: &freshness.value_digest,
        });
    }

    out.push_str("  },\n");
}

fn generate_kind_fields(out: &mut String, kind: &LockedKind) {
    match kind {
        LockedKind::File { url } => generate_url_kind_fields(out, UrlKindFields { kind_name: "file", url }),
        LockedKind::Tarball { url } => generate_url_kind_fields(out, UrlKindFields {
            kind_name: "tarball",
            url,
        }),
        LockedKind::Git {
            repository,
            rev,
            ref_name,
        } => generate_git_kind_fields(out, GitKindFields {
            repository,
            rev,
            ref_name: ref_name.as_deref(),
        }),
        LockedKind::Darcs {
            repository,
            selector,
            context,
            weak_hash,
        } => generate_darcs_kind_fields(out, repository, selector, context.as_deref(), weak_hash.as_deref()),
        LockedKind::Pijul {
            repository,
            selector,
            state,
            change,
        } => generate_pijul_kind_fields(out, repository, selector, state, change.as_deref()),
        LockedKind::Fossil {
            repository,
            selector,
            checkin,
        } => generate_fossil_kind_fields(out, repository, selector, checkin),
    }
}

fn generate_url_kind_fields(out: &mut String, fields: UrlKindFields<'_>) {
    assert!(!fields.kind_name.is_empty(), "kind name must not be empty");
    assert!(!fields.url.is_empty(), "url must not be empty");
    push_string_field(out, RenderedStringField {
        indent: "    ",
        name: "type",
        value: fields.kind_name,
    });
    push_string_field(out, RenderedStringField {
        indent: "    ",
        name: "url",
        value: fields.url,
    });
}

fn generate_git_kind_fields(out: &mut String, fields: GitKindFields<'_>) {
    assert!(!fields.repository.is_empty(), "git repository must not be empty");
    assert!(!fields.rev.is_empty(), "git revision must not be empty");
    push_string_field(out, RenderedStringField {
        indent: "    ",
        name: "type",
        value: "git",
    });
    push_string_field(out, RenderedStringField {
        indent: "    ",
        name: "repository",
        value: fields.repository,
    });
    push_string_field(out, RenderedStringField {
        indent: "    ",
        name: "rev",
        value: fields.rev,
    });
    if let Some(ref_name_value) = fields.ref_name {
        push_string_field(out, RenderedStringField {
            indent: "    ",
            name: "ref_name",
            value: ref_name_value,
        });
    }
}

fn generate_darcs_kind_fields(
    out: &mut String,
    repository: &str,
    selector: &DarcsSelector,
    context: Option<&str>,
    weak_hash: Option<&str>,
) {
    assert!(!repository.is_empty(), "darcs repository must not be empty");
    if context.is_none() {
        assert!(weak_hash.is_some(), "darcs weak hash must provide identity when context is absent");
    }
    if weak_hash.is_none() {
        assert!(context.is_some(), "darcs context must provide identity when weak hash is absent");
    }
    generate_vcs_common_fields(out, "darcs", repository);
    match selector {
        DarcsSelector::Tag(tag) => push_selector_fields(out, "tag", tag),
        DarcsSelector::Context(value) => push_selector_fields(out, "context", value),
    }
    if let Some(context) = context {
        push_string_field(out, RenderedStringField {
            indent: "    ",
            name: "context",
            value: context,
        });
    }
    if let Some(weak_hash) = weak_hash {
        push_string_field(out, RenderedStringField {
            indent: "    ",
            name: "weak_hash",
            value: weak_hash,
        });
    }
}

fn generate_pijul_kind_fields(
    out: &mut String,
    repository: &str,
    selector: &PijulSelector,
    state: &str,
    change: Option<&str>,
) {
    assert!(!repository.is_empty(), "pijul repository must not be empty");
    assert!(!state.is_empty(), "pijul state must not be empty");
    generate_vcs_common_fields(out, "pijul", repository);
    match selector {
        PijulSelector::Channel { channel } => push_selector_fields(out, "channel", channel),
        PijulSelector::State { channel, state } => {
            push_selector_fields(out, "state", state);
            push_string_field(out, RenderedStringField {
                indent: "    ",
                name: "channel",
                value: channel,
            });
        }
        PijulSelector::Change { channel, change } => {
            push_selector_fields(out, "change", change);
            push_string_field(out, RenderedStringField {
                indent: "    ",
                name: "channel",
                value: channel,
            });
        }
    }
    push_string_field(out, RenderedStringField {
        indent: "    ",
        name: "state",
        value: state,
    });
    if let Some(change) = change {
        push_string_field(out, RenderedStringField {
            indent: "    ",
            name: "change",
            value: change,
        });
    }
}

fn generate_fossil_kind_fields(out: &mut String, repository: &str, selector: &FossilSelector, checkin: &str) {
    assert!(!repository.is_empty(), "fossil repository must not be empty");
    assert!(!checkin.is_empty(), "fossil check-in must not be empty");
    generate_vcs_common_fields(out, "fossil", repository);
    match selector {
        FossilSelector::Branch(branch) => push_selector_fields(out, "branch", branch),
        FossilSelector::Tag(tag) => push_selector_fields(out, "tag", tag),
        FossilSelector::Checkin(value) => push_selector_fields(out, "checkin", value),
    }
    push_string_field(out, RenderedStringField {
        indent: "    ",
        name: "checkin",
        value: checkin,
    });
}

fn generate_vcs_common_fields(out: &mut String, kind_name: impl AsRef<str>, repository: &str) {
    let kind_name = kind_name.as_ref();
    push_string_field(out, RenderedStringField {
        indent: "    ",
        name: "type",
        value: kind_name,
    });
    push_string_field(out, RenderedStringField {
        indent: "    ",
        name: "repository",
        value: repository,
    });
}

fn push_selector_fields(out: &mut String, selector_type: impl AsRef<str>, selector_value: &str) {
    let selector_type = selector_type.as_ref();
    push_string_field(out, RenderedStringField {
        indent: "    ",
        name: "selector_type",
        value: selector_type,
    });
    push_string_field(out, RenderedStringField {
        indent: "    ",
        name: "selector_value",
        value: selector_value,
    });
}

fn render_field_name(name: &str) -> String {
    if !needs_quoting(name) {
        return name.to_string();
    }

    format!("\"{}\"", escape_nickel(name))
}

fn push_string_field(out: &mut String, field: RenderedStringField<'_>) {
    assert!(!field.indent.is_empty(), "field indent must not be empty");
    assert!(!field.name.is_empty(), "field name must not be empty");
    out.push_str(field.indent);
    out.push_str(field.name);
    out.push_str(" = \"");
    out.push_str(&escape_nickel(field.value));
    out.push_str("\",\n");
}

fn push_string_array(out: &mut String, array: RenderedStringArray<'_>) {
    assert!(!array.indent.is_empty(), "array indent must not be empty");
    assert!(!array.name.is_empty(), "array field name must not be empty");
    if array.values.is_empty() {
        return;
    }

    out.push_str(array.indent);
    out.push_str(array.name);
    out.push_str(" = [\n");
    for value in array.values {
        out.push_str(array.indent);
        out.push_str("  \"");
        out.push_str(&escape_nickel(value));
        out.push_str("\",\n");
    }
    out.push_str(array.indent);
    out.push_str("],\n");
}

/// Whether a Nickel field name needs quoting (contains non-ident chars).
fn needs_quoting(name: &str) -> bool {
    if name.is_empty() {
        return true;
    }
    let first = name.as_bytes()[0];
    let is_valid_start = first.is_ascii_alphabetic() || first == b'_';
    if !is_valid_start {
        return true;
    }
    !name.bytes().all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
}

/// Escape a string for inclusion in a Nickel double-quoted string.
fn escape_nickel(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

/// Compute a fingerprint of the generated content for drift detection.
///
/// Uses a simple hash of the content bytes. Two files with the same
/// fingerprint have the same content.
pub fn content_fingerprint(content: String) -> u64 {
    const FNV1A_OFFSET_BASIS_U64: u64 = 0xcbf29ce484222325;
    const FNV1A_PRIME_U64: u64 = 0x100000001b3;

    let mut hash: u64 = FNV1A_OFFSET_BASIS_U64;
    for byte in content.as_bytes() {
        hash ^= *byte as u64;
        hash = hash.wrapping_mul(FNV1A_PRIME_U64);
    }
    hash
}

#[cfg(test)]
mod tests {
    use alloc::collections::BTreeMap;
    use alloc::vec;

    use super::*;
    use crate::lock::*;
    use crate::manifest::HashAlgo;
    use crate::version::SchemaVersion;

    fn lock_with_file(name: &str, url: &str, hash: &str) -> Lockfile {
        let mut inputs = BTreeMap::new();
        inputs.insert(name.to_string(), LockEntry {
            kind: LockedKind::File { url: url.to_string() },
            hash: LockedHash {
                algo: HashAlgo::Sha256,
                value: hash.to_string(),
            },
            patches: vec![],
            mirrors: vec![],
            fetch_policy: crate::InputFetchPolicy::GenerationMaterial,
            freshness: None,
            trust: None,
        });
        Lockfile {
            version: SchemaVersion::CURRENT,
            inputs,
            patches: BTreeMap::new(),
        }
    }

    #[test]
    fn generate_empty_lock() {
        let lock = Lockfile::new();
        let ncl = generate_inputs_ncl(lock);
        assert!(ncl.starts_with("# Generated"));
        assert!(ncl.contains("{\n}\n"));
    }

    #[test]
    fn generate_file_entry() {
        let lock = lock_with_file("data", "https://example.com/data.bin", "sha256-abc=");
        let ncl = generate_inputs_ncl(lock);
        assert!(ncl.contains("data = {"));
        assert!(ncl.contains("type = \"file\""));
        assert!(ncl.contains("url = \"https://example.com/data.bin\""));
        assert!(ncl.contains("hash = \"sha256-abc=\""));
        assert!(ncl.contains("fetch_policy = \"generation-material\""));
    }

    #[test]
    fn generate_hyphenated_name_quoted() {
        let lock = lock_with_file("my-input", "https://example.com/f", "sha256-x=");
        let ncl = generate_inputs_ncl(lock);
        assert!(ncl.contains("\"my-input\" = {"));
    }

    #[test]
    fn generate_quoted_name_escapes_embedded_quote() {
        let lock = lock_with_file("my\"input", "https://example.com/f", "sha256-x=");
        let ncl = generate_inputs_ncl(lock);
        assert!(ncl.contains("\"my\\\"input\" = {"));
        assert!(!ncl.contains("\"my\"input\" = {"));
    }

    #[test]
    fn generate_git_entry() {
        let mut inputs = BTreeMap::new();
        inputs.insert("nixpkgs".to_string(), LockEntry {
            kind: LockedKind::Git {
                repository: "https://github.com/NixOS/nixpkgs.git".to_string(),
                rev: "abc123".to_string(),
                ref_name: Some("nixos-unstable".to_string()),
            },
            hash: LockedHash {
                algo: HashAlgo::Sha256,
                value: "sha256-xyz=".to_string(),
            },
            patches: vec![],
            mirrors: vec!["https://mirror.example.com/nixpkgs.git".to_string()],
            fetch_policy: crate::InputFetchPolicy::GenerationMaterial,
            freshness: None,
            trust: None,
        });
        let lock = Lockfile {
            version: SchemaVersion::CURRENT,
            inputs,
            patches: BTreeMap::new(),
        };

        let ncl = generate_inputs_ncl(lock);
        assert!(ncl.contains("type = \"git\""));
        assert!(ncl.contains("repository = \"https://github.com/NixOS/nixpkgs.git\""));
        assert!(ncl.contains("rev = \"abc123\""));
        assert!(ncl.contains("ref_name = \"nixos-unstable\""));
        assert!(ncl.contains("mirrors = ["));
        assert!(ncl.contains("\"https://mirror.example.com/nixpkgs.git\""));
    }

    #[test]
    fn generate_with_patches() {
        let mut lock = lock_with_file("src", "https://example.com/src.tar.gz", "sha256-h=");
        lock.inputs.get_mut("src").unwrap().patches = vec!["p1".into(), "p2".into()];
        lock.patches.insert("p1".into(), LockedPatch {
            source: LockedPatchSource::Local {
                path: "patches/p1.patch".into(),
            },
            hash: LockedHash {
                algo: HashAlgo::Sha256,
                value: "sha256-p1=".into(),
            },
            trust: None,
        });
        lock.patches.insert("p2".into(), LockedPatch {
            source: LockedPatchSource::Local {
                path: "patches/p2.patch".into(),
            },
            hash: LockedHash {
                algo: HashAlgo::Sha256,
                value: "sha256-p2=".into(),
            },
            trust: None,
        });
        let ncl = generate_inputs_ncl(lock);
        assert!(ncl.contains("patches = ["));
        assert!(ncl.contains("\"p1\""));
        assert!(ncl.contains("\"p2\""));
    }

    #[test]
    fn escape_special_chars() {
        assert_eq!(escape_nickel("a\"b"), "a\\\"b");
        assert_eq!(escape_nickel("a\\b"), "a\\\\b");
        assert_eq!(escape_nickel("a\nb"), "a\\nb");
    }

    #[test]
    fn needs_quoting_cases() {
        assert!(!needs_quoting("nixpkgs"));
        assert!(!needs_quoting("hello_world"));
        assert!(needs_quoting("hello-world"));
        assert!(needs_quoting("123abc"));
        assert!(needs_quoting(""));
    }

    #[test]
    fn fingerprint_deterministic() {
        let a = content_fingerprint("hello".to_string());
        let b = content_fingerprint("hello".to_string());
        assert_eq!(a, b);
    }

    #[test]
    fn fingerprint_differs() {
        let a = content_fingerprint("hello".to_string());
        let b = content_fingerprint("world".to_string());
        assert_ne!(a, b);
    }

    #[test]
    fn generate_includes_patch_metadata() {
        let mut inputs = BTreeMap::new();
        inputs.insert("pkg".to_string(), LockEntry {
            kind: LockedKind::File {
                url: "https://example.com/pkg".to_string(),
            },
            hash: LockedHash {
                algo: HashAlgo::Sha256,
                value: "sha256-abc=".to_string(),
            },
            patches: vec!["fix1".into()],
            mirrors: vec![],
            fetch_policy: crate::InputFetchPolicy::GenerationMaterial,
            freshness: None,
            trust: None,
        });
        let mut patches = BTreeMap::new();
        patches.insert("fix1".into(), LockedPatch {
            source: LockedPatchSource::Local {
                path: "patches/fix1.patch".into(),
            },
            hash: LockedHash {
                algo: HashAlgo::Sha256,
                value: "sha256-patchhash=".into(),
            },
            trust: None,
        });
        let lock = Lockfile {
            version: SchemaVersion::CURRENT,
            inputs,
            patches,
        };

        let ncl = generate_inputs_ncl(lock);
        assert!(ncl.contains("_patches = {"));
        assert!(ncl.contains("fix1 = {"));
        assert!(ncl.contains("type = \"local\""));
        assert!(ncl.contains("path = \"patches/fix1.patch\""));
        assert!(ncl.contains("hash = \"sha256-patchhash=\""));
    }

    #[test]
    fn generate_remote_patch_metadata() {
        let mut patches = BTreeMap::new();
        patches.insert("remote_fix".into(), LockedPatch {
            source: LockedPatchSource::Remote {
                url: "https://example.com/fix.patch".into(),
            },
            hash: LockedHash {
                algo: HashAlgo::Sha256,
                value: "sha256-remotehash=".into(),
            },
            trust: None,
        });
        let lock = Lockfile {
            version: SchemaVersion::CURRENT,
            inputs: BTreeMap::new(),
            patches,
        };

        let ncl = generate_inputs_ncl(lock);
        assert!(ncl.contains("_patches = {"));
        assert!(ncl.contains("type = \"remote\""));
        assert!(ncl.contains("url = \"https://example.com/fix.patch\""));
    }

    #[test]
    fn generate_quoted_patch_name_escapes_embedded_quote() {
        let mut patches = BTreeMap::new();
        patches.insert("fix\"name".into(), LockedPatch {
            source: LockedPatchSource::Local {
                path: "patches/fix.patch".into(),
            },
            hash: LockedHash {
                algo: HashAlgo::Sha256,
                value: "sha256-fix=".into(),
            },
            trust: None,
        });
        let lock = Lockfile {
            version: SchemaVersion::CURRENT,
            inputs: BTreeMap::new(),
            patches,
        };

        let ncl = generate_inputs_ncl(lock);
        assert!(ncl.contains("\"fix\\\"name\" = {"));
        assert!(!ncl.contains("\"fix\"name\" = {"));
    }

    #[test]
    fn generate_vcs_entries_include_native_lock_metadata() {
        let mut inputs = BTreeMap::new();
        inputs.insert("darcs".to_string(), LockEntry {
            kind: LockedKind::Darcs {
                repository: "https://example.invalid/repo.darcs".to_string(),
                selector: crate::DarcsSelector::Tag("v1".to_string()),
                context: Some("darcs-context".to_string()),
                weak_hash: Some("weak".to_string()),
            },
            hash: LockedHash {
                algo: HashAlgo::Blake3,
                value: "blake3-darcs=".to_string(),
            },
            patches: vec![],
            mirrors: vec![],
            fetch_policy: crate::InputFetchPolicy::GenerationMaterial,
            freshness: None,
            trust: None,
        });
        inputs.insert("pijul".to_string(), LockEntry {
            kind: LockedKind::Pijul {
                repository: "https://example.invalid/repo.pijul".to_string(),
                selector: crate::PijulSelector::Change {
                    channel: "main".to_string(),
                    change: "change".to_string(),
                },
                state: "state".to_string(),
                change: Some("change".to_string()),
            },
            hash: LockedHash {
                algo: HashAlgo::Blake3,
                value: "blake3-pijul=".to_string(),
            },
            patches: vec![],
            mirrors: vec![],
            fetch_policy: crate::InputFetchPolicy::GenerationMaterial,
            freshness: None,
            trust: None,
        });
        inputs.insert("fossil".to_string(), LockEntry {
            kind: LockedKind::Fossil {
                repository: "https://example.invalid/repo.fossil".to_string(),
                selector: crate::FossilSelector::Branch("trunk".to_string()),
                checkin: "checkin".to_string(),
            },
            hash: LockedHash {
                algo: HashAlgo::Blake3,
                value: "blake3-fossil=".to_string(),
            },
            patches: vec![],
            mirrors: vec![],
            fetch_policy: crate::InputFetchPolicy::GenerationMaterial,
            freshness: None,
            trust: None,
        });
        let ncl = generate_inputs_ncl(Lockfile {
            version: SchemaVersion::CURRENT,
            inputs,
            patches: BTreeMap::new(),
        });

        assert!(ncl.contains("type = \"darcs\""));
        assert!(ncl.contains("context = \"darcs-context\""));
        assert!(ncl.contains("weak_hash = \"weak\""));
        assert!(ncl.contains("type = \"pijul\""));
        assert!(ncl.contains("state = \"state\""));
        assert!(ncl.contains("change = \"change\""));
        assert!(ncl.contains("type = \"fossil\""));
        assert!(ncl.contains("checkin = \"checkin\""));
    }

    #[test]
    fn generate_panics_on_unlocked_patch_reference() {
        let mut lock = lock_with_file("src", "https://example.com/src.tar.gz", "sha256-h=");
        lock.inputs.get_mut("src").unwrap().patches = vec!["missing".into()];

        let panic_result = std::panic::catch_unwind(move || generate_inputs_ncl(lock));
        let panic_payload = panic_result.expect_err("generation should reject missing patch metadata");
        let panic_message = if let Some(message) = panic_payload.downcast_ref::<String>() {
            message.clone()
        } else if let Some(message) = panic_payload.downcast_ref::<&str>() {
            message.to_string()
        } else {
            String::new()
        };

        assert!(panic_message.contains("references unlocked patch 'missing'"));
        assert!(panic_message.contains("input 'src'"));
    }
}
