[workspace]
resolver = "2"
members = [
  "crates/crunch-eval",
  "crates/crunch-glue",
  "crates/crunch-store",
  "crates/crunch-build",
  "crates/crunch-pipeline",
  "crates/crunch-project",
  "crates/crunch-attestation",
  "crates/crunch-delta",
  "crates/crunch-shell",
  "vendor/nix-compat",
  "vendor/nix-compat-derive",
  "vendor/snix-build",
  "vendor/snix-castore",
  "vendor/snix-store",
  "vendor/snix-tracing",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"

[package]
name = "crunch"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "crunch"
path = "src/main.rs"

[dependencies]
crunch-pipeline = { path = "crates/crunch-pipeline" }
crunch-eval = { path = "crates/crunch-eval" }
crunch-glue = { path = "crates/crunch-glue" }
crunch-build = { path = "crates/crunch-build" }
crunch-store = { path = "crates/crunch-store" }
crunch-project = { path = "crates/crunch-project" }
crunch-attestation = { path = "crates/crunch-attestation" }
crunch-shell = { path = "crates/crunch-shell" }
nix-compat = { path = "vendor/nix-compat" }
snix-build = { path = "vendor/snix-build" }
snix-castore = { path = "vendor/snix-castore" }
snix-store = { path = "vendor/snix-store" }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
clap = { version = "4", features = ["derive", "env"] }
data-encoding = "2.6"
tempfile = "3"
blake3 = "=1.8.2"
digest = "=0.10.7"
sha2 = "0.10.8"
ureq = { version = "3.0", default-features = false, features = ["rustls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"
url = "2"
tar = "0.4"

[patch.crates-io]
fuse-backend-rs = { path = "vendor/fuse-backend-rs" }

[dev-dependencies]
crunch-delta = { path = "crates/crunch-delta" }
pretty_assertions = "1.0"
tempfile = "3"
assert_cmd = "2"
predicates = "3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
sha2 = "0.10.8"
base64 = "0.22"
tar = "0.4"
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
