[package]
name = "crunch-resource-policy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
crunch-resource-policy-core = { path = "../crunch-resource-policy-core" }
valence-core = { git = "ssh://git@github.com/OnixResearch/valence.git", rev = "e40c76b4d2070a29636e00c85c0dff93f03dba2f" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
pretty_assertions = "1.0"
