use std::path::Path;

use assert_cmd::Command;
use serde::Deserialize;

const BLAKE3_HEX_BYTES: usize = 64;
const EXPECTED_SCHEMA: &str = "mantle-cargo-import-plan-v1";
const PACKAGE_MANIFEST: &str = r#"[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "demo"
path = "src/main.rs"

[dependencies]
dep = { path = "dep" }
"#;
const DEP_MANIFEST: &str = r#"[package]
name = "dep"
version = "0.1.0"
edition = "2021"
"#;
const LOCKFILE: &str = r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "demo"
version = "0.1.0"

[[package]]
name = "dep"
version = "0.1.0"
"#;
const REGISTRY_DEP_MANIFEST: &str = r#"[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "demo"
path = "src/main.rs"

[dependencies]
serde = "1"
"#;

#[derive(Debug, Deserialize)]
struct ImportPlan {
    schema: String,
    selected_package: Option<String>,
    file_operations: Vec<ImportFileOperation>,
    blockers: Vec<ImportBlocker>,
    non_claims: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct ImportFileOperation {
    path: String,
    digest_blake3: String,
    content: String,
}

#[derive(Debug, Deserialize)]
struct ImportBlocker {
    class: String,
}

fn mantle_cmd() -> Command {
    Command::cargo_bin("mantle").expect("mantle binary should be built")
}

fn write_supported_workspace(root: &Path) {
    std::fs::create_dir_all(root.join("src")).unwrap();
    std::fs::create_dir_all(root.join("dep/src")).unwrap();
    std::fs::write(root.join("Cargo.toml"), PACKAGE_MANIFEST).unwrap();
    std::fs::write(root.join("Cargo.lock"), LOCKFILE).unwrap();
    std::fs::write(root.join("src/main.rs"), "fn main() { println!(\"demo\"); }\n").unwrap();
    std::fs::write(root.join("dep/Cargo.toml"), DEP_MANIFEST).unwrap();
    std::fs::write(root.join("dep/src/lib.rs"), "pub fn value() -> u8 { 1 }\n").unwrap();
}

fn run_import(root: &Path, mode: &str) -> std::process::Output {
    mantle_cmd()
        .current_dir(root)
        .arg("--json")
        .arg("import")
        .arg("cargo")
        .arg(mode)
        .output()
        .expect("mantle import cargo should execute")
}

fn parse_plan(output: &std::process::Output) -> ImportPlan {
    let stdout = String::from_utf8(output.stdout.clone()).unwrap();
    serde_json::from_str(&stdout).expect("plan JSON")
}

#[test]
fn cargo_import_plan_is_reviewable_and_side_effect_free() {
    let workspace = tempfile::tempdir().unwrap();
    write_supported_workspace(workspace.path());

    let output = run_import(workspace.path(), "--plan");
    let stderr = String::from_utf8_lossy(&output.stderr);
    let plan = parse_plan(&output);

    assert!(output.status.success(), "stderr: {stderr}");
    assert_eq!(plan.schema, EXPECTED_SCHEMA);
    assert_eq!(plan.selected_package.as_deref(), Some("demo"));
    assert!(plan.blockers.is_empty(), "blockers: {:?}", plan.blockers);
    assert_eq!(plan.file_operations.len(), 2);
    assert!(plan.file_operations.iter().any(|op| op.path == "mantle-project.ncl"));
    assert!(plan.file_operations.iter().any(|op| op.path == ".mantle/inputs.ncl"));
    assert!(plan.file_operations.iter().all(|op| op.digest_blake3.len() == BLAKE3_HEX_BYTES));
    assert!(plan.non_claims.contains(&"not-cargo-free-execution".to_string()));
    assert!(!workspace.path().join("mantle-project.ncl").exists());
    assert!(!workspace.path().join(".mantle/inputs.ncl").exists());
}

#[test]
fn cargo_import_apply_writes_bounded_files_and_project_shape() {
    let workspace = tempfile::tempdir().unwrap();
    write_supported_workspace(workspace.path());

    let output = run_import(workspace.path(), "--apply");
    let stderr = String::from_utf8_lossy(&output.stderr);
    let plan = parse_plan(&output);

    assert!(output.status.success(), "stderr: {stderr}");
    assert!(plan.blockers.is_empty(), "blockers: {:?}", plan.blockers);
    assert!(workspace.path().join("mantle-project.ncl").is_file());
    assert!(workspace.path().join(".mantle/inputs.ncl").is_file());
    let project_text = std::fs::read_to_string(workspace.path().join("mantle-project.ncl")).unwrap();
    let inputs_text = std::fs::read_to_string(workspace.path().join(".mantle/inputs.ncl")).unwrap();
    assert!(project_text.contains("mantle.offlineCargoPackage"));
    assert!(project_text.contains("not a module layer"));
    assert!(project_text.contains("packages.demo"));
    assert!(inputs_text.contains("placeholder \"demo-src\""));
    assert!(inputs_text.contains("placeholder \"rust\""));
}

#[test]
fn cargo_import_apply_fails_before_writing_conflicting_files() {
    let workspace = tempfile::tempdir().unwrap();
    write_supported_workspace(workspace.path());
    std::fs::write(workspace.path().join("mantle-project.ncl"), "# user project\n").unwrap();

    let output = run_import(workspace.path(), "--apply");
    let plan = parse_plan(&output);
    let classes: Vec<&str> = plan.blockers.iter().map(|blocker| blocker.class.as_str()).collect();

    assert!(!output.status.success());
    assert!(classes.contains(&"existing-file-conflict"), "classes: {classes:?}");
    assert!(!workspace.path().join(".mantle/inputs.ncl").exists());
}

#[test]
fn cargo_import_blocks_missing_lockfile_and_unsupported_registry_source() {
    let workspace = tempfile::tempdir().unwrap();
    std::fs::create_dir_all(workspace.path().join("src")).unwrap();
    std::fs::write(workspace.path().join("Cargo.toml"), REGISTRY_DEP_MANIFEST).unwrap();
    std::fs::write(workspace.path().join("src/main.rs"), "fn main() {}\n").unwrap();

    let output = run_import(workspace.path(), "--plan");
    let plan = parse_plan(&output);
    let classes: Vec<&str> = plan.blockers.iter().map(|blocker| blocker.class.as_str()).collect();

    assert!(!output.status.success());
    assert!(classes.contains(&"missing-lockfile"), "classes: {classes:?}");
    assert!(classes.contains(&"unsupported-dependency-source"), "classes: {classes:?}");
    assert!(plan.file_operations.is_empty());
}
