use assert_cmd::Command;
use serde_json::Value;
use tempfile::TempDir;

#[cfg(unix)]
const EXECUTABLE_PERMISSIONS: u32 = 0o755;

fn mantle_cmd() -> Command {
    Command::cargo_bin("mantle").expect("mantle binary should be built")
}

fn write_tiny_mantle_fixture(dir: &TempDir) -> std::path::PathBuf {
    let root = dir.path().join("tiny-mantle");
    std::fs::create_dir_all(root.join("src")).unwrap();
    std::fs::write(root.join("src/main.rs"), "fn main() { println!(\"tiny mantle\"); }\n").unwrap();
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"mantle\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[[bin]]\nname = \"mantle\"\npath = \"src/main.rs\"\n",
    )
    .unwrap();
    std::fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"mantle\"\nversion = \"0.1.0\"\n",
    )
    .unwrap();
    root
}

#[cfg(unix)]
fn write_executable(path: &std::path::Path, contents: &str) {
    use std::os::unix::fs::PermissionsExt;
    std::fs::write(path, contents).unwrap();
    let permissions = std::fs::Permissions::from_mode(EXECUTABLE_PERMISSIONS);
    std::fs::set_permissions(path, permissions).unwrap();
}

#[test]
fn cargo_free_self_build_builds_tiny_mantle_fixture() {
    let dir = TempDir::new().unwrap();
    let root = write_tiny_mantle_fixture(&dir);
    let out_dir = dir.path().join("cargo-free-out");

    let output = mantle_cmd()
        .current_dir(&root)
        .arg("--json")
        .arg("self-build")
        .arg("--cargo-free")
        .arg("--out")
        .arg(&out_dir)
        .output()
        .expect("cargo-free self-build CLI should run");

    assert!(
        output.status.success(),
        "stdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let summary: Value = serde_json::from_slice(&output.stdout).expect("summary JSON should parse");
    assert_eq!(summary["schema"], "mantle-cargo-free-self-build-v1");
    assert_eq!(summary["status"], "success");
    assert_eq!(summary["cargo_marker_absent"], true);
    assert_eq!(summary["execution_status"], "success");
    assert!(summary["unit_count"].as_u64().unwrap() >= 1);
    assert_eq!(summary["failed_unit_count"], 0);
    assert!(summary["source_digest"].is_object(), "{summary:#?}");
    assert!(out_dir.join("mantle").is_file());
    assert!(out_dir.join("receipt.json").is_file());
    assert!(out_dir.join("meta.json").is_file());
    assert!(!out_dir.join("cargo-was-invoked").exists());
}

#[cfg(unix)]
#[test]
fn cargo_free_self_build_fails_if_ambient_cargo_is_invoked() {
    let dir = TempDir::new().unwrap();
    let root = write_tiny_mantle_fixture(&dir);
    let out_dir = dir.path().join("cargo-free-out");
    let fake_rustc = dir.path().join("rustc-invokes-cargo");
    write_executable(&fake_rustc, "#!/bin/sh\ncargo --version >/dev/null 2>&1\nexit 1\n");

    let output = mantle_cmd()
        .current_dir(&root)
        .arg("--json")
        .arg("self-build")
        .arg("--cargo-free")
        .arg("--out")
        .arg(&out_dir)
        .arg("--rustc")
        .arg(&fake_rustc)
        .output()
        .expect("cargo-free self-build CLI should run");

    assert!(!output.status.success(), "stdout:\n{}", String::from_utf8_lossy(&output.stdout));
    assert!(out_dir.join("cargo-was-invoked").is_file());
    let summary: Value = serde_json::from_slice(&output.stdout).expect("blocked summary JSON should parse");
    assert_eq!(summary["status"], "blocked");
    assert_eq!(summary["cargo_marker_absent"], false);
    assert_eq!(summary["blocker"], "cargo guard was invoked");
    assert!(!out_dir.join("mantle").exists());
    assert!(out_dir.join("smoke-stdout.txt").is_file());
    assert!(out_dir.join("smoke-stderr.txt").is_file());
    let smoke_stderr = std::fs::read_to_string(out_dir.join("smoke-stderr.txt")).unwrap();
    assert!(smoke_stderr.contains("not run: blocked before binary"));
}
