use std::path::Path;

use assert_cmd::Command;
use serde::Deserialize;
use sha2::Digest;
use sha2::Sha256;

const BLAKE3_HEX_BYTES: usize = 64;
const EXPECTED_SCHEMA: &str = "mantle-cargo-import-plan-v1";
const PACKAGE_MANIFEST: &str = r#"[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "demo"
path = "src/main.rs"

[dependencies]
dep = { path = "dep" }
"#;
const DEP_MANIFEST: &str = r#"[package]
name = "dep"
version = "0.1.0"
edition = "2021"
"#;
const LOCKFILE: &str = r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "demo"
version = "0.1.0"

[[package]]
name = "dep"
version = "0.1.0"
"#;
const REGISTRY_DEP_MANIFEST: &str = r#"[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "demo"
path = "src/main.rs"

[dependencies]
serde = "1"
"#;
const REGISTRY_LOCKFILE: &str = r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "demo"
version = "0.1.0"
dependencies = ["serde"]

[[package]]
name = "serde"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
"#;
const CARGO_VENDOR_CONFIG: &str = r#"[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

[net]
offline = true
"#;

#[derive(Debug, Deserialize)]
struct ImportPlan {
    schema: String,
    selected_package: Option<String>,
    file_operations: Vec<ImportFileOperation>,
    source_inputs: Vec<ImportSourceInput>,
    vendor_source: Option<ImportVendorSource>,
    blockers: Vec<ImportBlocker>,
    non_claims: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct ImportFileOperation {
    path: String,
    digest_blake3: String,
    content: String,
}

#[derive(Debug, Deserialize)]
struct ImportSourceInput {
    role: String,
    field: String,
    name: String,
}

#[derive(Debug, Deserialize)]
struct ImportVendorSource {
    role: String,
    field: String,
    name: String,
    root: String,
    digest_blake3: Option<String>,
    packages: Vec<ImportVendorPackage>,
}

#[derive(Debug, Deserialize)]
struct ImportVendorPackage {
    name: String,
    version: String,
    checksum_status: String,
}

#[derive(Debug, Deserialize)]
struct ImportBlocker {
    class: String,
}

fn mantle_cmd() -> Command {
    Command::cargo_bin("mantle").expect("mantle binary should be built")
}

fn write_supported_workspace(root: &Path) {
    std::fs::create_dir_all(root.join("src")).unwrap();
    std::fs::create_dir_all(root.join("dep/src")).unwrap();
    std::fs::write(root.join("Cargo.toml"), PACKAGE_MANIFEST).unwrap();
    std::fs::write(root.join("Cargo.lock"), LOCKFILE).unwrap();
    std::fs::write(root.join("src/main.rs"), "fn main() { println!(\"demo\"); }\n").unwrap();
    std::fs::write(root.join("dep/Cargo.toml"), DEP_MANIFEST).unwrap();
    std::fs::write(root.join("dep/src/lib.rs"), "pub fn value() -> u8 { 1 }\n").unwrap();
}

fn write_vendored_registry_workspace(root: &Path) {
    std::fs::create_dir_all(root.join("src")).unwrap();
    std::fs::create_dir_all(root.join(".cargo")).unwrap();
    std::fs::create_dir_all(root.join("vendor/serde/src")).unwrap();
    std::fs::write(root.join("Cargo.toml"), REGISTRY_DEP_MANIFEST).unwrap();
    std::fs::write(root.join("Cargo.lock"), REGISTRY_LOCKFILE).unwrap();
    std::fs::write(root.join("src/main.rs"), "fn main() {}\n").unwrap();
    std::fs::write(root.join(".cargo/config.toml"), CARGO_VENDOR_CONFIG).unwrap();
    std::fs::write(
        root.join("vendor/serde/Cargo.toml"),
        "[package]\nname = \"serde\"\nversion = \"1.0.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    let lib_bytes = b"pub fn marker() {}\n";
    std::fs::write(root.join("vendor/serde/src/lib.rs"), lib_bytes).unwrap();
    let lib_sha256 = format!("{:x}", Sha256::digest(lib_bytes));
    std::fs::write(
        root.join("vendor/serde/.cargo-checksum.json"),
        format!(r#"{{"files":{{"src/lib.rs":"{lib_sha256}"}},"package":null}}"#),
    )
    .unwrap();
}

fn run_import(root: &Path, mode: &str) -> std::process::Output {
    mantle_cmd()
        .current_dir(root)
        .arg("--json")
        .arg("import")
        .arg("cargo")
        .arg(mode)
        .output()
        .expect("mantle import cargo should execute")
}

fn parse_plan(output: &std::process::Output) -> ImportPlan {
    let stdout = String::from_utf8(output.stdout.clone()).unwrap();
    serde_json::from_str(&stdout).expect("plan JSON")
}

#[test]
fn cargo_import_plan_is_reviewable_and_side_effect_free() {
    let workspace = tempfile::tempdir().unwrap();
    write_supported_workspace(workspace.path());

    let output = run_import(workspace.path(), "--plan");
    let stderr = String::from_utf8_lossy(&output.stderr);
    let plan = parse_plan(&output);

    assert!(output.status.success(), "stderr: {stderr}");
    assert_eq!(plan.schema, EXPECTED_SCHEMA);
    assert_eq!(plan.selected_package.as_deref(), Some("demo"));
    assert!(plan.blockers.is_empty(), "blockers: {:?}", plan.blockers);
    assert_eq!(plan.file_operations.len(), 2);
    assert!(plan.file_operations.iter().any(|op| op.path == "mantle-project.ncl"));
    assert!(plan.file_operations.iter().any(|op| op.path == ".mantle/inputs.ncl"));
    assert!(plan.file_operations.iter().all(|op| op.digest_blake3.len() == BLAKE3_HEX_BYTES));
    assert!(plan.non_claims.contains(&"not-cargo-free-execution".to_string()));
    assert!(!workspace.path().join("mantle-project.ncl").exists());
    assert!(!workspace.path().join(".mantle/inputs.ncl").exists());
}

#[test]
fn cargo_import_apply_writes_bounded_files_and_project_shape() {
    let workspace = tempfile::tempdir().unwrap();
    write_supported_workspace(workspace.path());

    let output = run_import(workspace.path(), "--apply");
    let stderr = String::from_utf8_lossy(&output.stderr);
    let plan = parse_plan(&output);

    assert!(output.status.success(), "stderr: {stderr}");
    assert!(plan.blockers.is_empty(), "blockers: {:?}", plan.blockers);
    assert!(workspace.path().join("mantle-project.ncl").is_file());
    assert!(workspace.path().join(".mantle/inputs.ncl").is_file());
    let project_text = std::fs::read_to_string(workspace.path().join("mantle-project.ncl")).unwrap();
    let inputs_text = std::fs::read_to_string(workspace.path().join(".mantle/inputs.ncl")).unwrap();
    assert!(project_text.contains("mantle.offlineCargoPackage"));
    assert!(project_text.contains("not a module layer"));
    assert!(project_text.contains("packages.demo"));
    assert!(inputs_text.contains("placeholder \"demo-src\""));
    assert!(inputs_text.contains("placeholder \"rust\""));
}

#[test]
fn cargo_import_apply_matches_reviewed_plan_bytes_and_is_repeatable() {
    let workspace = tempfile::tempdir().unwrap();
    write_supported_workspace(workspace.path());
    let plan = run_import(workspace.path(), "--plan");
    assert!(plan.status.success());
    let planned = parse_plan(&plan);

    for _ in 0..2 {
        let applied = run_import(workspace.path(), "--apply");
        assert!(applied.status.success(), "stderr: {}", String::from_utf8_lossy(&applied.stderr));
        for operation in &planned.file_operations {
            assert_eq!(
                std::fs::read(workspace.path().join(&operation.path)).unwrap(),
                operation.content.as_bytes(),
                "{}",
                operation.path
            );
        }
    }
}

#[test]
fn cargo_import_plan_accepts_declared_vendored_registry_source() {
    let workspace = tempfile::tempdir().unwrap();
    write_vendored_registry_workspace(workspace.path());

    let output = run_import(workspace.path(), "--plan");
    let stderr = String::from_utf8_lossy(&output.stderr);
    let plan = parse_plan(&output);

    assert!(output.status.success(), "stderr: {stderr}; blockers: {:?}", plan.blockers);
    assert!(plan.blockers.is_empty(), "blockers: {:?}", plan.blockers);
    let vendor = plan.vendor_source.as_ref().expect("vendor source accepted");
    assert_eq!(vendor.role, "vendored-dependencies");
    assert_eq!(vendor.field, "vendor_src");
    assert_eq!(vendor.name, "demo-vendor");
    assert_eq!(vendor.root, "vendor");
    assert_eq!(vendor.digest_blake3.as_ref().unwrap().len(), BLAKE3_HEX_BYTES);
    assert_eq!(vendor.packages.len(), 1);
    assert_eq!(vendor.packages[0].name, "serde");
    assert_eq!(vendor.packages[0].version, "1.0.0");
    assert_eq!(vendor.packages[0].checksum_status, "verified");
    assert!(plan.source_inputs.iter().any(|input| {
        input.role == "vendored-dependencies" && input.field == "vendor_src" && input.name == "demo-vendor"
    }));
    assert!(plan.file_operations.iter().any(|op| op.content.contains("vendor_src = inputs.vendor_src")));
    assert!(plan.non_claims.contains(&"not-network-vendoring".to_string()));
    assert!(plan.non_claims.contains(&"not-full-cargo-compatibility".to_string()));
    assert!(!workspace.path().join("mantle-project.ncl").exists());
}

#[test]
fn cargo_import_apply_wires_vendor_input_into_generated_project() {
    let workspace = tempfile::tempdir().unwrap();
    write_vendored_registry_workspace(workspace.path());

    let output = run_import(workspace.path(), "--apply");
    let stderr = String::from_utf8_lossy(&output.stderr);
    let plan = parse_plan(&output);

    assert!(output.status.success(), "stderr: {stderr}; blockers: {:?}", plan.blockers);
    let project_text = std::fs::read_to_string(workspace.path().join("mantle-project.ncl")).unwrap();
    let inputs_text = std::fs::read_to_string(workspace.path().join(".mantle/inputs.ncl")).unwrap();
    assert!(project_text.contains("vendor_src = inputs.vendor_src"));
    assert!(project_text.contains("vendor_name = \"demo-vendor\""));
    assert!(inputs_text.contains("placeholder \"demo-vendor\""));
}

#[test]
fn cargo_import_apply_rejects_stale_vendor_checksum_before_writes() {
    let workspace = tempfile::tempdir().unwrap();
    write_vendored_registry_workspace(workspace.path());
    std::fs::write(workspace.path().join("vendor/serde/src/lib.rs"), "pub fn tampered() {}\n").unwrap();

    let output = run_import(workspace.path(), "--apply");
    let plan = parse_plan(&output);
    let classes: Vec<&str> = plan.blockers.iter().map(|blocker| blocker.class.as_str()).collect();

    assert!(!output.status.success());
    assert!(classes.contains(&"stale-vendor-checksum"), "classes: {classes:?}");
    assert!(!workspace.path().join("mantle-project.ncl").exists());
    assert!(!workspace.path().join(".mantle/inputs.ncl").exists());
}

#[test]
fn cargo_import_ignores_ambient_cargo_home_vendor_material() {
    let workspace = tempfile::tempdir().unwrap();
    let cargo_home = tempfile::tempdir().unwrap();
    write_vendored_registry_workspace(cargo_home.path());
    std::fs::create_dir_all(workspace.path().join("src")).unwrap();
    std::fs::write(workspace.path().join("Cargo.toml"), REGISTRY_DEP_MANIFEST).unwrap();
    std::fs::write(workspace.path().join("Cargo.lock"), REGISTRY_LOCKFILE).unwrap();
    std::fs::write(workspace.path().join("src/main.rs"), "fn main() {}\n").unwrap();

    let output = mantle_cmd()
        .current_dir(workspace.path())
        .env("CARGO_HOME", cargo_home.path())
        .arg("--json")
        .arg("import")
        .arg("cargo")
        .arg("--plan")
        .output()
        .expect("mantle import cargo should execute");
    let plan = parse_plan(&output);
    let classes: Vec<&str> = plan.blockers.iter().map(|blocker| blocker.class.as_str()).collect();

    assert!(!output.status.success());
    assert!(classes.contains(&"missing-vendored-source"), "classes: {classes:?}");
    assert!(plan.vendor_source.is_none());
}

#[test]
fn cargo_import_apply_fails_before_writing_conflicting_files() {
    let workspace = tempfile::tempdir().unwrap();
    write_supported_workspace(workspace.path());
    std::fs::write(workspace.path().join("mantle-project.ncl"), "# user project\n").unwrap();

    let output = run_import(workspace.path(), "--apply");
    let plan = parse_plan(&output);
    let classes: Vec<&str> = plan.blockers.iter().map(|blocker| blocker.class.as_str()).collect();

    assert!(!output.status.success());
    assert!(classes.contains(&"existing-file-conflict"), "classes: {classes:?}");
    assert!(!workspace.path().join(".mantle/inputs.ncl").exists());
    let human = mantle_cmd().current_dir(workspace.path()).args(["import", "cargo", "--apply"]).output().unwrap();
    assert_eq!(human.status.code(), Some(3));
    assert!(String::from_utf8_lossy(&human.stdout).starts_with("Cargo import plan for"));
    assert!(human.stderr.is_empty());
}

#[test]
fn cargo_import_blocks_missing_lockfile_and_unsupported_registry_source() {
    let workspace = tempfile::tempdir().unwrap();
    std::fs::create_dir_all(workspace.path().join("src")).unwrap();
    std::fs::write(workspace.path().join("Cargo.toml"), REGISTRY_DEP_MANIFEST).unwrap();
    std::fs::write(workspace.path().join("src/main.rs"), "fn main() {}\n").unwrap();

    let output = run_import(workspace.path(), "--plan");
    let plan = parse_plan(&output);
    let classes: Vec<&str> = plan.blockers.iter().map(|blocker| blocker.class.as_str()).collect();

    assert!(!output.status.success());
    assert!(classes.contains(&"missing-lockfile"), "classes: {classes:?}");
    assert!(classes.contains(&"missing-lock-entry"), "classes: {classes:?}");
    assert!(plan.file_operations.is_empty());
}

#[cfg(unix)]
#[test]
fn cargo_import_rejects_symlink_output_parent_before_any_write() {
    let workspace = tempfile::tempdir().unwrap();
    let external = tempfile::tempdir().unwrap();
    write_supported_workspace(workspace.path());
    std::os::unix::fs::symlink(external.path(), workspace.path().join(".mantle")).unwrap();

    let output = run_import(workspace.path(), "--apply");
    assert!(!output.status.success());
    assert!(
        String::from_utf8_lossy(&output.stderr).contains("symlink import output"),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(!workspace.path().join("mantle-project.ncl").exists());
    assert!(!external.path().join("inputs.ncl").exists());
}

#[test]
fn cargo_import_rejects_overlapping_output_targets_before_writing() {
    let workspace = tempfile::tempdir().unwrap();
    write_supported_workspace(workspace.path());
    let output = mantle_cmd()
        .current_dir(workspace.path())
        .args(["import", "cargo", "--apply", "--project-file", ".mantle"])
        .output()
        .expect("cargo importer should run");

    assert!(!output.status.success());
    assert!(String::from_utf8_lossy(&output.stderr).contains("output targets overlap"));
    assert!(!workspace.path().join(".mantle").exists());
}
