use std::ffi::OsString;
use std::path::Path;

use assert_cmd::Command;
use crunch_glue::CrunchDerivation;

const TARGET: &str = "x86_64-unknown-linux-musl";
const EXPECTED_SMOKE_STDOUT: &str = "offline-cargo-smoke";

fn mantle_cmd() -> Command {
    Command::cargo_bin("mantle").expect("mantle binary should be built")
}

fn can_build() -> bool {
    Path::new("/nix/store").exists()
        && std::process::Command::new("bwrap")
            .arg("--version")
            .output()
            .is_ok_and(|output| output.status.success())
}

fn eval_derivation(source: &str) -> Result<CrunchDerivation, crunch_eval::Error> {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("main.ncl");
    std::fs::write(&path, source).unwrap();
    let stdlib = crunch_eval::stdlib::stdlib_import_path().unwrap();
    let import_paths: Vec<OsString> = vec![stdlib.into_os_string()];
    crunch_eval::evaluate_and_deserialize(&path, &import_paths)
}

fn valid_offline_cargo_package_expr(binary: &str) -> String {
    format!(
        r#"let mantle = import "lib.ncl" in
let dummy = fun package_name => {{
  name = package_name,
  builder = "/bin/sh",
  args = ["-c", "echo dummy > $out"],
  addressing_mode = 'input-addressed,
}} | mantle.Derivation in
mantle.offlineCargoPackage {{
  name = "demo",
  src = dummy "demo-src",
  source_name = "demo-src",
  rust = dummy "rust",
  rust_name = "rust",
  seed_toolchain = dummy "musl-seed-toolchain",
  seed_toolchain_name = "musl-seed-toolchain",
  musl = dummy "musl",
  musl_name = "musl",
  binary = "{binary}",
  target = "{TARGET}",
}}
"#,
    )
}

#[test]
fn offline_cargo_helper_lowers_to_derivation_with_bounded_evidence() {
    let drv = eval_derivation(&valid_offline_cargo_package_expr("demo")).unwrap();
    let script = drv.args.join("\n");

    assert_eq!(drv.name, "demo");
    assert_eq!(drv.builder, "/bin/sh");
    assert_eq!(drv.inputs.len(), 4);
    assert_eq!(drv.env["MANTLE_BUILD_EVIDENCE_CLASS"], "cargo-inside-mantle-sandbox");
    assert!(script.contains("cargo build --locked --offline --release --bin demo"));
    assert!(script.contains("share/mantle/offline-cargo-build.json"));
    assert!(script.contains("mantle-offline-cargo-build-evidence-v2"));
    assert!(script.contains("\"lockfile\": {\"role\":\"cargo-lockfile\""));
    assert!(script.contains("\"identity_class\":\"blake3-content\""));
    assert!(script.contains("\"result\": \"undeclared-network-denied\""));
    assert!(script.contains("not-cargo-free-execution"));
    assert!(script.contains("not-full-cargo-compatibility"));
}

#[test]
fn offline_cargo_helper_rejects_missing_binary_name() {
    let err = eval_derivation(&valid_offline_cargo_package_expr("")).unwrap_err();
    let rendered = err.to_string();

    assert!(rendered.contains("invalid derivation name") || rendered.contains("contract"), "{rendered}");
    assert!(!rendered.contains("cargo-inside-mantle-sandbox"));
}

#[test]
fn offline_cargo_project_run_executes_declared_sandbox_cargo_output() {
    if !can_build() {
        eprintln!("SKIP: offline Cargo project run requires Linux + bwrap + /nix/store");
        return;
    }
    let project = tempfile::tempdir().unwrap();
    let store = tempfile::tempdir().unwrap();
    let state = tempfile::tempdir().unwrap();
    std::fs::write(project.path().join("crunch.ncl"), fake_cargo_project_ncl()).unwrap();

    let output = mantle_cmd()
        .current_dir(project.path())
        .arg("--store")
        .arg(store.path())
        .arg("--state-dir")
        .arg(state.path())
        .arg("run")
        .arg(".#demo")
        .arg("--no-substitute")
        .output()
        .expect("mantle run should execute");
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);

    assert!(output.status.success(), "stdout:\n{stdout}\nstderr:\n{stderr}");
    assert_eq!(stdout.trim(), EXPECTED_SMOKE_STDOUT);
    assert!(stderr.contains("running:"), "stderr should name selected output binary: {stderr}");
}

fn fake_cargo_project_ncl() -> &'static str {
    r#"let mantle = import "lib.ncl" in
let fakeSource = {
  name = "demo-src",
  builder = "/bin/sh",
  args = ["-c", m%"
    BB=/bin/busybox
    $BB mkdir -p $out/src
    $BB cat > $out/Cargo.toml << 'EOF'
[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "demo"
path = "src/main.rs"
EOF
    $BB cat > $out/Cargo.lock << 'EOF'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "demo"
version = "0.1.0"
EOF
    $BB cat > $out/src/main.rs << 'EOF'
fn main() { println!("offline-cargo-smoke"); }
EOF
  "%],
  addressing_mode = 'input-addressed,
} | mantle.Derivation in
let fakeRust = {
  name = "rust",
  builder = "/bin/sh",
  args = ["-c", m%"
    BB=/bin/busybox
    $BB mkdir -p $out/bin
    $BB cat > $out/bin/cargo << 'EOF'
#!/bin/sh
set -eu
if [ "${CARGO_HOME:-}" != "/tmp/cargo-home" ]; then
  echo "unexpected CARGO_HOME=${CARGO_HOME:-}" >&2
  exit 1
fi
if [ "${CARGO_TARGET_DIR:-}" != "/tmp/cargo-target" ]; then
  echo "unexpected CARGO_TARGET_DIR=${CARGO_TARGET_DIR:-}" >&2
  exit 1
fi
if [ "$1" != "build" ]; then
  echo "unexpected cargo command $1" >&2
  exit 1
fi
mkdir -p "$CARGO_TARGET_DIR/x86_64-unknown-linux-musl/release"
cat > "$CARGO_TARGET_DIR/x86_64-unknown-linux-musl/release/demo" << 'BIN'
#!/bin/sh
echo offline-cargo-smoke
BIN
chmod +x "$CARGO_TARGET_DIR/x86_64-unknown-linux-musl/release/demo"
EOF
    $BB chmod +x $out/bin/cargo
    $BB cat > $out/bin/rustc << 'EOF'
#!/bin/sh
echo fake rustc
EOF
    $BB chmod +x $out/bin/rustc
  "%],
  addressing_mode = 'input-addressed,
} | mantle.Derivation in
let fakeSeed = {
  name = "musl-seed-toolchain",
  builder = "/bin/sh",
  args = ["-c", m%"
    BB=/bin/busybox
    $BB mkdir -p $out/bin $out/x86_64-linux-musl/lib
    $BB cat > $out/bin/x86_64-linux-musl-gcc << 'EOF'
#!/bin/sh
exit 0
EOF
    $BB chmod +x $out/bin/x86_64-linux-musl-gcc
  "%],
  addressing_mode = 'input-addressed,
} | mantle.Derivation in
let fakeMusl = {
  name = "musl",
  builder = "/bin/sh",
  args = ["-c", "BB=/bin/busybox; $BB mkdir -p $out/lib; : > $out/lib/libc.so"],
  addressing_mode = 'input-addressed,
} | mantle.Derivation in
{
  packages.demo = mantle.offlineCargoPackage {
    name = "demo",
    src = fakeSource,
    source_name = "demo-src",
    rust = fakeRust,
    rust_name = "rust",
    seed_toolchain = fakeSeed,
    seed_toolchain_name = "musl-seed-toolchain",
    musl = fakeMusl,
    musl_name = "musl",
    binary = "demo",
    target = "x86_64-unknown-linux-musl",
  },
  default.package = "demo",
} | mantle.Project
"#
}
