use std::collections::BTreeSet;
use std::path::Path;

use assert_cmd::Command;
use serde_json::Value;

const EXPECTED_STDOUT: &str = "representative-rail-ok";
const BWRAP_SKIP: &str = "SKIP: representative rail offline Cargo smoke requires Linux + bwrap + /nix/store";
const FAILING_CARGO_SHIM: &str = "#!/bin/sh\necho cargo must not be invoked >&2\nexit 99\n";
const EXECUTABLE_MODE: u32 = 0o755;
const BLOCKER_MISSING_VENDOR: &str = "missing-vendored-registry-source";
const BLOCKER_STALE_LOCK: &str = "stale-lockfile-digest";
const BLOCKER_BUILD_METADATA: &str = "malformed-build-script-metadata";
const BLOCKER_PROC_MACRO: &str = "missing-proc-macro-host-artifact";
const BLOCKER_NATIVE_LINK: &str = "unsupported-native-link-metadata";

fn mantle_cmd() -> Command {
    Command::cargo_bin("mantle").expect("mantle binary should be built")
}

fn can_build() -> bool {
    Path::new("/nix/store").exists()
        && std::process::Command::new("bwrap")
            .arg("--version")
            .output()
            .is_ok_and(|output| output.status.success())
}

fn write_representative_workspace(root: &Path) {
    std::fs::create_dir_all(root.join("src")).unwrap();
    std::fs::create_dir_all(root.join("local-lib/src")).unwrap();
    std::fs::create_dir_all(root.join("compat-macro/src")).unwrap();
    std::fs::create_dir_all(root.join("vendor/serde/src")).unwrap();
    std::fs::create_dir_all(root.join(".cargo")).unwrap();
    std::fs::write(root.join("Cargo.toml"), representative_manifest()).unwrap();
    std::fs::write(root.join("Cargo.lock"), representative_lockfile()).unwrap();
    std::fs::write(root.join("build.rs"), representative_build_rs()).unwrap();
    std::fs::write(root.join("src/main.rs"), representative_main_rs()).unwrap();
    std::fs::write(root.join("local-lib/Cargo.toml"), local_lib_manifest()).unwrap();
    std::fs::write(root.join("local-lib/src/lib.rs"), "pub fn message() -> &'static str { \"local\" }\n").unwrap();
    std::fs::write(root.join("compat-macro/Cargo.toml"), proc_macro_manifest()).unwrap();
    std::fs::write(root.join("compat-macro/src/lib.rs"), proc_macro_lib_rs()).unwrap();
    std::fs::write(root.join("vendor/serde/Cargo.toml"), vendor_manifest()).unwrap();
    std::fs::write(root.join("vendor/serde/src/lib.rs"), "pub fn marker() {}\n").unwrap();
    std::fs::write(root.join(".cargo/config.toml"), cargo_config()).unwrap();
}

fn representative_manifest() -> &'static str {
    r#"[package]
name = "compat-demo"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[[bin]]
name = "compat-demo"
path = "src/main.rs"

[dependencies]
local-lib = { path = "local-lib" }
compat-macro = { path = "compat-macro" }
serde = "1.0.0"
"#
}

fn representative_lockfile() -> &'static str {
    r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "compat-demo"
version = "0.1.0"
dependencies = ["compat-macro", "local-lib", "serde"]

[[package]]
name = "compat-macro"
version = "0.1.0"

[[package]]
name = "local-lib"
version = "0.1.0"

[[package]]
name = "serde"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
"#
}

fn representative_build_rs() -> &'static str {
    "fn main() { println!(\"cargo:rustc-env=COMPAT_BUILD_SCRIPT=ok\"); }\n"
}

fn representative_main_rs() -> &'static str {
    r#"use compat_macro::compat_marker;

#[compat_marker]
fn main() {
    println!("representative-rail-ok");
}
"#
}

fn local_lib_manifest() -> &'static str {
    r#"[package]
name = "local-lib"
version = "0.1.0"
edition = "2021"
"#
}

fn proc_macro_manifest() -> &'static str {
    r#"[package]
name = "compat-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
"#
}

fn proc_macro_lib_rs() -> &'static str {
    r#"extern crate proc_macro;
use proc_macro::TokenStream;

#[proc_macro_attribute]
pub fn compat_marker(_attr: TokenStream, item: TokenStream) -> TokenStream {
    item
}
"#
}

fn vendor_manifest() -> &'static str {
    r#"[package]
name = "serde"
version = "1.0.0"
edition = "2021"
"#
}

fn cargo_config() -> &'static str {
    r#"[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

[net]
offline = true
"#
}

fn rail_blockers(root: &Path, expected_lock_digest: &str) -> BTreeSet<&'static str> {
    let mut blockers = BTreeSet::new();
    if !root.join("vendor/serde/Cargo.toml").is_file() {
        blockers.insert(BLOCKER_MISSING_VENDOR);
    }
    let lock_digest = std::fs::read(root.join("Cargo.lock"))
        .map(|bytes| blake3::hash(&bytes).to_hex().to_string())
        .unwrap_or_default();
    if lock_digest != expected_lock_digest {
        blockers.insert(BLOCKER_STALE_LOCK);
    }
    let build_rs = std::fs::read_to_string(root.join("build.rs")).unwrap_or_default();
    if !build_rs.contains("cargo:rustc-env=COMPAT_BUILD_SCRIPT=ok") {
        blockers.insert(BLOCKER_BUILD_METADATA);
    }
    if !root.join("compat-macro/src/lib.rs").is_file() {
        blockers.insert(BLOCKER_PROC_MACRO);
    }
    let manifest = std::fs::read_to_string(root.join("Cargo.toml")).unwrap_or_default();
    if manifest.contains("links = ") {
        blockers.insert(BLOCKER_NATIVE_LINK);
    }
    blockers
}

fn fake_cargo_project_ncl() -> &'static str {
    r#"let mantle = import "lib.ncl" in
let fakeSource = {
  name = "compat-demo-src",
  builder = "/bin/sh",
  args = ["-c", m%"
    BB=/bin/busybox
    $BB mkdir -p $out/src $out/local-lib/src $out/compat-macro/src $out/vendor/serde/src $out/.cargo
    $BB cat > $out/Cargo.toml << 'EOF'
[package]
name = "compat-demo"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[[bin]]
name = "compat-demo"
path = "src/main.rs"

[dependencies]
local-lib = { path = "local-lib" }
compat-macro = { path = "compat-macro" }
serde = "1.0.0"
EOF
    $BB cat > $out/Cargo.lock << 'EOF'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "compat-demo"
version = "0.1.0"
dependencies = ["compat-macro", "local-lib", "serde"]

[[package]]
name = "compat-macro"
version = "0.1.0"

[[package]]
name = "local-lib"
version = "0.1.0"

[[package]]
name = "serde"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
EOF
    $BB cat > $out/build.rs << 'EOF'
fn main() { println!("cargo:rustc-env=COMPAT_BUILD_SCRIPT=ok"); }
EOF
    $BB cat > $out/src/main.rs << 'EOF'
use compat_macro::compat_marker;
#[compat_marker]
fn main() { println!("representative-rail-ok"); }
EOF
    $BB cat > $out/local-lib/Cargo.toml << 'EOF'
[package]
name = "local-lib"
version = "0.1.0"
edition = "2021"
EOF
    $BB cat > $out/local-lib/src/lib.rs << 'EOF'
pub fn message() -> &'static str { "local" }
EOF
    $BB cat > $out/compat-macro/Cargo.toml << 'EOF'
[package]
name = "compat-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
EOF
    $BB cat > $out/compat-macro/src/lib.rs << 'EOF'
extern crate proc_macro;
use proc_macro::TokenStream;
#[proc_macro_attribute]
pub fn compat_marker(_attr: TokenStream, item: TokenStream) -> TokenStream { item }
EOF
    $BB cat > $out/vendor/serde/Cargo.toml << 'EOF'
[package]
name = "serde"
version = "1.0.0"
edition = "2021"
EOF
    $BB cat > $out/vendor/serde/src/lib.rs << 'EOF'
pub fn marker() {}
EOF
    $BB cat > $out/.cargo/config.toml << 'EOF'
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

[net]
offline = true
EOF
  "%],
  addressing_mode = 'input-addressed,
} | mantle.Derivation in
let fakeRust = {
  name = "rust",
  builder = "/bin/sh",
  args = ["-c", m%"
    BB=/bin/busybox
    $BB mkdir -p $out/bin
    $BB cat > $out/bin/cargo << 'EOF'
#!/bin/sh
set -eu
test -f Cargo.lock
test -f build.rs
test -f local-lib/src/lib.rs
test -f compat-macro/src/lib.rs
test -f vendor/serde/Cargo.toml
grep 'cargo:rustc-env=COMPAT_BUILD_SCRIPT=ok' build.rs >/dev/null
if [ "${CARGO_HOME:-}" != "/tmp/cargo-home" ]; then exit 1; fi
if [ "${CARGO_TARGET_DIR:-}" != "/tmp/cargo-target" ]; then exit 1; fi
mkdir -p "$CARGO_TARGET_DIR/x86_64-unknown-linux-musl/release"
cat > "$CARGO_TARGET_DIR/x86_64-unknown-linux-musl/release/compat-demo" << 'BIN'
#!/bin/sh
echo representative-rail-ok
BIN
chmod +x "$CARGO_TARGET_DIR/x86_64-unknown-linux-musl/release/compat-demo"
EOF
    $BB chmod +x $out/bin/cargo
    $BB cat > $out/bin/rustc << 'EOF'
#!/bin/sh
echo fake rustc
EOF
    $BB chmod +x $out/bin/rustc
  "%],
  addressing_mode = 'input-addressed,
} | mantle.Derivation in
let fakeSeed = {
  name = "musl-seed-toolchain",
  builder = "/bin/sh",
  args = ["-c", "BB=/bin/busybox; $BB mkdir -p $out/bin $out/x86_64-linux-musl/lib; echo '#!/bin/sh' > $out/bin/x86_64-linux-musl-gcc; echo 'exit 0' >> $out/bin/x86_64-linux-musl-gcc; $BB chmod +x $out/bin/x86_64-linux-musl-gcc"],
  addressing_mode = 'input-addressed,
} | mantle.Derivation in
let fakeMusl = {
  name = "musl",
  builder = "/bin/sh",
  args = ["-c", "BB=/bin/busybox; $BB mkdir -p $out/lib; : > $out/lib/libc.so"],
  addressing_mode = 'input-addressed,
} | mantle.Derivation in
{
  packages."compat-demo" = mantle.offlineCargoPackage {
    name = "compat-demo",
    src = fakeSource,
    source_name = "compat-demo-src",
    rust = fakeRust,
    rust_name = "rust",
    seed_toolchain = fakeSeed,
    seed_toolchain_name = "musl-seed-toolchain",
    musl = fakeMusl,
    musl_name = "musl",
    binary = "compat-demo",
    target = "x86_64-unknown-linux-musl",
  },
  default.package = "compat-demo",
} | mantle.Project
"#
}

#[test]
fn representative_fixture_contains_required_practical_rust_surfaces() {
    let fixture = tempfile::tempdir().unwrap();
    write_representative_workspace(fixture.path());

    assert!(fixture.path().join("src/main.rs").is_file());
    assert!(fixture.path().join("local-lib/src/lib.rs").is_file());
    assert!(fixture.path().join("compat-macro/src/lib.rs").is_file());
    assert!(fixture.path().join("build.rs").is_file());
    assert!(fixture.path().join("vendor/serde/Cargo.toml").is_file());
    assert!(fixture.path().join("Cargo.lock").is_file());
    assert!(
        std::fs::read_to_string(fixture.path().join(".cargo/config.toml"))
            .unwrap()
            .contains("offline = true")
    );
}

#[test]
fn representative_negative_fixtures_report_stable_blockers() {
    let fixture = tempfile::tempdir().unwrap();
    write_representative_workspace(fixture.path());
    let expected_lock_digest =
        blake3::hash(&std::fs::read(fixture.path().join("Cargo.lock")).unwrap()).to_hex().to_string();

    std::fs::remove_file(fixture.path().join("vendor/serde/Cargo.toml")).unwrap();
    std::fs::write(fixture.path().join("Cargo.lock"), "stale lock\n").unwrap();
    std::fs::write(fixture.path().join("build.rs"), "fn main() {}\n").unwrap();
    std::fs::remove_file(fixture.path().join("compat-macro/src/lib.rs")).unwrap();
    std::fs::write(
        fixture.path().join("Cargo.toml"),
        representative_manifest().replace("build = \"build.rs\"", "build = \"build.rs\"\nlinks = \"native\""),
    )
    .unwrap();

    let blockers = rail_blockers(fixture.path(), &expected_lock_digest);

    assert!(blockers.contains(BLOCKER_MISSING_VENDOR), "blockers: {blockers:?}");
    assert!(blockers.contains(BLOCKER_STALE_LOCK), "blockers: {blockers:?}");
    assert!(blockers.contains(BLOCKER_BUILD_METADATA), "blockers: {blockers:?}");
    assert!(blockers.contains(BLOCKER_PROC_MACRO), "blockers: {blockers:?}");
    assert!(blockers.contains(BLOCKER_NATIVE_LINK), "blockers: {blockers:?}");
}

#[test]
fn representative_offline_cargo_rail_runs_sandbox_smoke_without_network_inputs() {
    if !can_build() {
        eprintln!("{BWRAP_SKIP}");
        return;
    }
    let project = tempfile::tempdir().unwrap();
    let store = tempfile::tempdir().unwrap();
    let state = tempfile::tempdir().unwrap();
    std::fs::write(project.path().join("mantle-project.ncl"), fake_cargo_project_ncl()).unwrap();

    let output = mantle_cmd()
        .current_dir(project.path())
        .arg("--store")
        .arg(store.path())
        .arg("--state-dir")
        .arg(state.path())
        .arg("run")
        .arg(".#compat-demo")
        .arg("--no-substitute")
        .output()
        .expect("mantle run should execute");
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);

    assert!(output.status.success(), "stdout:\n{stdout}\nstderr:\n{stderr}");
    assert_eq!(stdout.trim(), EXPECTED_STDOUT);
    assert!(stderr.contains("running:"), "stderr should identify the selected binary: {stderr}");
}

#[test]
fn representative_rust_plan_receipt_is_bounded_success_or_blocker_without_cargo_fallback() {
    let fixture = tempfile::tempdir().unwrap();
    let shim_dir = tempfile::tempdir().unwrap();
    write_representative_workspace(fixture.path());
    let shim = shim_dir.path().join("cargo");
    std::fs::write(&shim, FAILING_CARGO_SHIM).unwrap();
    make_executable(&shim);

    let output = mantle_cmd()
        .arg("--json")
        .arg("rust-plan")
        .arg("--root")
        .arg(fixture.path())
        .arg("--cargo")
        .arg(&shim)
        .arg("--no-cargo-oracle")
        .output()
        .expect("mantle rust-plan should execute");
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);

    assert!(output.status.success(), "stdout:\n{stdout}\nstderr:\n{stderr}");
    assert!(!stderr.contains("cargo must not be invoked"), "rust-plan fell back to Cargo: {stderr}");
    let receipt: Value = serde_json::from_str(&stdout).expect("rust-plan JSON receipt");
    let class = receipt.pointer("/cargo_mode/compatibility_class").and_then(Value::as_str).unwrap_or_default();
    assert!(
        class == "cargo-free-bounded-topology" || class == "blocked-unsupported-surface",
        "unexpected compatibility class `{class}` in {stdout}"
    );
}

#[test]
fn representative_docs_and_gallery_do_not_overclaim_compatibility() {
    let readme = std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("README.md")).unwrap();
    let operator_docs =
        std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("docs/operator-workflows.md")).unwrap();
    let examples_readme =
        std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("examples/README.md")).unwrap();

    for docs in [&readme, &operator_docs, &examples_readme] {
        assert!(docs.contains("representative Rust compatibility rail"));
        assert!(docs.contains("not proof") || docs.contains("not full"));
        assert!(docs.contains("full Cargo compatibility"));
        assert!(docs.contains("cargo-inside-mantle-sandbox") || docs.contains("sandboxed offline Cargo"));
    }
}

#[cfg(unix)]
fn make_executable(path: &Path) {
    use std::os::unix::fs::PermissionsExt;
    let mut permissions = std::fs::metadata(path).unwrap().permissions();
    permissions.set_mode(EXECUTABLE_MODE);
    std::fs::set_permissions(path, permissions).unwrap();
}

#[cfg(not(unix))]
fn make_executable(_path: &Path) {}
