use assert_cmd::Command;
use serde_json::Value;
use tempfile::TempDir;

fn mantle_cmd() -> Command {
    Command::cargo_bin("mantle").expect("mantle binary should be built")
}

#[test]
fn rust_plan_cli_executes_supported_unit_from_explicit_receipt_material() {
    let dir = TempDir::new().unwrap();
    let crate_dir = dir.path().join("cli-exec");
    let src_dir = crate_dir.join("src");
    std::fs::create_dir_all(&src_dir).unwrap();
    std::fs::write(
        crate_dir.join("Cargo.toml"),
        "[package]\nname = \"cli-exec\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(
        crate_dir.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"cli-exec\"\nversion = \"0.1.0\"\n",
    )
    .unwrap();
    std::fs::write(src_dir.join("lib.rs"), "pub fn answer() -> u32 { 42 }\n").unwrap();

    let output_root = dir.path().join("unit-output");
    let output = mantle_cmd()
        .arg("--json")
        .arg("rust-plan")
        .arg("--root")
        .arg(&crate_dir)
        .arg("--execute-first-supported-unit")
        .arg("--execution-output-root")
        .arg(&output_root)
        .output()
        .expect("rust-plan execution CLI should run");

    assert!(
        output.status.success(),
        "rust-plan execution CLI failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let receipt: Value = serde_json::from_slice(&output.stdout).expect("CLI should emit JSON receipt");
    let execution = &receipt["unit_execution"];
    assert_eq!(execution["execution_status"], "success");
    assert_eq!(execution["rebuild_reason"], "rebuilt-explicit-unit");
    assert_eq!(execution["target_kind"], "lib");
    assert_eq!(execution["toolchain"]["tool"], "rustc");
    assert!(execution["blocker"].is_null());
    assert!(execution["output_artifact_digests"].as_array().unwrap().iter().any(|artifact| {
        artifact["path"].as_str().unwrap().starts_with("declared-output/")
            && artifact["path"].as_str().unwrap().ends_with(".rlib")
            && artifact["blake3"].as_str().unwrap().len() == 64
    }));
    assert!(receipt["rust_plan"]["unit_derivation_graph"]["ready"].as_bool().unwrap());
    assert_eq!(receipt["rust_plan"]["unit_derivation_graph"]["derivation_count"], 1);
}

#[test]
fn rust_plan_cli_executes_dependency_chain_from_explicit_receipt_material() {
    let dir = TempDir::new().unwrap();
    let dep_dir = dir.path().join("dep-crate");
    let app_dir = dir.path().join("app-crate");
    std::fs::create_dir_all(dep_dir.join("src")).unwrap();
    std::fs::create_dir_all(app_dir.join("src")).unwrap();
    std::fs::write(
        dep_dir.join("Cargo.toml"),
        "[package]\nname = \"dep-crate\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(dep_dir.join("src/lib.rs"), "pub fn answer() -> u32 { 42 }\n").unwrap();
    std::fs::write(
        app_dir.join("Cargo.toml"),
        "[package]\nname = \"app-crate\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\ndep_crate = { package = \"dep-crate\", path = \"../dep-crate\" }\n",
    )
    .unwrap();
    std::fs::write(app_dir.join("src/lib.rs"), "pub fn call_dep() -> u32 { dep_crate::answer() }\n").unwrap();
    let lock_output = std::process::Command::new("cargo")
        .arg("generate-lockfile")
        .current_dir(&app_dir)
        .output()
        .expect("cargo generate-lockfile should run");
    assert!(
        lock_output.status.success(),
        "cargo generate-lockfile failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&lock_output.stdout),
        String::from_utf8_lossy(&lock_output.stderr)
    );

    let output_root = dir.path().join("chain-output");
    let output = mantle_cmd()
        .arg("--json")
        .arg("rust-plan")
        .arg("--root")
        .arg(&app_dir)
        .arg("--execute-first-dependency-chain")
        .arg("--execution-output-root")
        .arg(&output_root)
        .output()
        .expect("rust-plan dependency-chain CLI should run");

    assert!(
        output.status.success(),
        "rust-plan dependency-chain CLI failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let receipt: Value = serde_json::from_slice(&output.stdout).expect("CLI should emit JSON receipt");
    assert!(receipt["rust_plan"]["unit_derivation_graph"]["ready"].as_bool().unwrap());
    let chain = &receipt["dependency_chain_execution"];
    assert_eq!(chain["execution_status"], "success", "{receipt:#?}");
    assert!(chain["claim"].as_str().unwrap().contains("bounded explicit Rust dependency edge"));
    assert!(chain["blocker"].is_null());
    let unit_executions = chain["unit_executions"].as_array().unwrap();
    assert_eq!(unit_executions.len(), 2);
    assert_eq!(unit_executions[0]["target_kind"], "lib");
    assert_eq!(unit_executions[1]["target_kind"], "lib");
    assert_eq!(unit_executions[0]["execution_status"], "success");
    assert_eq!(unit_executions[1]["execution_status"], "success");
    assert!(
        unit_executions[1]["dependency_artifact_digests"]
            .as_array()
            .unwrap()
            .iter()
            .any(|artifact| artifact["blake3"].as_str().unwrap().len() == 64)
    );
    assert!(unit_executions.iter().all(|execution| {
        execution["output_artifact_digests"].as_array().unwrap().iter().any(|artifact| {
            artifact["path"].as_str().unwrap().starts_with("declared-output/")
                && artifact["blake3"].as_str().unwrap().len() == 64
        })
    }));
}

#[test]
fn rust_plan_cli_executes_target_unit_topology_from_explicit_receipt_material() {
    let dir = TempDir::new().unwrap();
    let dep_a_dir = dir.path().join("dep-a");
    let dep_b_dir = dir.path().join("dep-b");
    let app_dir = dir.path().join("app-crate");
    for crate_dir in [&dep_a_dir, &dep_b_dir, &app_dir] {
        std::fs::create_dir_all(crate_dir.join("src")).unwrap();
    }
    std::fs::write(
        dep_a_dir.join("Cargo.toml"),
        "[package]\nname = \"dep-a\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(dep_a_dir.join("src/lib.rs"), "pub fn a() -> u32 { 40 }\n").unwrap();
    std::fs::write(
        dep_b_dir.join("Cargo.toml"),
        "[package]\nname = \"dep-b\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\ndep_a = { package = \"dep-a\", path = \"../dep-a\" }\n",
    )
    .unwrap();
    std::fs::write(dep_b_dir.join("src/lib.rs"), "pub fn b() -> u32 { dep_a::a() + 1 }\n").unwrap();
    std::fs::write(
        app_dir.join("Cargo.toml"),
        "[package]\nname = \"app-crate\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\ndep_b = { package = \"dep-b\", path = \"../dep-b\" }\n",
    )
    .unwrap();
    std::fs::write(app_dir.join("src/lib.rs"), "pub fn call_dep() -> u32 { dep_b::b() + 1 }\n").unwrap();
    let lock_output = std::process::Command::new("cargo")
        .arg("generate-lockfile")
        .current_dir(&app_dir)
        .output()
        .expect("cargo generate-lockfile should run");
    assert!(
        lock_output.status.success(),
        "cargo generate-lockfile failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&lock_output.stdout),
        String::from_utf8_lossy(&lock_output.stderr)
    );

    let output_root = dir.path().join("topology-output");
    let output = mantle_cmd()
        .arg("--json")
        .arg("rust-plan")
        .arg("--root")
        .arg(&app_dir)
        .arg("--execute-target-topology")
        .arg("--execution-output-root")
        .arg(&output_root)
        .output()
        .expect("rust-plan target-topology CLI should run");

    assert!(
        output.status.success(),
        "rust-plan target-topology CLI failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let receipt: Value = serde_json::from_slice(&output.stdout).expect("CLI should emit JSON receipt");
    assert!(receipt["rust_plan"]["unit_derivation_graph"]["ready"].as_bool().unwrap());
    let topology = &receipt["target_topology_execution"];
    assert_eq!(topology["execution_status"], "success", "{receipt:#?}");
    assert!(topology["claim"].as_str().unwrap().contains("bounded target-only Rust unit topology"));
    assert!(topology["blocker"].is_null());
    assert_eq!(topology["receipt_hash"].as_str().unwrap().len(), 64);
    let unit_executions = topology["unit_executions"].as_array().unwrap();
    assert_eq!(unit_executions.len(), 3);
    assert!(unit_executions.iter().all(|execution| execution["execution_status"] == "success"));
    assert!(
        unit_executions[1]["dependency_artifact_digests"].as_array().unwrap()[0]["blake3"]
            .as_str()
            .unwrap()
            .len()
            == 64
    );
    assert!(
        unit_executions[2]["dependency_artifact_digests"].as_array().unwrap()[0]["blake3"]
            .as_str()
            .unwrap()
            .len()
            == 64
    );
}

#[test]
fn rust_plan_cli_blocks_target_topology_with_proc_macro_host_artifact() {
    let dir = TempDir::new().unwrap();
    let macro_dir = dir.path().join("demo-macro");
    let app_dir = dir.path().join("app-crate");
    std::fs::create_dir_all(macro_dir.join("src")).unwrap();
    std::fs::create_dir_all(app_dir.join("src")).unwrap();
    std::fs::write(
        macro_dir.join("Cargo.toml"),
        "[package]\nname = \"demo-macro\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[lib]\nproc-macro = true\n",
    )
    .unwrap();
    std::fs::write(
        macro_dir.join("src/lib.rs"),
        "extern crate proc_macro;\nuse proc_macro::TokenStream;\n#[proc_macro_attribute]\npub fn demo(_attr: TokenStream, item: TokenStream) -> TokenStream { item }\n",
    )
    .unwrap();
    std::fs::write(
        app_dir.join("Cargo.toml"),
        "[package]\nname = \"app-crate\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\ndemo_macro = { package = \"demo-macro\", path = \"../demo-macro\" }\n",
    )
    .unwrap();
    std::fs::write(app_dir.join("src/lib.rs"), "use demo_macro::demo;\n#[demo]\npub fn value() -> u32 { 1 }\n")
        .unwrap();
    let lock_output = std::process::Command::new("cargo")
        .arg("generate-lockfile")
        .current_dir(&app_dir)
        .output()
        .expect("cargo generate-lockfile should run");
    assert!(lock_output.status.success(), "{}", String::from_utf8_lossy(&lock_output.stderr));

    let output = mantle_cmd()
        .arg("--json")
        .arg("rust-plan")
        .arg("--root")
        .arg(&app_dir)
        .arg("--execute-target-topology")
        .arg("--execution-output-root")
        .arg(dir.path().join("blocked-output"))
        .output()
        .expect("rust-plan target-topology CLI should run");

    assert!(output.status.success(), "{}", String::from_utf8_lossy(&output.stderr));
    let receipt: Value = serde_json::from_slice(&output.stdout).expect("CLI should emit JSON receipt");
    let topology = &receipt["target_topology_execution"];
    assert_eq!(topology["execution_status"], "blocked", "{receipt:#?}");
    assert_eq!(topology["blocker"]["class"], "unsupported-topology-shape");
    assert_eq!(topology["unit_executions"].as_array().unwrap().len(), 0);
}

#[test]
fn rust_plan_cli_executes_proc_macro_host_artifact_topology() {
    let dir = TempDir::new().unwrap();
    let macro_dir = dir.path().join("demo-macro");
    let app_dir = dir.path().join("app-crate");
    std::fs::create_dir_all(macro_dir.join("src")).unwrap();
    std::fs::create_dir_all(app_dir.join("src")).unwrap();
    std::fs::write(
        macro_dir.join("Cargo.toml"),
        "[package]\nname = \"demo-macro\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[lib]\nproc-macro = true\n",
    )
    .unwrap();
    std::fs::write(
        macro_dir.join("src/lib.rs"),
        "extern crate proc_macro;\nuse proc_macro::TokenStream;\n#[proc_macro_attribute]\npub fn demo(_attr: TokenStream, item: TokenStream) -> TokenStream { item }\n",
    )
    .unwrap();
    std::fs::write(
        app_dir.join("Cargo.toml"),
        "[package]\nname = \"app-crate\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\ndemo_macro = { package = \"demo-macro\", path = \"../demo-macro\" }\n",
    )
    .unwrap();
    std::fs::write(app_dir.join("src/lib.rs"), "use demo_macro::demo;\n#[demo]\npub fn value() -> u32 { 1 }\n")
        .unwrap();
    let lock_output = std::process::Command::new("cargo")
        .arg("generate-lockfile")
        .current_dir(&app_dir)
        .output()
        .expect("cargo generate-lockfile should run");
    assert!(lock_output.status.success(), "{}", String::from_utf8_lossy(&lock_output.stderr));

    let output = mantle_cmd()
        .arg("--json")
        .arg("rust-plan")
        .arg("--root")
        .arg(&app_dir)
        .arg("--execute-host-artifact-topology")
        .arg("--execution-output-root")
        .arg(dir.path().join("host-output"))
        .output()
        .expect("rust-plan host-artifact topology CLI should run");

    assert!(
        output.status.success(),
        "rust-plan host-artifact CLI failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let receipt: Value = serde_json::from_slice(&output.stdout).expect("CLI should emit JSON receipt");
    assert!(receipt["rust_plan"]["unit_derivation_graph"]["ready"].as_bool().unwrap());
    let topology = &receipt["host_artifact_topology_execution"];
    assert_eq!(topology["execution_status"], "success", "{receipt:#?}");
    assert!(topology["claim"].as_str().unwrap().contains("bounded Rust host-artifact topology"));
    assert!(topology["blocker"].is_null());
    assert_eq!(topology["receipt_hash"].as_str().unwrap().len(), 64);
    let unit_executions = topology["unit_executions"].as_array().unwrap();
    assert_eq!(unit_executions.len(), 2);
    assert_eq!(unit_executions[0]["target_kind"], "proc-macro");
    assert_eq!(unit_executions[1]["target_kind"], "lib");
    assert!(unit_executions.iter().all(|execution| execution["execution_status"] == "success"));
    assert!(unit_executions[1]["host_artifact_digests"].as_array().unwrap().iter().any(|artifact| {
        artifact["path"].as_str().unwrap().contains("demo_macro") && artifact["blake3"].as_str().unwrap().len() == 64
    }));
}

#[test]
fn rust_plan_cli_executes_build_script_metadata_topology() {
    let dir = TempDir::new().unwrap();
    let crate_dir = dir.path().join("build-meta-crate");
    std::fs::create_dir_all(crate_dir.join("src")).unwrap();
    std::fs::write(
        crate_dir.join("Cargo.toml"),
        "[package]\nname = \"build-meta-crate\"\nversion = \"0.1.0\"\nedition = \"2021\"\nbuild = \"build.rs\"\n",
    )
    .unwrap();
    std::fs::write(
        crate_dir.join("build.rs"),
        "fn main() {\n    let out = std::env::var(\"OUT_DIR\").unwrap();\n    std::fs::write(format!(\"{out}/generated.txt\"), \"generated-ok\").unwrap();\n    println!(\"cargo:rustc-cfg=mantle_build_script\");\n    println!(\"cargo:rustc-env=BUILD_VALUE=env-ok\");\n    println!(\"cargo:rerun-if-changed=build.rs\");\n}\n",
    )
    .unwrap();
    std::fs::write(
        crate_dir.join("src/lib.rs"),
        "#[cfg(not(mantle_build_script))]\ncompile_error!(\"missing build script cfg\");\npub const BUILD_VALUE: &str = env!(\"BUILD_VALUE\");\npub const GENERATED: &str = include_str!(concat!(env!(\"OUT_DIR\"), \"/generated.txt\"));\n",
    )
    .unwrap();
    let lock_output = std::process::Command::new("cargo")
        .arg("generate-lockfile")
        .current_dir(&crate_dir)
        .output()
        .expect("cargo generate-lockfile should run");
    assert!(lock_output.status.success(), "{}", String::from_utf8_lossy(&lock_output.stderr));

    let output = mantle_cmd()
        .arg("--json")
        .arg("rust-plan")
        .arg("--root")
        .arg(&crate_dir)
        .arg("--execute-host-artifact-topology")
        .arg("--execution-output-root")
        .arg(dir.path().join("build-meta-output"))
        .output()
        .expect("rust-plan host-artifact topology CLI should run");

    assert!(
        output.status.success(),
        "rust-plan build-script metadata CLI failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let receipt: Value = serde_json::from_slice(&output.stdout).expect("CLI should emit JSON receipt");
    let topology = &receipt["host_artifact_topology_execution"];
    assert_eq!(topology["execution_status"], "success", "{receipt:#?}");
    let metadata_runs = topology["build_script_metadata_runs"].as_array().unwrap();
    assert_eq!(metadata_runs.len(), 1, "{receipt:#?}");
    assert_eq!(metadata_runs[0]["rustc_cfg"].as_array().unwrap()[0], "mantle_build_script");
    assert_eq!(metadata_runs[0]["rustc_env"]["BUILD_VALUE"], "env-ok");
    assert_eq!(metadata_runs[0]["rerun_if_changed"].as_array().unwrap()[0], "build.rs");
    assert!(metadata_runs[0]["out_dir_artifact_digests"].as_array().unwrap().iter().any(|artifact| {
        artifact["path"] == "out-dir/generated.txt" && artifact["blake3"].as_str().unwrap().len() == 64
    }));
    let unit_executions = topology["unit_executions"].as_array().unwrap();
    assert_eq!(unit_executions.len(), 2);
    assert_eq!(unit_executions[0]["target_kind"], "custom-build");
    assert_eq!(unit_executions[1]["target_kind"], "lib");
    assert!(unit_executions.iter().all(|execution| execution["execution_status"] == "success"));
}

#[test]
fn rust_plan_cli_binds_build_script_native_link_metadata() {
    let dir = TempDir::new().unwrap();
    let crate_dir = dir.path().join("build-link-crate");
    std::fs::create_dir_all(crate_dir.join("src")).unwrap();
    std::fs::write(
        crate_dir.join("Cargo.toml"),
        "[package]\nname = \"build-link-crate\"\nversion = \"0.1.0\"\nedition = \"2021\"\nbuild = \"build.rs\"\n",
    )
    .unwrap();
    std::fs::write(
        crate_dir.join("build.rs"),
        "fn main() {\n    println!(\"cargo:rustc-link-search=native=/tmp\");\n    println!(\"cargo:rustc-link-lib=m\");\n}\n",
    )
    .unwrap();
    std::fs::write(
        crate_dir.join("src/main.rs"),
        "unsafe extern \"C\" { fn cos(input: f64) -> f64; }\nfn main() { let _ = unsafe { cos(0.0) }; }\n",
    )
    .unwrap();
    let lock_output = std::process::Command::new("cargo")
        .arg("generate-lockfile")
        .current_dir(&crate_dir)
        .output()
        .expect("cargo generate-lockfile should run");
    assert!(lock_output.status.success(), "{}", String::from_utf8_lossy(&lock_output.stderr));

    let output = mantle_cmd()
        .arg("--json")
        .arg("rust-plan")
        .arg("--root")
        .arg(&crate_dir)
        .arg("--execute-host-artifact-topology")
        .arg("--execution-output-root")
        .arg(dir.path().join("build-link-output"))
        .output()
        .expect("rust-plan host-artifact topology CLI should run");

    assert!(
        output.status.success(),
        "rust-plan build-script link metadata CLI failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let receipt: Value = serde_json::from_slice(&output.stdout).expect("CLI should emit JSON receipt");
    let topology = &receipt["host_artifact_topology_execution"];
    assert_eq!(topology["execution_status"], "success", "{receipt:#?}");
    let metadata_runs = topology["build_script_metadata_runs"].as_array().unwrap();
    assert_eq!(metadata_runs.len(), 1, "{receipt:#?}");
    assert_eq!(metadata_runs[0]["rustc_link_lib"].as_array().unwrap()[0], "m");
    assert_eq!(metadata_runs[0]["rustc_link_search"].as_array().unwrap()[0], "native=/tmp");
    let unit_executions = topology["unit_executions"].as_array().unwrap();
    assert_eq!(unit_executions.len(), 2);
    assert_eq!(unit_executions[0]["target_kind"], "custom-build");
    assert_eq!(unit_executions[1]["target_kind"], "bin");
    assert!(unit_executions.iter().all(|execution| execution["execution_status"] == "success"));
}

#[test]
fn rust_plan_cli_blocks_unsupported_build_script_link_metadata() {
    let dir = TempDir::new().unwrap();
    let crate_dir = dir.path().join("bad-build-link-crate");
    std::fs::create_dir_all(crate_dir.join("src")).unwrap();
    std::fs::write(
        crate_dir.join("Cargo.toml"),
        "[package]\nname = \"bad-build-link-crate\"\nversion = \"0.1.0\"\nedition = \"2021\"\nbuild = \"build.rs\"\n",
    )
    .unwrap();
    std::fs::write(
        crate_dir.join("build.rs"),
        "fn main() { println!(\"cargo:rustc-link-lib=static:+whole-archive=m\"); }\n",
    )
    .unwrap();
    std::fs::write(crate_dir.join("src/lib.rs"), "pub fn value() -> u32 { 1 }\n").unwrap();
    let lock_output = std::process::Command::new("cargo")
        .arg("generate-lockfile")
        .current_dir(&crate_dir)
        .output()
        .expect("cargo generate-lockfile should run");
    assert!(lock_output.status.success(), "{}", String::from_utf8_lossy(&lock_output.stderr));

    let output = mantle_cmd()
        .arg("--json")
        .arg("rust-plan")
        .arg("--root")
        .arg(&crate_dir)
        .arg("--execute-host-artifact-topology")
        .arg("--execution-output-root")
        .arg(dir.path().join("bad-build-link-output"))
        .output()
        .expect("rust-plan host-artifact topology CLI should run");

    assert!(output.status.success(), "{}", String::from_utf8_lossy(&output.stderr));
    let receipt: Value = serde_json::from_slice(&output.stdout).expect("CLI should emit JSON receipt");
    let topology = &receipt["host_artifact_topology_execution"];
    assert_eq!(topology["execution_status"], "blocked", "{receipt:#?}");
    assert_eq!(topology["blocker"]["class"], "malformed-build-script-metadata");
    assert_eq!(topology["unit_executions"].as_array().unwrap().len(), 1);
    assert_eq!(topology["unit_executions"].as_array().unwrap()[0]["target_kind"], "custom-build");
}

#[test]
fn rust_plan_cli_blocks_malformed_build_script_metadata() {
    let dir = TempDir::new().unwrap();
    let crate_dir = dir.path().join("bad-build-meta-crate");
    std::fs::create_dir_all(crate_dir.join("src")).unwrap();
    std::fs::write(
        crate_dir.join("Cargo.toml"),
        "[package]\nname = \"bad-build-meta-crate\"\nversion = \"0.1.0\"\nedition = \"2021\"\nbuild = \"build.rs\"\n",
    )
    .unwrap();
    std::fs::write(crate_dir.join("build.rs"), "fn main() { println!(\"cargo:rustc-env=BROKEN\"); }\n").unwrap();
    std::fs::write(crate_dir.join("src/lib.rs"), "pub fn value() -> u32 { 1 }\n").unwrap();
    let lock_output = std::process::Command::new("cargo")
        .arg("generate-lockfile")
        .current_dir(&crate_dir)
        .output()
        .expect("cargo generate-lockfile should run");
    assert!(lock_output.status.success(), "{}", String::from_utf8_lossy(&lock_output.stderr));

    let output = mantle_cmd()
        .arg("--json")
        .arg("rust-plan")
        .arg("--root")
        .arg(&crate_dir)
        .arg("--execute-host-artifact-topology")
        .arg("--execution-output-root")
        .arg(dir.path().join("bad-build-meta-output"))
        .output()
        .expect("rust-plan host-artifact topology CLI should run");

    assert!(output.status.success(), "{}", String::from_utf8_lossy(&output.stderr));
    let receipt: Value = serde_json::from_slice(&output.stdout).expect("CLI should emit JSON receipt");
    let topology = &receipt["host_artifact_topology_execution"];
    assert_eq!(topology["execution_status"], "blocked", "{receipt:#?}");
    assert_eq!(topology["blocker"]["class"], "malformed-build-script-metadata");
    assert_eq!(topology["unit_executions"].as_array().unwrap().len(), 1);
    assert_eq!(topology["unit_executions"].as_array().unwrap()[0]["target_kind"], "custom-build");
}

#[test]
fn rust_plan_cli_blocks_host_artifact_topology_without_host_units() {
    let dir = TempDir::new().unwrap();
    let crate_dir = dir.path().join("plain-crate");
    std::fs::create_dir_all(crate_dir.join("src")).unwrap();
    std::fs::write(
        crate_dir.join("Cargo.toml"),
        "[package]\nname = \"plain-crate\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(crate_dir.join("Cargo.lock"), "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"plain-crate\"\nversion = \"0.1.0\"\n").unwrap();
    std::fs::write(crate_dir.join("src/lib.rs"), "pub fn value() -> u32 { 1 }\n").unwrap();

    let output = mantle_cmd()
        .arg("--json")
        .arg("rust-plan")
        .arg("--root")
        .arg(&crate_dir)
        .arg("--execute-host-artifact-topology")
        .arg("--execution-output-root")
        .arg(dir.path().join("no-host-output"))
        .output()
        .expect("rust-plan host-artifact topology CLI should run");

    assert!(output.status.success(), "{}", String::from_utf8_lossy(&output.stderr));
    let receipt: Value = serde_json::from_slice(&output.stdout).expect("CLI should emit JSON receipt");
    let topology = &receipt["host_artifact_topology_execution"];
    assert_eq!(topology["execution_status"], "blocked", "{receipt:#?}");
    assert_eq!(topology["blocker"]["class"], "missing-host-artifact-unit");
    assert_eq!(topology["unit_executions"].as_array().unwrap().len(), 0);
}
