use assert_cmd::Command;
use serde_json::Value;
use tempfile::TempDir;

fn mantle_cmd() -> Command {
    Command::cargo_bin("mantle").expect("mantle binary should be built")
}

#[test]
fn rust_plan_cli_executes_supported_unit_from_explicit_receipt_material() {
    let dir = TempDir::new().unwrap();
    let crate_dir = dir.path().join("cli-exec");
    let src_dir = crate_dir.join("src");
    std::fs::create_dir_all(&src_dir).unwrap();
    std::fs::write(
        crate_dir.join("Cargo.toml"),
        "[package]\nname = \"cli-exec\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(
        crate_dir.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"cli-exec\"\nversion = \"0.1.0\"\n",
    )
    .unwrap();
    std::fs::write(src_dir.join("lib.rs"), "pub fn answer() -> u32 { 42 }\n").unwrap();

    let output_root = dir.path().join("unit-output");
    let output = mantle_cmd()
        .arg("--json")
        .arg("rust-plan")
        .arg("--root")
        .arg(&crate_dir)
        .arg("--execute-first-supported-unit")
        .arg("--execution-output-root")
        .arg(&output_root)
        .output()
        .expect("rust-plan execution CLI should run");

    assert!(
        output.status.success(),
        "rust-plan execution CLI failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let receipt: Value = serde_json::from_slice(&output.stdout).expect("CLI should emit JSON receipt");
    let execution = &receipt["unit_execution"];
    assert_eq!(execution["execution_status"], "success");
    assert_eq!(execution["rebuild_reason"], "rebuilt-explicit-unit");
    assert_eq!(execution["target_kind"], "lib");
    assert_eq!(execution["toolchain"]["tool"], "rustc");
    assert!(execution["blocker"].is_null());
    assert!(execution["output_artifact_digests"].as_array().unwrap().iter().any(|artifact| {
        artifact["path"].as_str().unwrap().starts_with("declared-output/")
            && artifact["path"].as_str().unwrap().ends_with(".rlib")
            && artifact["blake3"].as_str().unwrap().len() == 64
    }));
    assert!(receipt["rust_plan"]["unit_derivation_graph"]["ready"].as_bool().unwrap());
    assert_eq!(receipt["rust_plan"]["unit_derivation_graph"]["derivation_count"], 1);
}
