//! Generate `.crunch/inputs.ncl` from a resolved lockfile.
//!
//! The generated file is a plain Nickel record where each field is a
//! locked input's metadata (url, hash, rev, mirrors). Package code
//! imports this file and passes the data to fetch helpers.
//!
//! Pure string generation. No I/O, no Nickel eval.

use crate::lock::{LockEntry, LockedKind, Lockfile};

/// Maximum number of inputs to generate (guard against runaway locks).
const MAX_GENERATED_INPUTS: u32 = 4096;

/// Header comment for the generated file.
const HEADER: &str = "# Generated by crunch from crunch.lock. DO NOT EDIT.\n";

/// Generate the `.crunch/inputs.ncl` content from a lockfile.
///
/// Each lock entry becomes a record field with its resolved metadata.
/// The output is valid Nickel that can be imported by package code.
pub fn generate_inputs_ncl(lock: &Lockfile) -> String {
    assert!(
        lock.inputs.len() as u64 <= MAX_GENERATED_INPUTS as u64,
        "too many inputs to generate: {}",
        lock.inputs.len()
    );

    let mut out = String::with_capacity(1024);
    out.push_str(HEADER);
    out.push_str("{\n");

    for (i, (name, entry)) in lock.inputs.iter().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        generate_entry(&mut out, name, entry);
    }

    out.push_str("}\n");
    out
}

/// Generate a single input entry as a Nickel record field.
fn generate_entry(out: &mut String, name: &str, entry: &LockEntry) {
    // Nickel field names with hyphens need quoting.
    let field_name = if needs_quoting(name) {
        format!("\"{name}\"")
    } else {
        name.to_string()
    };

    out.push_str(&format!("  {field_name} = {{\n"));

    match &entry.kind {
        LockedKind::File { url } => {
            out.push_str("    type = \"file\",\n");
            out.push_str(&format!("    url = \"{}\",\n", escape_nickel(url)));
        }
        LockedKind::Tarball { url } => {
            out.push_str("    type = \"tarball\",\n");
            out.push_str(&format!("    url = \"{}\",\n", escape_nickel(url)));
        }
        LockedKind::Git {
            repository,
            rev,
            ref_name,
        } => {
            out.push_str("    type = \"git\",\n");
            out.push_str(&format!(
                "    repository = \"{}\",\n",
                escape_nickel(repository)
            ));
            out.push_str(&format!("    rev = \"{}\",\n", escape_nickel(rev)));
            if let Some(r) = ref_name {
                out.push_str(&format!(
                    "    ref_name = \"{}\",\n",
                    escape_nickel(r)
                ));
            }
        }
    }

    out.push_str(&format!(
        "    hash = \"{}\",\n",
        escape_nickel(&entry.hash.value)
    ));
    out.push_str(&format!("    algo = \"{}\",\n", entry.hash.algo));

    if !entry.mirrors.is_empty() {
        out.push_str("    mirrors = [\n");
        for mirror in &entry.mirrors {
            out.push_str(&format!("      \"{}\",\n", escape_nickel(mirror)));
        }
        out.push_str("    ],\n");
    }

    if !entry.patches.is_empty() {
        out.push_str("    patches = [\n");
        for patch in &entry.patches {
            out.push_str(&format!("      \"{}\",\n", escape_nickel(patch)));
        }
        out.push_str("    ],\n");
    }

    out.push_str("  },\n");
}

/// Whether a Nickel field name needs quoting (contains non-ident chars).
fn needs_quoting(name: &str) -> bool {
    if name.is_empty() {
        return true;
    }
    let first = name.as_bytes()[0];
    let valid_start = first.is_ascii_alphabetic() || first == b'_';
    if !valid_start {
        return true;
    }
    !name
        .bytes()
        .all(|b| b.is_ascii_alphanumeric() || b == b'_')
}

/// Escape a string for inclusion in a Nickel double-quoted string.
fn escape_nickel(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

/// Compute a fingerprint of the generated content for drift detection.
///
/// Uses a simple hash of the content bytes. Two files with the same
/// fingerprint have the same content.
pub fn content_fingerprint(content: &str) -> u64 {
    // FNV-1a for simplicity. Not cryptographic, just for drift detection.
    let mut hash: u64 = 0xcbf29ce484222325;
    for byte in content.as_bytes() {
        hash ^= *byte as u64;
        hash = hash.wrapping_mul(0x100000001b3);
    }
    hash
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lock::*;
    use crate::manifest::HashAlgo;
    use crate::version::SchemaVersion;
    use std::collections::BTreeMap;

    fn lock_with_file(name: &str, url: &str, hash: &str) -> Lockfile {
        let mut inputs = BTreeMap::new();
        inputs.insert(
            name.to_string(),
            LockEntry {
                kind: LockedKind::File {
                    url: url.to_string(),
                },
                hash: LockedHash {
                    algo: HashAlgo::Sha256,
                    value: hash.to_string(),
                },
                patches: vec![],
                mirrors: vec![],
            },
        );
        Lockfile {
            version: SchemaVersion::CURRENT,
            inputs,
            patches: BTreeMap::new(),
        }
    }

    #[test]
    fn generate_empty_lock() {
        let lock = Lockfile::new();
        let ncl = generate_inputs_ncl(&lock);
        assert!(ncl.starts_with("# Generated"));
        assert!(ncl.contains("{\n}\n"));
    }

    #[test]
    fn generate_file_entry() {
        let lock = lock_with_file("data", "https://example.com/data.bin", "sha256-abc=");
        let ncl = generate_inputs_ncl(&lock);
        assert!(ncl.contains("data = {"));
        assert!(ncl.contains("type = \"file\""));
        assert!(ncl.contains("url = \"https://example.com/data.bin\""));
        assert!(ncl.contains("hash = \"sha256-abc=\""));
    }

    #[test]
    fn generate_hyphenated_name_quoted() {
        let lock = lock_with_file("my-input", "https://example.com/f", "sha256-x=");
        let ncl = generate_inputs_ncl(&lock);
        assert!(ncl.contains("\"my-input\" = {"));
    }

    #[test]
    fn generate_git_entry() {
        let mut inputs = BTreeMap::new();
        inputs.insert(
            "nixpkgs".to_string(),
            LockEntry {
                kind: LockedKind::Git {
                    repository: "https://github.com/NixOS/nixpkgs.git".to_string(),
                    rev: "abc123".to_string(),
                    ref_name: Some("nixos-unstable".to_string()),
                },
                hash: LockedHash {
                    algo: HashAlgo::Sha256,
                    value: "sha256-xyz=".to_string(),
                },
                patches: vec![],
                mirrors: vec!["https://mirror.example.com/nixpkgs.git".to_string()],
            },
        );
        let lock = Lockfile {
            version: SchemaVersion::CURRENT,
            inputs,
            patches: BTreeMap::new(),
        };

        let ncl = generate_inputs_ncl(&lock);
        assert!(ncl.contains("type = \"git\""));
        assert!(ncl.contains("repository = \"https://github.com/NixOS/nixpkgs.git\""));
        assert!(ncl.contains("rev = \"abc123\""));
        assert!(ncl.contains("ref_name = \"nixos-unstable\""));
        assert!(ncl.contains("mirrors = ["));
        assert!(ncl.contains("\"https://mirror.example.com/nixpkgs.git\""));
    }

    #[test]
    fn generate_with_patches() {
        let mut lock = lock_with_file("src", "https://example.com/src.tar.gz", "sha256-h=");
        lock.inputs.get_mut("src").unwrap().patches = vec!["p1".into(), "p2".into()];
        let ncl = generate_inputs_ncl(&lock);
        assert!(ncl.contains("patches = ["));
        assert!(ncl.contains("\"p1\""));
        assert!(ncl.contains("\"p2\""));
    }

    #[test]
    fn escape_special_chars() {
        assert_eq!(escape_nickel("a\"b"), "a\\\"b");
        assert_eq!(escape_nickel("a\\b"), "a\\\\b");
        assert_eq!(escape_nickel("a\nb"), "a\\nb");
    }

    #[test]
    fn needs_quoting_cases() {
        assert!(!needs_quoting("nixpkgs"));
        assert!(!needs_quoting("hello_world"));
        assert!(needs_quoting("hello-world"));
        assert!(needs_quoting("123abc"));
        assert!(needs_quoting(""));
    }

    #[test]
    fn fingerprint_deterministic() {
        let a = content_fingerprint("hello");
        let b = content_fingerprint("hello");
        assert_eq!(a, b);
    }

    #[test]
    fn fingerprint_differs() {
        let a = content_fingerprint("hello");
        let b = content_fingerprint("world");
        assert_ne!(a, b);
    }
}
