//! crunch-project: Project manifest, lockfile, and input management.
//!
//! Owns the human-edited Nickel manifest (`crunch-project.ncl`),
//! the machine-edited JSON lockfile (`crunch.lock`), refresh logic,
//! stale detection, schema upgrades, and generated input files.
//! Consumers use this crate for project-level operations; fetch
//! execution stays in the build pipeline.

mod attestation;
mod attestation_adapter;
mod drift;
mod error;
mod generate;
mod lock;
mod manifest;
mod merge;
mod mirrors;
mod refresh;
mod refresh_adapter;
mod upgrade;
mod upgrade_adapter;
mod version;

pub use attestation::ProjectAttestationInput;
pub use attestation::synthesize_project_attestation;
pub use crunch_project_core::CommandFreshnessEnv;
pub use crunch_project_core::CommandFreshnessProbe;
pub use crunch_project_core::ExternalExistingFile;
pub use crunch_project_core::ExternalHash;
pub use crunch_project_core::ExternalPatch;
pub use crunch_project_core::ExternalPatchSource;
pub use crunch_project_core::ExternalPin;
pub use crunch_project_core::ExternalPinKind;
pub use crunch_project_core::ExternalPinMetadata;
pub use crunch_project_core::ExternalPinSet;
pub use crunch_project_core::FRESHNESS_PROBE_VERSION;
pub use crunch_project_core::FreshnessDecision;
pub use crunch_project_core::FreshnessDecisionKind;
pub use crunch_project_core::FreshnessError;
pub use crunch_project_core::FreshnessErrorKind;
pub use crunch_project_core::FreshnessObservation;
pub use crunch_project_core::FreshnessObservationRequest;
pub use crunch_project_core::FreshnessObservationStatus;
pub use crunch_project_core::FreshnessProbe;
pub use crunch_project_core::FreshnessProbeKind;
pub use crunch_project_core::FreshnessRefreshPlanRequest;
pub use crunch_project_core::FreshnessTemplateDestination;
pub use crunch_project_core::FreshnessTemplateRequest;
pub use crunch_project_core::InputFetchDiagnostic;
pub use crunch_project_core::InputFetchDiagnosticKind;
pub use crunch_project_core::InputFetchPolicy;
pub use crunch_project_core::InputFetchPolicyItem;
pub use crunch_project_core::InputFetchPolicyReport;
pub use crunch_project_core::InputFetchRequirement;
pub use crunch_project_core::InputSourceStateClass;
pub use crunch_project_core::InputSourceStateFact;
pub use crunch_project_core::LockedFreshnessValue;
pub use crunch_project_core::MAX_FRESHNESS_VALUE_BYTES;
pub use crunch_project_core::PIN_IMPORT_DEFAULT_INPUTS_FILE;
pub use crunch_project_core::PIN_IMPORT_DEFAULT_LOCK_FILE;
pub use crunch_project_core::PIN_IMPORT_DEFAULT_PROJECT_FILE;
pub use crunch_project_core::PIN_IMPORT_PLAN_SCHEMA;
pub use crunch_project_core::PIN_IMPORT_SUPPORTED_IMPORTER;
pub use crunch_project_core::PinImportBlocker;
pub use crunch_project_core::PinImportFileOperation;
pub use crunch_project_core::PinImportMappedInput;
pub use crunch_project_core::PinImportMappedPatch;
pub use crunch_project_core::PinImportOptions;
pub use crunch_project_core::PinImportPlan;
pub use crunch_project_core::PinImportSemantic;
pub use crunch_project_core::ProjectSoundnessClass;
pub use crunch_project_core::ProjectSoundnessFact;
pub use crunch_project_core::ProjectSoundnessInput;
pub use crunch_project_core::ProjectSoundnessIssue;
pub use crunch_project_core::ProjectSoundnessMode;
pub use crunch_project_core::ProjectSoundnessReport;
pub use crunch_project_core::ProjectSoundnessSeverity;
pub use crunch_project_core::ProjectSoundnessSubject;
pub use crunch_project_core::build_pin_import_plan;
pub use crunch_project_core::check_project_soundness;
pub use crunch_project_core::input_source_identity;
pub use crunch_project_core::normalize_freshness_observation;
pub use crunch_project_core::plan_freshness_refresh;
pub use crunch_project_core::project_soundness_parse_error;
pub use crunch_project_core::render_freshness_template;
pub use crunch_project_core::validate_freshness_probe;
pub use drift::DriftStatus;
pub use drift::check_drift;
pub use error::Error;
pub use generate::content_fingerprint;
pub use generate::generate_inputs_ncl;
pub use lock::LockEntry;
pub use lock::LockedHash;
pub use lock::LockedKind;
pub use lock::LockedPatch;
pub use lock::LockedPatchSource;
pub use lock::Lockfile;
pub use manifest::GitReference;
pub use manifest::HashAlgo;
pub use manifest::HashSpec;
pub use manifest::InputKind;
pub use manifest::ManifestInput;
pub use manifest::PatchDef;
pub use manifest::PatchSource;
pub use manifest::ProjectManifest;
pub use merge::FilterInputsResult;
pub use merge::MergeIssue;
pub use merge::MergeReport;
pub use merge::Severity;
pub use merge::check_manifest_lock;
pub use merge::filter_inputs;
pub use merge::inputs_needing_refresh;
pub use merge::orphaned_lock_entries;
pub use mirrors::url_with_mirrors;
pub use mirrors::validate_mirrors;
pub use refresh::ApplyResult;
pub use refresh::HashResolutionMode;
pub use refresh::RefreshFailure;
pub use refresh::RefreshOutcome;
pub use refresh::RefreshResolver;
pub use refresh::ResolvedInput;
pub use refresh::StaleReport;
pub use refresh::apply_outcomes;
pub use refresh::list_stale;
pub use refresh::list_stale_with_options;
pub use refresh::refresh_inputs;
pub use refresh::refresh_inputs_with_options;
pub use upgrade::OLDEST_SUPPORTED;
pub use upgrade::upgrade_lockfile;
pub use version::SchemaVersion;
pub use version::parse_version;
