[package]
name = "crunch-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-compression = { version = "0.4", features = ["tokio", "bzip2", "gzip", "xz", "zstd"] }
async-trait = "0.1"
crunch-attestation = { path = "../crunch-attestation" }
ed25519-dalek = "2.1.1"
nix-compat = { path = "../../vendor/nix-compat", features = ["serde"] }
snix-castore = { path = "../../vendor/snix-castore" }
snix-store = { path = "../../vendor/snix-store" }
blake3 = "=1.8.2"
data-encoding = "2.6"
futures = "0.3"
fs2 = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
reqwest = { version = "0.13.1", default-features = true, features = ["json"] }
tokio = { version = "1", features = ["fs", "rt"] }
tokio-util = { version = "0.7", features = ["io"] }
tracing = "0.1"
url = "2"

[dev-dependencies]
bzip2 = "0.6"
crunch-delta = { path = "../crunch-delta" }
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
futures = "0.3"
pretty_assertions = "1.0"
sha2 = "0.10"
tempfile = "3"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
xz2 = "0.1"
zstd = "0.13"

