[workspace]
resolver = "2"
members = [
  "crates/crunch-spacewasm-core",
  "crates/crunch-spacewasm",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
blake3 = { version = "=1.8.2", default-features = false }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
tempfile = "3.14"
