[package]
name = "crunch-pipeline"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
crunch-build = { path = "../crunch-build" }
crunch-eval = { path = "../crunch-eval" }
crunch-evaluation-stream-core = { path = "../crunch-evaluation-stream-core" }
crunch-glue = { path = "../crunch-glue" }
crunch-store = { path = "../crunch-store" }
nix-compat = { path = "../../vendor/nix-compat" }
snix-build = { path = "../../vendor/snix-build" }
thiserror = "2.0"
tokio = { version = "1", features = ["rt", "sync"] }
tracing = "0.1"

[dev-dependencies]
data-encoding = "2.6"
sha2 = "0.10.8"
snix-castore = { path = "../../vendor/snix-castore" }
snix-store = { path = "../../vendor/snix-store" }
tokio = { version = "1", features = ["full"] }
tempfile = "3"
