mod canonical;
pub mod discovery;
mod digest;
mod error;
pub mod policy;
pub mod release;
mod schema;
mod version;

pub use canonical::Canonicalize;
pub use digest::AttestationDigest;
pub use error::Error;
pub use release::BinaryDigest;
pub use release::DetachedSignature;
pub use release::FinalClass;
pub use release::PolicyStatus;
pub use release::RebuildEnvironmentSummary;
pub use release::ReleaseAttestation;
pub use release::SignatureSuite;
pub use release::TechnicalClass;
pub use release::TrustTier;
pub use release::WitnessAttestation;
pub use release::Workflow;
pub use release::binary_digests_match;
pub use policy::PolicyEvaluation;
pub use policy::PolicyFailureReason;
pub use policy::ReleasePolicy;
pub use policy::ReleaseRevocations;
pub use policy::ValidatedWitness;
pub use policy::evaluate_policy;
pub use discovery::DiscoveryError;
pub use discovery::VerificationDirectory;
pub use discovery::VerificationMaterial;
pub use schema::ArtifactAttestation;
pub use schema::ArtifactFacts;
pub use schema::ArtifactReference;
pub use schema::Claims;
pub use schema::ClosureAttestation;
pub use schema::ClosureFacts;
pub use schema::ClosureSemantics;
pub use schema::Edge;
pub use schema::EdgeKind;
pub use schema::Node;
pub use schema::NodeKind;
pub use schema::ProjectAttestation;
pub use schema::ProjectFacts;
pub use version::SchemaVersion;
