mod adapter;
mod canonical;
mod digest;
pub mod discovery;
mod error;
pub mod policy;
pub mod release;
mod schema;
mod version;

pub use adapter::binary_digests_match;
pub use adapter::encode_detached_signature;
pub use adapter::evaluate_policy;
pub use adapter::parse_detached_signature;
pub use canonical::Canonicalize;
pub use digest::AttestationDigest;
pub use discovery::DiscoveryError;
pub use discovery::VerificationDirectory;
pub use discovery::VerificationMaterial;
pub use error::Error;
pub use policy::PolicyEvaluation;
pub use policy::PolicyEvaluationInput;
pub use policy::PolicyFailureReason;
pub use policy::ReleasePolicy;
pub use policy::ReleaseRevocations;
pub use policy::ValidatedWitness;
pub use release::AgreementWitnessClassification;
pub use release::BinaryDigest;
pub use release::BinaryDigestMatchInput;
pub use release::DetachedSignature;
pub use release::FinalClass;
pub use release::INDEPENDENT_AGREEMENT_REPORT_SCHEMA;
pub use release::IndependentAgreementReport;
pub use release::IndependentAgreementReportInit;
pub use release::IndependentAgreementStatus;
pub use release::PolicyStatus;
pub use release::RebuildEnvironmentSummary;
pub use release::ReleaseAttestation;
pub use release::ReleaseAttestationInit;
pub use release::SignatureSuite;
pub use release::TechnicalClass;
pub use release::TrustTier;
pub use release::WITNESS_SOURCE_ACQUISITION_MODE_NOT_RECORDED;
pub use release::WITNESS_SOURCE_ACQUISITION_MODE_UNSPECIFIED;
pub use release::WitnessAttestation;
pub use release::WitnessClassificationReason;
pub use release::Workflow;
pub use release::independent_agreement_report_canonical_bytes;
pub use release::independent_agreement_report_canonical_digest;
pub use schema::ArtifactAttestation;
pub use schema::ArtifactFacts;
pub use schema::ArtifactReference;
pub use schema::Claims;
pub use schema::ClosureAttestation;
pub use schema::ClosureFacts;
pub use schema::ClosureSemantics;
pub use schema::Edge;
pub use schema::EdgeKind;
pub use schema::Node;
pub use schema::NodeKind;
pub use schema::ProjectAttestation;
pub use schema::ProjectFacts;
pub use version::SchemaVersion;
