//! Representative Rust compatibility rail.
//!
//! The maintained fixture is generated by `tests/rust_compatibility_rail.rs` so
//! the source shape stays deterministic without checking in vendored crate
//! payloads. It covers one binary, one local library, one vendored registry
//! source, one proc-macro crate, one build script metadata surface, and no
//! network access.
//!
//! Evidence is lane-scoped:
//! - sandboxed offline Cargo rail: `cargo-inside-mantle-sandbox`
//! - native rust-plan rail: `cargo-free-bounded-topology` or `blocked-unsupported-surface`
//!
//! This rail is not proof of full Cargo compatibility, compiler correctness,
//! release reproducibility, or bootstrap correctness.

fn main() {
    println!("representative Rust compatibility rail: see tests/rust_compatibility_rail.rs");
}
