//! Representative Rust compatibility rail.
//! This representative Rust compatibility rail is bounded evidence only.
//!
//! The maintained fixture is generated by `tests/rust_compatibility_rail.rs` so
//! the source shape stays deterministic without checking in vendored crate
//! payloads. The source-controlled surface matrix lives at
//! `examples/rust_compatibility_surface_matrix.ncl`; it names supported offline
//! Cargo surfaces, native `cargo-free-bounded-topology` path-workspace support,
//! blocked surfaces such as vendored git and native-link metadata, stable blocker
//! classes, and non-claims.
//!
//! Evidence is lane-scoped:
//! - sandboxed offline Cargo rail: `cargo-inside-mantle-sandbox`
//! - native rust-plan rail: `cargo-free-bounded-topology` or `blocked-unsupported-surface`
//!
//! This rail is not proof of full Cargo compatibility, compiler correctness,
//! release reproducibility, or bootstrap correctness.

fn main() {
    println!("representative Rust compatibility rail: see tests/rust_compatibility_rail.rs");
}
