use std::collections::BTreeMap;
use std::collections::BTreeSet;

use serde_json::Map;
use serde_json::Value;

use super::model::Invariant;
use super::schema::declared_non_null_type;
use super::schema::validate_schema;

pub fn render_contract(surface_id: &str, schema: &Value) -> Result<String, String> {
    let issues = validate_schema(surface_id, schema);
    if !issues.is_empty() {
        return Err(format!("schema is outside supported subset: {issues:?}"));
    }
    let root = schema.as_object().expect("validated object schema");
    let definitions = root.get("$defs").and_then(Value::as_object).cloned().unwrap_or_default();
    let order = definition_order(&definitions)?;
    let bounds = bound_declarations(schema)?;
    let mut output = String::new();
    output.push_str("# Generated by scripts/check-machine-schema-contracts.rs.\n");
    output.push_str("# Eager exact predicate over the supported schema subset; do not edit.\n");
    output.push_str("let C = import \"prelude.ncl\" in\n");
    for (name, value) in bounds {
        output.push_str(&format!("let {name} = {value} in\n"));
    }
    for name in order {
        let definition = definitions.get(&name).expect("ordered definition exists");
        let predicate = render_predicate_node(schema, definition, "value", 0)?;
        output.push_str(&format!("let {} = fun value => {predicate} in\n", predicate_identifier(&name)));
    }
    let predicate = render_predicate_node(schema, schema, "value", 0)?;
    output.push_str(&format!("C.FromPredicate (fun value => {predicate})\n"));
    if output.contains("Dyn") {
        return Err("generated contract contains forbidden Dyn fallback".to_string());
    }
    Ok(output)
}

fn render_predicate_node(root: &Value, schema: &Value, value: &str, depth: u32) -> Result<String, String> {
    let object = schema.as_object().ok_or_else(|| "predicate schema node must be object".to_string())?;
    if let Some(reference) = object.get("$ref").and_then(Value::as_str) {
        let name = reference
            .strip_prefix("#/$defs/")
            .ok_or_else(|| format!("unsupported contract reference {reference}"))?;
        return Ok(format!("{} ({value})", predicate_identifier(name)));
    }
    let nullable = object
        .get("type")
        .and_then(Value::as_array)
        .is_some_and(|types| types.iter().any(|kind| kind.as_str() == Some("null")));
    let mut universal_predicates = Vec::new();
    if let Some(expected) = object.get("const") {
        universal_predicates.push(format!("({value}) == {}", json_literal(expected)?));
    }
    if let Some(allowed) = object.get("enum") {
        universal_predicates.push(format!("std.array.elem ({value}) {}", json_literal(allowed)?));
    }
    let mut type_predicates = Vec::new();
    match declared_non_null_type(object) {
        Some("object") => type_predicates.extend(render_object_predicates(root, object, value, depth)?),
        Some("array") => type_predicates.extend(render_array_predicates(root, object, value, depth)?),
        Some("string") => type_predicates.extend(render_string_predicates(object, value)?),
        Some("integer") => type_predicates.extend(render_number_predicates(object, value, true)?),
        Some("number") => type_predicates.extend(render_number_predicates(object, value, false)?),
        Some("boolean") => type_predicates.push(format!("std.is_bool ({value})")),
        Some("null") => type_predicates.push(format!("({value}) == null")),
        Some(other) => return Err(format!("unsupported predicate type {other}")),
        None if object.contains_key("const") || object.contains_key("enum") => {}
        None => return Err("predicate node lacks renderable type".to_string()),
    }
    if !type_predicates.is_empty() {
        let type_body = join_predicates(type_predicates);
        universal_predicates.push(if nullable {
            format!("(({value}) == null || ({type_body}))")
        } else {
            type_body
        });
    }
    Ok(join_predicates(universal_predicates))
}

fn render_object_predicates(
    root: &Value,
    object: &Map<String, Value>,
    value: &str,
    depth: u32,
) -> Result<Vec<String>, String> {
    let next_depth = depth.saturating_add(1);
    let field_variable = format!("field_{next_depth}");
    let fields_expression = format!("std.record.fields ({value})");
    let properties = object.get("properties").and_then(Value::as_object);
    let required = object
        .get("required")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .collect::<BTreeSet<_>>();
    let mut predicates = vec![format!("std.is_record ({value})")];
    if object.contains_key("minProperties") {
        predicates.push(format!("std.array.length ({fields_expression}) >= {}", bound_name(object, "minProperties")?));
    }
    if object.contains_key("maxProperties") {
        predicates.push(format!("std.array.length ({fields_expression}) <= {}", bound_name(object, "maxProperties")?));
    }
    if let Some(properties) = properties {
        let names = properties.keys().cloned().map(Value::String).collect::<Vec<_>>();
        if object.get("additionalProperties") == Some(&Value::Bool(false)) {
            predicates.push(format!(
                "std.array.all (fun {field_variable} => std.array.elem {field_variable} {}) ({fields_expression})",
                json_literal(&Value::Array(names.clone()))?
            ));
        }
        for (name, child) in properties {
            let has_field = format!("std.record.has_field {} ({value})", json_string(name));
            let child_value = format!("std.record.get {} ({value})", json_string(name));
            let child_predicate = render_predicate_node(root, child, &child_value, next_depth)?;
            if required.contains(name.as_str()) {
                predicates.push(format!("({has_field} && ({child_predicate}))"));
            } else {
                predicates.push(format!("(!{has_field} || ({child_predicate}))"));
            }
        }
        if let Some(additional) = object.get("additionalProperties").filter(|value| value.is_object()) {
            let known = json_literal(&Value::Array(names))?;
            let dynamic_value = format!("std.record.get {field_variable} ({value})");
            let dynamic_predicate = render_predicate_node(root, additional, &dynamic_value, next_depth)?;
            predicates.push(format!(
                "std.array.all (fun {field_variable} => std.array.elem {field_variable} {known} || ({dynamic_predicate})) ({fields_expression})"
            ));
        }
    } else if let Some(additional) = object.get("additionalProperties").filter(|value| value.is_object()) {
        let dynamic_value = format!("std.record.get {field_variable} ({value})");
        let dynamic_predicate = render_predicate_node(root, additional, &dynamic_value, next_depth)?;
        predicates.push(format!("std.array.all (fun {field_variable} => {dynamic_predicate}) ({fields_expression})"));
    }
    predicates.extend(render_invariant_predicates(object, value)?);
    Ok(predicates)
}

fn render_array_predicates(
    root: &Value,
    object: &Map<String, Value>,
    value: &str,
    depth: u32,
) -> Result<Vec<String>, String> {
    let next_depth = depth.saturating_add(1);
    let item_variable = format!("item_{next_depth}");
    let mut predicates = vec![format!("std.is_array ({value})")];
    if object.contains_key("minItems") {
        predicates.push(format!("std.array.length ({value}) >= {}", bound_name(object, "minItems")?));
    }
    if object.contains_key("maxItems") {
        predicates.push(format!("std.array.length ({value}) <= {}", bound_name(object, "maxItems")?));
    }
    if let Some(items) = object.get("items") {
        let item_predicate = render_predicate_node(root, items, &item_variable, next_depth)?;
        predicates.push(format!("std.array.all (fun {item_variable} => {item_predicate}) ({value})"));
    }
    Ok(predicates)
}

fn render_string_predicates(object: &Map<String, Value>, value: &str) -> Result<Vec<String>, String> {
    let mut predicates = vec![format!("std.is_string ({value})")];
    if object.contains_key("minLength") {
        predicates.push(format!("C.Utf8ByteLength ({value}) >= {}", bound_name(object, "minLength")?));
    }
    if object.contains_key("maxLength") {
        predicates.push(format!("C.Utf8ByteLength ({value}) <= {}", bound_name(object, "maxLength")?));
    }
    if let Some(semantic) = object.get("x-mantle-semantic").and_then(Value::as_str) {
        let predicate = match semantic {
            "blake3" => "C.IsBlake3Hex",
            "mantle-digest" => "C.IsMantleDigest",
            "sha256" => "C.IsSha256Hex",
            "sha256-digest" => "C.IsSha256Digest",
            "mantle-reference" => "C.IsMantleReference",
            "safe-reference" => "C.IsSafeReference",
            "redaction-safe" => "C.IsRedactionSafe",
            "non-empty" => "C.IsNonEmptyString",
            other => return Err(format!("unsupported string semantic {other}")),
        };
        predicates.push(format!("{predicate} ({value})"));
    }
    Ok(predicates)
}

fn render_number_predicates(object: &Map<String, Value>, value: &str, integer: bool) -> Result<Vec<String>, String> {
    let mut predicates = vec![format!("std.is_number ({value})")];
    if integer {
        predicates.push(format!("std.number.is_integer ({value})"));
    }
    if object.contains_key("minimum") {
        predicates.push(format!("({value}) >= {}", bound_name(object, "minimum")?));
    }
    if object.contains_key("maximum") {
        predicates.push(format!("({value}) <= {}", bound_name(object, "maximum")?));
    }
    Ok(predicates)
}

fn bound_declarations(schema: &Value) -> Result<BTreeMap<String, String>, String> {
    let mut declarations = BTreeMap::new();
    collect_bound_declarations(schema, &mut declarations)?;
    Ok(declarations)
}

fn collect_bound_declarations(schema: &Value, declarations: &mut BTreeMap<String, String>) -> Result<(), String> {
    match schema {
        Value::Object(object) => {
            if let Some(names) = object.get("x-mantle-bound-name").and_then(Value::as_object) {
                for (keyword, name) in names {
                    let name = name.as_str().ok_or_else(|| format!("bound {keyword} name is not a string"))?;
                    let value = object
                        .get(keyword)
                        .ok_or_else(|| format!("bound name {name} has no {keyword} value"))?
                        .to_string();
                    if let Some(previous) = declarations.insert(name.to_string(), value.clone())
                        && previous != value
                    {
                        return Err(format!("bound name {name} has conflicting values {previous} and {value}"));
                    }
                }
            }
            for (key, child) in object {
                if key != "x-mantle-bound-name" {
                    collect_bound_declarations(child, declarations)?;
                }
            }
        }
        Value::Array(values) => {
            for child in values {
                collect_bound_declarations(child, declarations)?;
            }
        }
        _ => {}
    }
    Ok(())
}

fn bound_name<'a>(object: &'a Map<String, Value>, keyword: &str) -> Result<&'a str, String> {
    object
        .get("x-mantle-bound-name")
        .and_then(Value::as_object)
        .and_then(|names| names.get(keyword))
        .and_then(Value::as_str)
        .ok_or_else(|| format!("bound {keyword} has no generated identifier"))
}

fn render_invariant_predicates(object: &Map<String, Value>, value: &str) -> Result<Vec<String>, String> {
    object
        .get("x-mantle-invariants")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .map(|raw| {
            let invariant = serde_json::from_value::<Invariant>(raw.clone())
                .map_err(|err| format!("parsing invariant for predicate rendering: {err}"))?;
            render_invariant_predicate(&invariant, value)
        })
        .collect()
}

fn render_invariant_predicate(invariant: &Invariant, root: &str) -> Result<String, String> {
    match invariant.kind.as_str() {
        "length-equals" => render_length_equals(invariant, root),
        "sum-equals" => render_sum_equals(invariant, root),
        "empty-iff" => render_empty_iff(invariant, root),
        "present-iff" => render_present_iff(invariant, root),
        "boolean-not" => render_boolean_not(invariant, root),
        "boolean-or" => render_boolean_or(invariant, root),
        "selected-not-in-array" => render_selected_not_in_array(invariant, root),
        "all-item-equals-iff" => render_all_item_equals_iff(invariant, root),
        "unique-by" => render_unique_by(invariant, root),
        "disjoint-by" => render_disjoint_by(invariant, root),
        "field-equals-const-when" => render_field_equals_const_when(invariant, root),
        "arrays-empty-iff-enum" => render_arrays_empty_iff_enum(invariant, root),
        other => Err(format!("unsupported invariant rendering kind {other}")),
    }
}

fn render_length_equals(invariant: &Invariant, root: &str) -> Result<String, String> {
    Ok(format!(
        "std.array.length {} == {}",
        nickel_path(root, &invariant.array)?,
        nickel_path(root, &invariant.integer)?
    ))
}

fn render_sum_equals(invariant: &Invariant, root: &str) -> Result<String, String> {
    Ok(format!(
        "({}) == {}",
        render_joined_paths(root, &invariant.terms, " + ")?,
        nickel_path(root, &invariant.target)?
    ))
}

fn render_empty_iff(invariant: &Invariant, root: &str) -> Result<String, String> {
    Ok(format!(
        "(std.array.length {} == 0) == {}",
        nickel_path(root, &invariant.array)?,
        nickel_path(root, &invariant.boolean)?
    ))
}

fn render_present_iff(invariant: &Invariant, root: &str) -> Result<String, String> {
    let expected = nickel_path(root, &invariant.boolean)?;
    invariant
        .fields
        .iter()
        .map(|path| {
            let (parent, field) = nickel_parent_and_field(root, path)?;
            Ok(format!(
                "((std.record.has_field {} ({parent})) && (std.record.get {} ({parent}) != null)) == {expected}",
                json_string(&field),
                json_string(&field)
            ))
        })
        .collect::<Result<Vec<String>, String>>()
        .map(|checks| checks.join(" && "))
}

fn render_boolean_not(invariant: &Invariant, root: &str) -> Result<String, String> {
    Ok(format!("{} != {}", nickel_path(root, &invariant.boolean)?, nickel_path(root, &invariant.target)?))
}

fn render_boolean_or(invariant: &Invariant, root: &str) -> Result<String, String> {
    Ok(format!(
        "({}) == {}",
        render_joined_paths(root, &invariant.terms, " || ")?,
        nickel_path(root, &invariant.target)?
    ))
}

fn render_selected_not_in_array(invariant: &Invariant, root: &str) -> Result<String, String> {
    Ok(format!(
        "std.array.all (fun item => std.record.get {} item != {}) {}",
        json_string(pointer_leaf(&invariant.item_field)?),
        nickel_path(root, &invariant.target)?,
        nickel_path(root, &invariant.array)?
    ))
}

fn render_all_item_equals_iff(invariant: &Invariant, root: &str) -> Result<String, String> {
    Ok(format!(
        "(std.array.all (fun item => std.record.get {} item == {}) {}) == {}",
        json_string(pointer_leaf(&invariant.item_field)?),
        json_literal(&invariant.value)?,
        nickel_path(root, &invariant.array)?,
        nickel_path(root, &invariant.boolean)?
    ))
}

fn render_unique_by(invariant: &Invariant, root: &str) -> Result<String, String> {
    let array = nickel_path(root, &invariant.array)?;
    let equality = if invariant.item_field.is_empty() {
        "other == item".to_string()
    } else {
        let field = json_string(pointer_leaf(&invariant.item_field)?);
        format!("std.record.get {field} other == std.record.get {field} item")
    };
    Ok(format!(
        "std.array.all (fun item => std.array.length (std.array.filter (fun other => {equality}) {array}) == 1) {array}"
    ))
}

fn render_disjoint_by(invariant: &Invariant, root: &str) -> Result<String, String> {
    let left = nickel_path(root, &invariant.array)?;
    let right = nickel_path(root, &invariant.other_array)?;
    let left_field = json_string(pointer_leaf(&invariant.item_field)?);
    let right_field = json_string(pointer_leaf(&invariant.other_item_field)?);
    Ok(format!(
        "std.array.all (fun r => std.array.all (fun l => std.record.get {left_field} l != std.record.get {right_field} r) {left}) {right}"
    ))
}

fn render_field_equals_const_when(invariant: &Invariant, root: &str) -> Result<String, String> {
    Ok(format!(
        "(!{}) || ({} == {})",
        nickel_path(root, &invariant.boolean)?,
        nickel_path(root, &invariant.target)?,
        json_literal(&invariant.value)?
    ))
}

fn render_arrays_empty_iff_enum(invariant: &Invariant, root: &str) -> Result<String, String> {
    let emptiness = invariant
        .fields
        .iter()
        .map(|path| Ok(format!("std.array.length {} == 0", nickel_path(root, path)?)))
        .collect::<Result<Vec<String>, String>>()?
        .join(" && ");
    Ok(format!(
        "({emptiness}) == ({} == {})",
        nickel_path(root, &invariant.target)?,
        json_literal(&invariant.value)?
    ))
}

fn render_joined_paths(root: &str, paths: &[String], separator: &str) -> Result<String, String> {
    paths
        .iter()
        .map(|path| nickel_path(root, path))
        .collect::<Result<Vec<_>, _>>()
        .map(|values| values.join(separator))
}

fn join_predicates(predicates: Vec<String>) -> String {
    if predicates.is_empty() {
        "true".to_string()
    } else {
        format!("({})", predicates.join("\n  && "))
    }
}

fn definition_order(definitions: &Map<String, Value>) -> Result<Vec<String>, String> {
    let mut order = Vec::new();
    let mut visiting = BTreeSet::new();
    let mut visited = BTreeSet::new();
    for name in definitions.keys() {
        visit_definition(name, definitions, &mut visiting, &mut visited, &mut order)?;
    }
    Ok(order)
}

fn visit_definition(
    name: &str,
    definitions: &Map<String, Value>,
    visiting: &mut BTreeSet<String>,
    visited: &mut BTreeSet<String>,
    order: &mut Vec<String>,
) -> Result<(), String> {
    if visited.contains(name) {
        return Ok(());
    }
    if !visiting.insert(name.to_string()) {
        return Err(format!("recursive schema definition {name} is unsupported"));
    }
    let definition = definitions.get(name).ok_or_else(|| format!("missing definition {name}"))?;
    let mut dependencies = BTreeSet::new();
    collect_definition_references(definition, &mut dependencies);
    for dependency in dependencies {
        if !definitions.contains_key(&dependency) {
            return Err(format!("definition {name} references missing definition {dependency}"));
        }
        visit_definition(&dependency, definitions, visiting, visited, order)?;
    }
    visiting.remove(name);
    visited.insert(name.to_string());
    order.push(name.to_string());
    Ok(())
}

fn collect_definition_references(value: &Value, dependencies: &mut BTreeSet<String>) {
    match value {
        Value::Object(object) => {
            if let Some(reference) = object.get("$ref").and_then(Value::as_str)
                && let Some(name) = reference.strip_prefix("#/$defs/")
            {
                dependencies.insert(name.to_string());
            }
            for child in object.values() {
                collect_definition_references(child, dependencies);
            }
        }
        Value::Array(array) => {
            for child in array {
                collect_definition_references(child, dependencies);
            }
        }
        _ => {}
    }
}

fn predicate_identifier(value: &str) -> String {
    format!("is_{}", nickel_identifier(value))
}

fn nickel_identifier(value: &str) -> String {
    let mut output = String::new();
    for (index, byte) in value.bytes().enumerate() {
        if index == 0 && byte.is_ascii_digit() {
            output.push('_');
        }
        output.push(if byte.is_ascii_alphanumeric() || byte == b'_' {
            char::from(byte)
        } else {
            '_'
        });
    }
    output
}

fn nickel_path(root: &str, pointer: &str) -> Result<String, String> {
    if pointer.is_empty() {
        return Ok(format!("({root})"));
    }
    if !pointer.starts_with('/') {
        return Err(format!("invariant path must be a JSON pointer: {pointer}"));
    }
    let mut expression = root.to_string();
    for segment in pointer.split('/').skip(1) {
        let decoded = segment.replace("~1", "/").replace("~0", "~");
        if decoded.is_empty() || decoded.bytes().all(|byte| byte.is_ascii_digit()) {
            return Err(format!("unsupported invariant path segment {decoded:?}"));
        }
        expression = format!("std.record.get {} ({expression})", json_string(&decoded));
    }
    Ok(format!("({expression})"))
}

fn nickel_parent_and_field(root: &str, pointer: &str) -> Result<(String, String), String> {
    let leaf = pointer_leaf(pointer)?.to_string();
    let parent = pointer.rsplit_once('/').map(|(parent, _)| parent).unwrap_or_default();
    Ok((nickel_path(root, parent)?, leaf))
}

fn pointer_leaf(pointer: &str) -> Result<&str, String> {
    pointer
        .rsplit_once('/')
        .map(|(_, leaf)| leaf)
        .filter(|leaf| !leaf.is_empty())
        .ok_or_else(|| format!("pointer has no field leaf: {pointer}"))
}

fn json_literal(value: &Value) -> Result<String, String> {
    serde_json::to_string(value).map_err(|err| format!("serializing Nickel literal: {err}"))
}

fn json_string(value: &str) -> String {
    serde_json::to_string(value).expect("string serialization cannot fail")
}
