#!/usr/bin/env bash
set -euo pipefail

PROOF_SCHEMA="mantle-cargo-free-rust-plan-proof-v1"
DEFAULT_PROOF_ROOT="target/cargo-free-rust-plan-proof"
EXPECTED_SMOKE_STDOUT="42"

usage() {
  cat <<'USAGE'
usage: scripts/prove-cargo-free-rust-plan.sh [--check|--full] [--bundle-dir DIR] [--mantle-bin PATH]

Runs a bounded Cargo-free Rust planning/topology proof. --check validates tools only.
--full creates a two-crate path workspace, runs rust-plan --no-cargo-oracle with a failing Cargo shim,
and writes an audit bundle with receipts, streams, tool/source identity, output digests, and smoke output.
USAGE
}

mode="check"
bundle_dir=""
mantle_bin="${MANTLE_BIN:-}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)
      mode="check"
      shift
      ;;
    --full)
      mode="full"
      shift
      ;;
    --bundle-dir)
      bundle_dir="${2:?--bundle-dir requires a path}"
      shift 2
      ;;
    --mantle-bin)
      mantle_bin="${2:?--mantle-bin requires a path}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$bundle_dir" ]]; then
  bundle_dir="$DEFAULT_PROOF_ROOT/run-$(date -u +%Y%m%dT%H%M%SZ)"
fi

resolve_mantle_bin() {
  if [[ -n "$mantle_bin" ]]; then
    printf '%s\n' "$mantle_bin"
    return
  fi
  if command -v mantle >/dev/null 2>&1; then
    command -v mantle
    return
  fi
  if [[ -x "/home/brittonr/.cargo-target/debug/mantle" ]]; then
    printf '%s\n' "/home/brittonr/.cargo-target/debug/mantle"
    return
  fi
  if [[ -x "target/debug/mantle" ]]; then
    printf '%s\n' "target/debug/mantle"
    return
  fi
  echo "could not locate mantle binary; pass --mantle-bin" >&2
  exit 1
}

require_tool() {
  local tool="$1"
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "required tool not found: $tool" >&2
    exit 1
  fi
}

write_preflight() {
  local mantle_path="$1"
  mkdir -p "$bundle_dir"
  jq -n \
    --arg schema "$PROOF_SCHEMA" \
    --arg mode "$mode" \
    --arg mantle_bin "$mantle_path" \
    --arg rustc "$(command -v rustc)" \
    --arg jq "$(command -v jq)" \
    '{schema:$schema, mode:$mode, tools:{mantle:$mantle_bin,rustc:$rustc,jq:$jq}}' \
    > "$bundle_dir/preflight.json"
}

write_fixture() {
  local root="$1"
  local app="$root/no-cargo-app"
  local helper="$root/helper-lib"
  mkdir -p "$app/src/bin" "$helper/src"
  cat > "$helper/src/lib.rs" <<'RS'
pub fn helper() -> u32 { 41 }
RS
  cat > "$helper/Cargo.toml" <<'TOML'
[package]
name = "helper-lib"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
TOML
  cat > "$app/src/lib.rs" <<'RS'
pub fn value() -> u32 { helper_lib::helper() + 1 }
RS
  cat > "$app/src/bin/no_cargo_app.rs" <<'RS'
fn main() { println!("{}", no_cargo_app::value()); }
RS
  cat > "$app/Cargo.toml" <<'TOML'
[package]
name = "no-cargo-app"
version = "0.1.0"
edition = "2021"

[dependencies]
helper-lib = { path = "../helper-lib" }

[lib]
path = "src/lib.rs"

[[bin]]
name = "no-cargo-app"
path = "src/bin/no_cargo_app.rs"
TOML
  cat > "$app/Cargo.lock" <<'TOML'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "helper-lib"
version = "0.1.0"

[[package]]
name = "no-cargo-app"
version = "0.1.0"
dependencies = [
 "helper-lib",
]
TOML
  printf '%s\n' "$app"
}

run_full_proof() {
  local mantle_path="$1"
  local work_dir="$bundle_dir/work"
  local execution_dir="$bundle_dir/execution"
  local cargo_shim="$bundle_dir/cargo-forbidden"
  local cargo_marker="$bundle_dir/cargo-was-invoked"
  mkdir -p "$work_dir" "$execution_dir"
  local app_dir
  app_dir="$(write_fixture "$work_dir")"
  cat > "$cargo_shim" <<SH
#!/bin/sh
printf invoked > "$cargo_marker"
exit 99
SH
  chmod +x "$cargo_shim"

  set +e
  "$mantle_path" --json rust-plan \
    --root "$app_dir" \
    --cargo "$cargo_shim" \
    --no-cargo-oracle \
    --execute-topology \
    --execution-output-root "$execution_dir" \
    > "$bundle_dir/receipt.json" \
    2> "$bundle_dir/stderr.txt"
  local status=$?
  set -e
  printf '%s\n' "$status" > "$bundle_dir/status.txt"
  if [[ "$status" -ne 0 ]]; then
    jq -n \
      --arg schema "$PROOF_SCHEMA" \
      --arg status "blocked" \
      --arg receipt "$bundle_dir/receipt.json" \
      --arg stderr "$bundle_dir/stderr.txt" \
      '{schema:$schema,status:$status,receipt:$receipt,stderr:$stderr}' \
      > "$bundle_dir/meta.json"
    exit "$status"
  fi
  if [[ -e "$cargo_marker" ]]; then
    echo "Cargo shim was invoked during Cargo-free proof" >&2
    exit 1
  fi

  jq '.topology_execution.unit_executions[].output_artifact_digests[]?' \
    "$bundle_dir/receipt.json" > "$bundle_dir/output-digests.json"
  local binary
  binary="$(find "$execution_dir" -type f -perm -u+x ! -name '*.json' ! -name '*.rlib' | sort | head -n 1)"
  if [[ -z "$binary" ]]; then
    echo "proof produced no executable output" >&2
    exit 1
  fi
  "$binary" > "$bundle_dir/smoke-stdout.txt" 2> "$bundle_dir/smoke-stderr.txt"
  local smoke_stdout
  smoke_stdout="$(tr -d '\n' < "$bundle_dir/smoke-stdout.txt")"
  if [[ "$smoke_stdout" != "$EXPECTED_SMOKE_STDOUT" ]]; then
    echo "unexpected smoke stdout: $smoke_stdout" >&2
    exit 1
  fi
  jq -n \
    --arg schema "$PROOF_SCHEMA" \
    --arg status "success" \
    --arg workspace "$app_dir" \
    --arg receipt "$bundle_dir/receipt.json" \
    --arg execution "$execution_dir" \
    --arg binary "$binary" \
    --arg smoke_stdout "$EXPECTED_SMOKE_STDOUT" \
    --arg cargo_forbidden_marker_absent "true" \
    '{schema:$schema,status:$status,workspace:$workspace,receipt:$receipt,execution:$execution,binary:$binary,smoke_stdout:$smoke_stdout,cargo_forbidden_marker_absent:($cargo_forbidden_marker_absent == "true")}' \
    > "$bundle_dir/meta.json"
}

require_tool jq
require_tool rustc
mantle_bin="$(resolve_mantle_bin)"
if [[ ! -x "$mantle_bin" ]]; then
  echo "mantle binary is not executable: $mantle_bin" >&2
  exit 1
fi
write_preflight "$mantle_bin"

case "$mode" in
  check)
    echo "cargo-free proof preflight OK: $bundle_dir"
    ;;
  full)
    run_full_proof "$mantle_bin"
    echo "cargo-free proof OK: $bundle_dir"
    ;;
  *)
    echo "unsupported mode: $mode" >&2
    exit 2
    ;;
esac
