#!/usr/bin/env bash
set -euo pipefail

PROOF_SCHEMA="mantle-cargo-free-rust-plan-proof-v2"
DEFAULT_PROOF_ROOT="target/cargo-free-rust-plan-proof"
SELF_BUILD_PROOF_ROOT="target/no-cargo-self-build-probe"
EXPECTED_SMOKE_STDOUT="42"
FIRST_MATCH_LINES=1
PROOF_BLOCKED_EXIT=1

usage() {
  cat <<'USAGE'
usage: scripts/prove-cargo-free-rust-plan.sh [--check|--full|--self-build] [--bundle-dir DIR] [--mantle-bin PATH] [--root DIR]

Runs bounded Cargo-free Rust planning/topology proofs. --check validates tools only.
--full creates a two-crate path workspace, runs rust-plan --no-cargo-oracle with a failing Cargo shim,
and writes an audit bundle with receipts, streams, tool/source identity, output digests, and smoke output.
--self-build runs the same Cargo-forbidden path against the checked-out Mantle workspace and smoke-checks
its produced mantle CLI with --help. This is not Mantle fixed-point or release reproducibility evidence.
USAGE
}

mode="check"
bundle_dir=""
mantle_bin="${MANTLE_BIN:-}"
root_dir="${MANTLE_PROOF_ROOT:-.}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)
      mode="check"
      shift
      ;;
    --full)
      mode="full"
      shift
      ;;
    --self-build)
      mode="self-build"
      shift
      ;;
    --bundle-dir)
      bundle_dir="${2:?--bundle-dir requires a path}"
      shift 2
      ;;
    --mantle-bin)
      mantle_bin="${2:?--mantle-bin requires a path}"
      shift 2
      ;;
    --root)
      root_dir="${2:?--root requires a path}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$bundle_dir" ]]; then
  case "$mode" in
    self-build)
      bundle_dir="$SELF_BUILD_PROOF_ROOT/run-$(date -u +%Y%m%dT%H%M%SZ)"
      ;;
    *)
      bundle_dir="$DEFAULT_PROOF_ROOT/run-$(date -u +%Y%m%dT%H%M%SZ)"
      ;;
  esac
fi

resolve_mantle_bin() {
  if [[ -n "$mantle_bin" ]]; then
    printf '%s\n' "$mantle_bin"
    return
  fi
  if command -v mantle >/dev/null 2>&1; then
    command -v mantle
    return
  fi
  if [[ -n "${CARGO_TARGET_DIR:-}" && -x "$CARGO_TARGET_DIR/debug/mantle" ]]; then
    printf '%s\n' "$CARGO_TARGET_DIR/debug/mantle"
    return
  fi
  if [[ -x "target/debug/mantle" ]]; then
    printf '%s\n' "target/debug/mantle"
    return
  fi
  echo "could not locate mantle binary; pass --mantle-bin" >&2
  exit 1
}

require_tool() {
  local tool="$1"
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "required tool not found: $tool" >&2
    exit 1
  fi
}

write_preflight() {
  local mantle_path="$1"
  local proof_root="$2"
  mkdir -p "$bundle_dir"
  jq -n \
    --arg schema "$PROOF_SCHEMA" \
    --arg mode "$mode" \
    --arg root "$proof_root" \
    --arg mantle_bin "$mantle_path" \
    --arg rustc "$(command -v rustc)" \
    --arg jq "$(command -v jq)" \
    '{schema:$schema, mode:$mode, root:$root, tools:{mantle:$mantle_bin,rustc:$rustc,jq:$jq}}' \
    > "$bundle_dir/preflight.json"
}

write_fixture() {
  local root="$1"
  local app="$root/no-cargo-app"
  local helper="$root/helper-lib"
  mkdir -p "$app/src/bin" "$helper/src"
  cat > "$helper/src/lib.rs" <<'RS'
pub fn helper() -> u32 { 41 }
RS
  cat > "$helper/Cargo.toml" <<'TOML'
[package]
name = "helper-lib"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
TOML
  cat > "$app/src/lib.rs" <<'RS'
pub fn value() -> u32 { helper_lib::helper() + 1 }
RS
  cat > "$app/src/bin/no_cargo_app.rs" <<'RS'
fn main() { println!("{}", no_cargo_app::value()); }
RS
  cat > "$app/Cargo.toml" <<'TOML'
[package]
name = "no-cargo-app"
version = "0.1.0"
edition = "2021"

[dependencies]
helper-lib = { path = "../helper-lib" }

[lib]
path = "src/lib.rs"

[[bin]]
name = "no-cargo-app"
path = "src/bin/no_cargo_app.rs"
TOML
  cat > "$app/Cargo.lock" <<'TOML'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "helper-lib"
version = "0.1.0"

[[package]]
name = "no-cargo-app"
version = "0.1.0"
dependencies = [
 "helper-lib",
]
TOML
  printf '%s\n' "$app"
}

write_cargo_shim() {
  local cargo_shim="$1"
  local cargo_marker="$2"
  cat > "$cargo_shim" <<SH
#!/bin/sh
printf invoked > "$cargo_marker"
exit 99
SH
  chmod +x "$cargo_shim"
}

run_cargo_free_topology() {
  local mantle_path="$1"
  local proof_root="$2"
  local execution_dir="$3"
  local cargo_shim="$4"
  set +e
  "$mantle_path" --json rust-plan \
    --root "$proof_root" \
    --cargo "$cargo_shim" \
    --no-cargo-oracle \
    --execute-topology \
    --execution-output-root "$execution_dir" \
    > "$bundle_dir/receipt.json" \
    2> "$bundle_dir/stderr.txt"
  local status=$?
  set -e
  printf '%s\n' "$status" > "$bundle_dir/status.txt"
}

receipt_execution_status() {
  if [[ ! -s "$bundle_dir/receipt.json" ]]; then
    printf '%s\n' "missing"
    return
  fi
  jq -r '.topology_execution.execution_status // "missing"' "$bundle_dir/receipt.json" 2>/dev/null || printf '%s\n' "invalid"
}

write_blocker_summary() {
  if [[ ! -s "$bundle_dir/receipt.json" ]]; then
    printf '%s\n' '[]' > "$bundle_dir/blocker-summary.json"
    return
  fi
  jq '[.topology_execution.unit_executions[]? | select(.execution_status != "success") | {unit_id,package_id,target_name,target_kind,execution_status,blocker}]' \
    "$bundle_dir/receipt.json" > "$bundle_dir/blocker-summary.json" 2>/dev/null || printf '%s\n' '[]' > "$bundle_dir/blocker-summary.json"
}

write_blocked_meta() {
  local proof_root="$1"
  local cargo_marker="$2"
  write_blocker_summary
  jq -n \
    --arg schema "$PROOF_SCHEMA" \
    --arg status "blocked" \
    --arg workspace "$proof_root" \
    --arg receipt "$bundle_dir/receipt.json" \
    --arg stderr "$bundle_dir/stderr.txt" \
    --arg cargo_forbidden_marker_absent "$([[ ! -e "$cargo_marker" ]] && printf true || printf false)" \
    '{schema:$schema,status:$status,workspace:$workspace,receipt:$receipt,stderr:$stderr,cargo_forbidden_marker_absent:($cargo_forbidden_marker_absent == "true")}' \
    > "$bundle_dir/meta.json"
}

write_non_claims() {
  cat > "$bundle_dir/non-claims.txt" <<'TXT'
This proof does not claim Mantle fixed-point self-hosting.
This proof does not claim source-built bootstrap closure provenance.
This proof does not claim release-quality reproducibility.
This proof does not claim network source fetching.
TXT
}

write_output_digests() {
  jq '.topology_execution.unit_executions[].output_artifact_digests[]?' \
    "$bundle_dir/receipt.json" > "$bundle_dir/output-digests.json"
}

find_first_executable() {
  local execution_dir="$1"
  find "$execution_dir" -type f -perm -u+x ! -name '*.json' ! -name '*.rlib' | sort | head -n "$FIRST_MATCH_LINES"
}

find_named_executable() {
  local execution_dir="$1"
  local executable_name="$2"
  find "$execution_dir" -type f -perm -u+x -name "$executable_name" | sort | head -n "$FIRST_MATCH_LINES"
}

write_success_meta() {
  local proof_root="$1"
  local execution_dir="$2"
  local binary="$3"
  local smoke_stdout_expected="$4"
  jq -n \
    --arg schema "$PROOF_SCHEMA" \
    --arg status "success" \
    --arg workspace "$proof_root" \
    --arg receipt "$bundle_dir/receipt.json" \
    --arg execution "$execution_dir" \
    --arg binary "$binary" \
    --arg smoke_stdout "$smoke_stdout_expected" \
    --arg cargo_forbidden_marker_absent "true" \
    '{schema:$schema,status:$status,workspace:$workspace,receipt:$receipt,execution:$execution,binary:$binary,smoke_stdout:$smoke_stdout,cargo_forbidden_marker_absent:($cargo_forbidden_marker_absent == "true")}' \
    > "$bundle_dir/meta.json"
}

run_full_proof() {
  local mantle_path="$1"
  local work_dir="$bundle_dir/work"
  local execution_dir="$bundle_dir/execution"
  local cargo_shim="$bundle_dir/cargo-forbidden"
  local cargo_marker="$bundle_dir/cargo-was-invoked"
  mkdir -p "$work_dir" "$execution_dir"
  local app_dir
  app_dir="$(write_fixture "$work_dir")"
  write_cargo_shim "$cargo_shim" "$cargo_marker"
  run_cargo_free_topology "$mantle_path" "$app_dir" "$execution_dir" "$cargo_shim"
  local status
  status="$(cat "$bundle_dir/status.txt")"
  local execution_status
  execution_status="$(receipt_execution_status)"
  if [[ "$status" -ne 0 || "$execution_status" != "success" ]]; then
    write_blocked_meta "$app_dir" "$cargo_marker"
    if [[ "$status" -ne 0 ]]; then
      exit "$status"
    fi
    exit "$PROOF_BLOCKED_EXIT"
  fi
  if [[ -e "$cargo_marker" ]]; then
    echo "Cargo shim was invoked during Cargo-free proof" >&2
    exit 1
  fi

  write_output_digests
  local binary
  binary="$(find_first_executable "$execution_dir")"
  if [[ -z "$binary" ]]; then
    echo "proof produced no executable output" >&2
    exit 1
  fi
  "$binary" > "$bundle_dir/smoke-stdout.txt" 2> "$bundle_dir/smoke-stderr.txt"
  local smoke_stdout
  smoke_stdout="$(tr -d '\n' < "$bundle_dir/smoke-stdout.txt")"
  if [[ "$smoke_stdout" != "$EXPECTED_SMOKE_STDOUT" ]]; then
    echo "unexpected smoke stdout: $smoke_stdout" >&2
    exit 1
  fi
  write_blocker_summary
  write_non_claims
  write_success_meta "$app_dir" "$execution_dir" "$binary" "$EXPECTED_SMOKE_STDOUT"
}

run_self_build_proof() {
  local mantle_path="$1"
  local proof_root="$2"
  local execution_dir="$bundle_dir/execution"
  local cargo_shim="$bundle_dir/cargo-forbidden"
  local cargo_marker="$bundle_dir/cargo-was-invoked"
  mkdir -p "$execution_dir"
  write_cargo_shim "$cargo_shim" "$cargo_marker"
  run_cargo_free_topology "$mantle_path" "$proof_root" "$execution_dir" "$cargo_shim"
  local status
  status="$(cat "$bundle_dir/status.txt")"
  local execution_status
  execution_status="$(receipt_execution_status)"
  if [[ "$status" -ne 0 || "$execution_status" != "success" ]]; then
    write_blocked_meta "$proof_root" "$cargo_marker"
    if [[ "$status" -ne 0 ]]; then
      exit "$status"
    fi
    exit "$PROOF_BLOCKED_EXIT"
  fi
  if [[ -e "$cargo_marker" ]]; then
    echo "Cargo shim was invoked during Cargo-free self-build proof" >&2
    exit 1
  fi

  write_output_digests
  local binary
  binary="$(find_named_executable "$execution_dir" mantle)"
  if [[ -z "$binary" ]]; then
    echo "self-build proof produced no mantle executable output" >&2
    exit 1
  fi
  "$binary" --help > "$bundle_dir/smoke-stdout.txt" 2> "$bundle_dir/smoke-stderr.txt"
  if ! grep -q 'Mantle build system' "$bundle_dir/smoke-stdout.txt"; then
    echo "self-build smoke output did not look like mantle --help" >&2
    exit 1
  fi
  write_blocker_summary
  write_non_claims
  write_success_meta "$proof_root" "$execution_dir" "$binary" "Mantle build system"
}

require_tool jq
require_tool rustc
mantle_bin="$(resolve_mantle_bin)"
if [[ ! -x "$mantle_bin" ]]; then
  echo "mantle binary is not executable: $mantle_bin" >&2
  exit 1
fi
write_preflight "$mantle_bin" "$root_dir"

case "$mode" in
  check)
    echo "cargo-free proof preflight OK: $bundle_dir"
    ;;
  full)
    run_full_proof "$mantle_bin"
    echo "cargo-free proof OK: $bundle_dir"
    ;;
  self-build)
    run_self_build_proof "$mantle_bin" "$root_dir"
    echo "cargo-free self-build proof OK: $bundle_dir"
    ;;
  *)
    echo "unsupported mode: $mode" >&2
    exit 2
    ;;
esac
