#![no_std]
extern crate alloc;

mod determinism;
mod error;
mod manifest;
mod nix_witness;
mod reproducibility;

pub use determinism::BUILD_EFFECT_POLICY_VERSION;
pub use determinism::BuildEffect;
pub use determinism::DETERMINISTIC_BUILD_PROOF_RECEIPT_SCHEMA;
pub use determinism::DETERMINISTIC_SANDBOX_ISOLATION_EVIDENCE_SCHEMA;
pub use determinism::DeterministicBuildProofReceipt;
pub use determinism::DeterministicBuildProofReceiptInit;
pub use determinism::DeterministicBuildProofVerdict;
pub use determinism::DeterministicBuildRunReceipt;
pub use determinism::DeterministicOutputDigest;
pub use determinism::DeterministicProofUnit;
pub use determinism::DeterministicSandboxIsolationEvidence;
pub use determinism::DeterministicSandboxIsolationEvidenceStatus;
pub use determinism::PURE_LOCAL_BUILD_EFFECTS;
pub use determinism::REQUIRED_ISOLATION_CHECKS;
pub use determinism::SUPPORTED_SANDBOX_PROFILE_FAMILY;
pub use determinism::canonical_deterministic_build_proof_receipt;
pub use determinism::deterministic_build_proof_receipt_canonical_bytes;
pub use determinism::deterministic_build_proof_receipt_digest_blake3;
pub use determinism::deterministic_release_claim_eligible;
pub use determinism::deterministic_sandbox_isolation_evidence_canonical_bytes;
pub use determinism::deterministic_sandbox_isolation_evidence_digest_blake3;
pub use determinism::validate_deterministic_sandbox_isolation_evidence;
pub use error::ReleaseEvidenceError;
pub use manifest::BLAKE3_HEX_LENGTH_CHARS;
pub use manifest::BundledArtifact;
pub use manifest::BundledArtifactKind;
pub use manifest::CLAIM_SCOPE_PACKAGED_INTEGRITY;
pub use manifest::DEFAULT_PROOF_WORKFLOW_COMMAND;
pub use manifest::DEFAULT_PROOF_WORKFLOW_VERSION;
pub use manifest::DETERMINISTIC_BUILD_PROOF_EVIDENCE_ROLE;
pub use manifest::DETERMINISTIC_SANDBOX_ISOLATION_EVIDENCE_ROLE;
pub use manifest::FULL_SELF_HOSTING_PROOF_SCHEMA;
pub use manifest::FullSelfHostingProofIdentityFields;
pub use manifest::PROVIDER_FIXED_POINT_PROOF_EVIDENCE_ROLE;
pub use manifest::ProviderFixedPointProofArtifact;
pub use manifest::RELEASE_EVIDENCE_SCHEMA;
pub use manifest::ReleaseEvidenceManifest;
pub use manifest::ReleaseProofLinkage;
pub use manifest::ReleaseWorkflowIdentity;
pub use manifest::RoleBoundedReleaseArtifact;
pub use manifest::canonical_release_evidence_manifest;
pub use manifest::extract_full_self_hosting_proof_identity_fields;
pub use manifest::validate_bundled_artifact_record;
pub use nix_witness::NIX_CROSS_BUILDER_WITNESS_PROOF_CLASS;
pub use nix_witness::NIX_CROSS_BUILDER_WITNESS_RECEIPT_SCHEMA;
pub use nix_witness::NixCrossBuilderArtifactDigest;
pub use nix_witness::NixCrossBuilderBuildPolicy;
pub use nix_witness::NixCrossBuilderWitnessReceipt;
pub use nix_witness::NixCrossBuilderWitnessReceiptInit;
pub use nix_witness::NixCrossBuilderWitnessVerdict;
pub use nix_witness::canonical_nix_cross_builder_witness_receipt;
pub use nix_witness::nix_cross_builder_witness_receipt_canonical_bytes;
pub use nix_witness::nix_cross_builder_witness_receipt_digest_blake3;
pub use reproducibility::RELEASE_REPRODUCIBILITY_REPORT_SCHEMA;
pub use reproducibility::RebuildWorkflowIdentity;
pub use reproducibility::ReleaseReproducibilityReport;
pub use reproducibility::ReleaseReproducibilityReportInit;
pub use reproducibility::ReleaseReproducibilityReportLinkage;
pub use reproducibility::ReproducibilityArtifactComparison;
pub use reproducibility::ReproducibilityComparisonResult;
pub use reproducibility::ReproducibilityComparisonVerdict;
pub use reproducibility::ReproducibilityProofClass;
pub use reproducibility::canonical_release_reproducibility_report;
pub use reproducibility::release_reproducibility_report_canonical_bytes;
pub use reproducibility::release_reproducibility_report_digest_blake3;
pub use reproducibility::validate_release_reproducibility_report_artifact_names;
pub use reproducibility::validate_release_reproducibility_report_linkage;
