#define PACKAGE "coreutils"
#define PACKAGE_NAME "GNU coreutils"
#define GNU_PACKAGE "GNU coreutils"
#define PACKAGE_BUGREPORT "bug-coreutils@gnu.org"
#define PACKAGE_VERSION "5.0"
#define VERSION "5.0"
#define HAVE_LIMITS_H 1
#define HAVE_DECL_FREE 1
#define HAVE_DECL_MALLOC 1
#define HAVE_MALLOC 1
#define HAVE_STDLIB_H 1
#define HAVE_REALLOC 1
#define HAVE_DECL_REALLOC 1
#define HAVE_DECL_GETENV 1
#define HAVE_DIRENT_H 1
#define HAVE_DECL___FPENDING 0
#define STDC_HEADERS 1
#define HAVE_ALLOCA_H 1
#define HAVE_STRUCT_TIMESPEC 1
#define HAVE_STRING_H 1
#define HAVE_SYS_TIME_H 1
#define TIME_WITH_SYS_TIME 1
#define HAVE_STDINT_H 1
#define MB_LEN_MAX 16
#define LIBDIR "/stagex/lib/mes"
#define HAVE_DECL_WCWIDTH 0
#define HAVE_SYS_STAT_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_DECL_MEMCHR 1
#define HAVE_MEMORY_H 1
#define PENDING_OUTPUT_N_BYTES 1
#define CHAR_MIN 0
#define LOCALEDIR NULL
#define HAVE_FCNTL_H 1
#define EPERM 1
#define HAVE_DECL_STRTOUL 1
#define HAVE_DECL_STRTOULL 1
#define HAVE_DECL_STRTOL 1
#define HAVE_DECL_STRTOLL 1
#define HAVE_RMDIR 1
#define RMDIR_ERRNO_NOT_EMPTY 39
#define ENOTEMPTY 1
#define LSTAT_FOLLOWS_SLASHED_SYMLINK 1
#define HAVE_DECL_DIRFD 0
#define LC_TIME "C"
#define LC_COLLATE "C"
#define HAVE_GETCWD 1
#define my_strftime nstrftime
#define mkstemp rpl_mkstemp
#define DIR_TO_FD(Dir_p) -1
#define UTILS_OPEN_MAX 1000
#define major_t unsigned
#define minor_t unsigned
#define HAVE_UNISTD_H 1
#define HAVE_LOCALE_H 1
#define HAVE_SYS_TYPES_H 1
