//! Bootstrap logic: resolve Nix packages and generate seed.ncl.
//!
//! The resolution step is parameterized by a closure so tests can
//! supply a mock resolver instead of shelling out to nix-build.

use crate::errors::RunError;

/// Resolve packages to store paths using the given resolver function.
///
/// `resolve` takes a package name and returns its store path or an error.
pub fn resolve_packages<F>(
    packages: &[String],
    resolve: F,
) -> Result<Vec<(String, String)>, RunError>
where
    F: Fn(&str) -> Result<String, RunError>,
{
    let mut entries = Vec::new();
    for pkg in packages {
        let store_path = resolve(pkg)?;
        if store_path.is_empty() {
            return Err(RunError::Internal(format!("empty store path for {pkg}")));
        }
        entries.push((pkg.clone(), store_path));
    }
    Ok(entries)
}

/// Generate seed.ncl content from resolved (name, store_path) pairs.
pub fn generate_seed_ncl(entries: &[(String, String)]) -> String {
    let mut ncl = String::new();
    ncl.push_str("# Generated by `crunch bootstrap`\n");
    ncl.push_str("# Re-run to update paths after nixpkgs changes.\n");
    ncl.push_str("#\n");
    ncl.push_str("# Pin these paths as GC roots:\n");
    for (_, path) in entries {
        ncl.push_str(&format!(
            "#   nix-store --add-root /nix/var/nix/gcroots/crunch-seed -r {path}\n"
        ));
    }
    ncl.push_str("\nlet { StorePath, .. } = import \"contracts.ncl\" in\n\n{\n");

    for (name, path) in entries {
        let field = name.replace('-', "_");
        ncl.push_str(&format!(
            "  {field} | StorePath\n    | doc \"Store path for {name}\"\n    = \"{path}\",\n\n"
        ));
    }

    ncl.push_str("}\n");
    ncl
}

/// Resolve a package using nix-build, falling back to `nix build`.
pub fn nix_resolve(pkg: &str) -> Result<String, RunError> {
    use std::process::Command as Cmd;

    let result = Cmd::new("nix-build")
        .args(["<nixpkgs>", "-A", pkg, "--no-out-link"])
        .output();

    match result {
        Ok(out) if out.status.success() => {
            let path = String::from_utf8_lossy(&out.stdout).trim().to_string();
            if path.is_empty() {
                Err(RunError::Internal(format!("empty store path for {pkg}")))
            } else {
                Ok(path)
            }
        }
        _ => {
            let out = Cmd::new("nix")
                .args([
                    "build",
                    &format!("nixpkgs#{pkg}"),
                    "--no-link",
                    "--print-out-paths",
                ])
                .output()
                .map_err(|e| RunError::Internal(format!("failed to run nix: {e}")))?;

            if !out.status.success() {
                let stderr = String::from_utf8_lossy(&out.stderr);
                return Err(RunError::Internal(format!(
                    "failed to resolve {pkg}: {stderr}"
                )));
            }
            let path = String::from_utf8_lossy(&out.stdout).trim().to_string();
            if path.is_empty() {
                Err(RunError::Internal(format!("empty store path for {pkg}")))
            } else {
                Ok(path)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn mock_resolve_ok(pkg: &str) -> Result<String, RunError> {
        Ok(format!("/nix/store/aaaa-{pkg}"))
    }

    fn mock_resolve_fail(pkg: &str) -> Result<String, RunError> {
        Err(RunError::Internal(format!("package not found: {pkg}")))
    }

    fn mock_resolve_empty(_pkg: &str) -> Result<String, RunError> {
        Ok(String::new())
    }

    #[test]
    fn resolve_success() {
        let pkgs = vec!["bash".into(), "coreutils".into()];
        let entries = resolve_packages(&pkgs, mock_resolve_ok).unwrap();
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[0], ("bash".into(), "/nix/store/aaaa-bash".into()));
        assert_eq!(
            entries[1],
            ("coreutils".into(), "/nix/store/aaaa-coreutils".into())
        );
    }

    #[test]
    fn resolve_failure_reports_package() {
        let pkgs = vec!["bash".into(), "nonexistent".into()];
        let err = resolve_packages(&pkgs, mock_resolve_fail).unwrap_err();
        let msg = err.message().to_string();
        assert!(msg.contains("bash"), "error should name the package: {msg}");
    }

    #[test]
    fn resolve_empty_path_rejected() {
        let pkgs = vec!["bash".into()];
        let err = resolve_packages(&pkgs, mock_resolve_empty).unwrap_err();
        assert!(err.message().contains("empty store path"));
    }

    #[test]
    fn generate_seed_valid_structure() {
        let entries = vec![
            ("bash".into(), "/nix/store/aaaa-bash".into()),
            ("gcc".into(), "/nix/store/bbbb-gcc".into()),
        ];
        let ncl = generate_seed_ncl(&entries);

        // Header
        assert!(ncl.starts_with("# Generated by `crunch bootstrap`\n"));

        // Contains import
        assert!(ncl.contains("import \"contracts.ncl\""));

        // Contains both entries with correct field names and paths
        assert!(ncl.contains("bash | StorePath"));
        assert!(ncl.contains("\"/nix/store/aaaa-bash\""));
        assert!(ncl.contains("gcc | StorePath"));
        assert!(ncl.contains("\"/nix/store/bbbb-gcc\""));

        // GC root comments
        assert!(ncl.contains("nix-store --add-root"));

        // Ends with closing brace
        assert!(ncl.trim_end().ends_with('}'));
    }

    #[test]
    fn generate_seed_sanitizes_hyphens() {
        let entries = vec![("my-cool-pkg".into(), "/nix/store/xxxx-my-cool-pkg".into())];
        let ncl = generate_seed_ncl(&entries);

        // Field name should use underscores
        assert!(ncl.contains("my_cool_pkg | StorePath"));
        // doc string keeps original name
        assert!(ncl.contains("\"Store path for my-cool-pkg\""));
    }

    #[test]
    fn generate_seed_empty_packages() {
        let entries: Vec<(String, String)> = vec![];
        let ncl = generate_seed_ncl(&entries);
        // Should still be valid — header + empty record
        assert!(ncl.contains("{\n}\n"));
    }
}
