//! Bootstrap logic: resolve Nix packages and generate seed.ncl.
//!
//! Two modes:
//! - `--from-nix` (default): shells out to `nix-build` to resolve
//!   package names to `/nix/store` paths.
//! - `--fetch`: downloads static toolchain tarballs, persists them
//!   as FODs in the crunch store, generates seed.ncl. No Nix required.
//!
//! The resolution step is parameterized by a closure so tests can
//! supply a mock resolver instead of shelling out to nix-build.

use std::path::Path;

use crate::errors::RunError;

/// Resolve packages to store paths using the given resolver function.
///
/// `resolve` takes a package name and returns its store path or an error.
pub fn resolve_packages<F>(
    packages: &[String],
    resolve: F,
) -> Result<Vec<(String, String)>, RunError>
where
    F: Fn(&str) -> Result<String, RunError>,
{
    let mut entries = Vec::new();
    for pkg in packages {
        let store_path = resolve(pkg)?;
        if store_path.is_empty() {
            return Err(RunError::Internal(format!("empty store path for {pkg}")));
        }
        entries.push((pkg.clone(), store_path));
    }
    Ok(entries)
}

/// Generate seed.ncl content from resolved (name, store_path) pairs.
pub fn generate_seed_ncl(entries: &[(String, String)]) -> String {
    let mut ncl = String::new();
    ncl.push_str("# Generated by `crunch bootstrap`\n");
    ncl.push_str("# Re-run to update paths after nixpkgs changes.\n");
    ncl.push_str("#\n");
    ncl.push_str("# Pin these paths as GC roots:\n");
    for (_, path) in entries {
        ncl.push_str(&format!(
            "#   nix-store --add-root /nix/var/nix/gcroots/crunch-seed -r {path}\n"
        ));
    }
    ncl.push_str("\nlet { StorePath, .. } = import \"contracts.ncl\" in\n\n{\n");

    for (name, path) in entries {
        let field = name.replace('-', "_");
        ncl.push_str(&format!(
            "  {field} | StorePath\n    | doc \"Store path for {name}\"\n    = \"{path}\",\n\n"
        ));
    }

    ncl.push_str("}\n");
    ncl
}

/// Resolve a package using nix-build, falling back to `nix build`.
pub fn nix_resolve(pkg: &str) -> Result<String, RunError> {
    use std::process::Command as Cmd;

    let result = Cmd::new("nix-build")
        .args(["<nixpkgs>", "-A", pkg, "--no-out-link"])
        .output();

    match result {
        Ok(out) if out.status.success() => {
            let path = String::from_utf8_lossy(&out.stdout).trim().to_string();
            if path.is_empty() {
                Err(RunError::Internal(format!("empty store path for {pkg}")))
            } else {
                Ok(path)
            }
        }
        _ => {
            let out = Cmd::new("nix")
                .args([
                    "build",
                    &format!("nixpkgs#{pkg}"),
                    "--no-link",
                    "--print-out-paths",
                ])
                .output()
                .map_err(|e| RunError::Internal(format!("failed to run nix: {e}")))?;

            if !out.status.success() {
                let stderr = String::from_utf8_lossy(&out.stderr);
                return Err(RunError::Internal(format!(
                    "failed to resolve {pkg}: {stderr}"
                )));
            }
            let path = String::from_utf8_lossy(&out.stdout).trim().to_string();
            if path.is_empty() {
                Err(RunError::Internal(format!("empty store path for {pkg}")))
            } else {
                Ok(path)
            }
        }
    }
}

// ── Fetch-based bootstrap ──────────────────────────────────────────────

/// Seed package definition for fetch-based bootstrap.
struct FetchSeed {
    /// Derivation name (used in store path computation).
    name: &'static str,
    /// URL to download.
    url: &'static str,
    /// SRI hash of the unpacked tarball (NAR hash, sha256).
    hash: &'static str,
    /// Field name in the generated seed.ncl.
    field: &'static str,
    /// Human-readable description for the doc annotation.
    doc: &'static str,
}

/// Pinned seed packages for the fetch-based bootstrap.
///
/// Each entry becomes a `fetchTarball` FOD in the crunch store.
/// Update hashes here when upgrading toolchain versions.
const FETCH_SEEDS: &[FetchSeed] = &[
    FetchSeed {
        name: "musl-gcc",
        url: "https://musl.cc/x86_64-linux-musl-native.tgz",
        hash: "sha256-XpcI34j9YwAQj7qw4DpvXqT1CX00vHcUQbAk/do46jw=",
        field: "gcc",
        doc: "Static musl-gcc toolchain (fetched from musl.cc)",
    },
];

/// The logical store prefix — must match orchestrate.rs.
const LOGICAL_STORE_DIR: &str = "/nix/store";

/// Build a `CrunchDerivation` for a fetchTarball FOD.
///
/// Mirrors what `crunch.fetchTarball { url, hash, name }` produces
/// in Nickel, but constructed directly in Rust.
fn make_fetch_derivation(seed: &FetchSeed) -> crunch_glue::CrunchDerivation {
    let mut env = std::collections::HashMap::new();
    env.insert("url".to_string(), seed.url.to_string());
    env.insert("unpack".to_string(), "1".to_string());

    crunch_glue::CrunchDerivation {
        name: seed.name.to_string(),
        builder: "builtin:fetchurl".to_string(),
        system: "x86_64-linux".to_string(),
        args: vec![],
        outputs: vec!["out".to_string()],
        env,
        inputs: vec![],
        fixed_output: Some(crunch_glue::FixedOutput {
            hash: seed.hash.to_string(),
            algo: "sha256".to_string(),
            mode: "recursive".to_string(),
        }),
        addressing_mode: "input-addressed".to_string(),
    }
}

/// Generate seed.ncl for fetch-based bootstrap.
///
/// Same format as `generate_seed_ncl` but with a different header
/// (no Nix GC root comments).
fn generate_fetch_seed_ncl(entries: &[(String, String, String)]) -> String {
    let mut ncl = String::new();
    ncl.push_str("# Generated by `crunch bootstrap --fetch`\n");
    ncl.push_str("# Seed packages fetched from pinned tarballs.\n");
    ncl.push_str("# No Nix dependency required.\n");
    ncl.push_str("\nlet { StorePath, .. } = import \"contracts.ncl\" in\n\n{\n");

    for (field, path, doc) in entries {
        ncl.push_str(&format!(
            "  {field} | StorePath\n    | doc \"{doc}\"\n    = \"{path}\",\n\n"
        ));
    }

    ncl.push_str("}\n");
    ncl
}

/// Resolve the crunch state directory (same logic as main.rs).
fn resolve_state_dir() -> std::path::PathBuf {
    std::env::var("CRUNCH_STATE_DIR")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|_| {
            let state = std::env::var("XDG_STATE_HOME")
                .map(std::path::PathBuf::from)
                .unwrap_or_else(|_| {
                    let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".to_string());
                    std::path::PathBuf::from(home).join(".local/state")
                });
            state.join("crunch")
        })
}

/// Download seed tarballs, persist as FODs, and generate seed.ncl.
///
/// This is the `crunch bootstrap --fetch` implementation. Sets up a
/// minimal Builder (fetchers don't need bwrap), runs each seed through
/// the fetch pipeline, and writes the resulting store paths to seed.ncl.
pub async fn bootstrap_fetch(
    store_dir: &Path,
    output: &Path,
    verbose: bool,
) -> Result<(), RunError> {
    use snix_castore::directoryservice::{RedbDirectoryService, RedbDirectoryServiceConfig};

    debug_assert!(!FETCH_SEEDS.is_empty(), "must have at least one seed package");

    eprintln!("Fetching {} seed package(s)...", FETCH_SEEDS.len());

    // 1. Convert all seeds to derivations, then bridge to registry.
    let mut cache = crunch_glue::ConversionCache::new(LOGICAL_STORE_DIR);
    let mut drv_paths = Vec::new();

    for seed in FETCH_SEEDS {
        let crunch_drv = make_fetch_derivation(seed);
        let (drv_path, nix_drv) = crunch_glue::convert(&crunch_drv, &mut cache)
            .map_err(|e| RunError::Build(format!("converting {}: {e}", seed.name)))?;

        let out_path = nix_drv.outputs.get("out")
            .and_then(|o| o.path.as_ref())
            .ok_or_else(|| RunError::Build(format!(
                "no output path for {}", seed.name
            )))?;

        eprintln!(
            "  {} -> {}",
            seed.name,
            out_path.to_absolute_path_with_prefix(
                store_dir.to_str().unwrap_or(LOGICAL_STORE_DIR)
            )
        );

        drv_paths.push((seed.field.to_string(), seed.doc.to_string(), drv_path));
    }

    // 2. Set up services for the Builder.
    let state_dir = resolve_state_dir();
    let _ = std::fs::create_dir_all(&state_dir);

    let blob_service = {
        use snix_castore::blobservice::ObjectStoreBlobService;
        let blob_dir = state_dir.join("blobs");
        std::fs::create_dir_all(&blob_dir)
            .map_err(|e| RunError::Internal(format!("creating blob dir: {e}")))?;
        std::sync::Arc::new(
            ObjectStoreBlobService::new_local(&blob_dir)
                .map_err(|e| RunError::Internal(format!("blob service: {e}")))?
        )
    };
    let directory_service = RedbDirectoryService::new_temporary(
        "bootstrap".to_string(),
        RedbDirectoryServiceConfig {
            path: None,
            read_only: false,
            cache_size: None,
        },
    )
    .map_err(|e| RunError::Internal(format!("directory service: {e}")))?;

    let pathinfo_service = open_bootstrap_pathinfo(&state_dir).await?;

    // Fetchers bypass bwrap entirely, so a dummy workdir is fine.
    #[cfg(target_os = "linux")]
    let build_service = {
        use snix_build::buildservice::BubblewrapBuildService;
        let workdir = std::env::temp_dir().join("crunch-bootstrap");
        let _ = std::fs::create_dir_all(&workdir);
        BubblewrapBuildService::new(
            workdir,
            blob_service.clone(),
            directory_service.clone(),
        )
    };

    #[cfg(not(target_os = "linux"))]
    return Err(RunError::Internal(
        "fetch bootstrap requires Linux (bwrap build service)".to_string(),
    ));

    #[cfg(target_os = "linux")]
    {
        let mut builder = crunch_build::Builder::with_state_dir(
            blob_service as std::sync::Arc<dyn snix_castore::blobservice::BlobService>,
            std::sync::Arc::new(directory_service) as std::sync::Arc<dyn snix_castore::directoryservice::DirectoryService>,
            build_service,
            std::sync::Arc::new(pathinfo_service) as std::sync::Arc<dyn snix_store::pathinfoservice::PathInfoService>,
            store_dir.to_path_buf(),
            Some(state_dir),
            None, // no remote substitution for bootstrap
            verbose,
        );

        // 3. Bridge conversion cache to build registry, then build.
        let mut known_paths = crunch_build::DerivationRegistry::new(LOGICAL_STORE_DIR);
        crunch_build::populate_registry(&mut known_paths, cache.iter_entries());

        let root_paths: Vec<nix_compat::store_path::StorePath<String>> =
            drv_paths.iter().map(|(_, _, sp)| sp.clone()).collect();

        let outcomes = builder
            .build_all(&root_paths, &mut known_paths, 1)
            .await
            .map_err(|e| RunError::Build(format!("fetching seeds: {e}")))?;

        // 4. Collect output paths.
        let store_prefix = store_dir.to_str().unwrap_or(LOGICAL_STORE_DIR);
        let mut entries: Vec<(String, String, String)> = Vec::new();

        for (i, outcome) in outcomes.iter().enumerate() {
            let (field, doc, _) = &drv_paths[i];
            let out_info = outcome.outputs.get("out").ok_or_else(|| {
                RunError::Build("seed fetch produced no 'out' output".to_string())
            })?;
            // seed.ncl always uses the logical prefix.
            let logical_path = out_info
                .store_path
                .to_absolute_path_with_prefix(LOGICAL_STORE_DIR);
            let display_path = out_info
                .store_path
                .to_absolute_path_with_prefix(store_prefix);

            if outcome.cached {
                eprintln!("  {} (cached)", display_path);
            } else {
                eprintln!("  {} (fetched)", display_path);
            }

            entries.push((field.clone(), logical_path, doc.clone()));
        }

        // 5. Generate seed.ncl.
        let ncl = generate_fetch_seed_ncl(&entries);
        std::fs::write(output, &ncl)
            .map_err(|e| RunError::Internal(format!(
                "writing {}: {e}", output.display()
            )))?;

        eprintln!("Wrote {}", output.display());
    }

    Ok(())
}

/// Open PathInfo database for bootstrap (reused from main).
async fn open_bootstrap_pathinfo(
    state_dir: &Path,
) -> Result<snix_store::pathinfoservice::RedbPathInfoService, RunError> {
    use snix_store::pathinfoservice::{RedbPathInfoService, RedbPathInfoServiceConfig};

    let db_path = state_dir.join("pathinfo.redb");
    match RedbPathInfoService::new(
        "crunch".to_string(),
        RedbPathInfoServiceConfig {
            path: Some(db_path.clone()),
            read_only: false,
            cache_size: None,
        },
    )
    .await
    {
        Ok(svc) => Ok(svc),
        Err(e) => {
            tracing::warn!(
                path = %db_path.display(),
                err = %e,
                "failed to open PathInfo database, using in-memory fallback"
            );
            RedbPathInfoService::new_temporary(
                "crunch".to_string(),
                RedbPathInfoServiceConfig::default(),
            )
            .map_err(|e| RunError::Internal(format!("in-memory PathInfo: {e}")))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn mock_resolve_ok(pkg: &str) -> Result<String, RunError> {
        Ok(format!("/nix/store/aaaa-{pkg}"))
    }

    fn mock_resolve_fail(pkg: &str) -> Result<String, RunError> {
        Err(RunError::Internal(format!("package not found: {pkg}")))
    }

    fn mock_resolve_empty(_pkg: &str) -> Result<String, RunError> {
        Ok(String::new())
    }

    #[test]
    fn resolve_success() {
        let pkgs = vec!["bash".into(), "coreutils".into()];
        let entries = resolve_packages(&pkgs, mock_resolve_ok).unwrap();
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[0], ("bash".into(), "/nix/store/aaaa-bash".into()));
        assert_eq!(
            entries[1],
            ("coreutils".into(), "/nix/store/aaaa-coreutils".into())
        );
    }

    #[test]
    fn resolve_failure_reports_package() {
        let pkgs = vec!["bash".into(), "nonexistent".into()];
        let err = resolve_packages(&pkgs, mock_resolve_fail).unwrap_err();
        let msg = err.message().to_string();
        assert!(msg.contains("bash"), "error should name the package: {msg}");
    }

    #[test]
    fn resolve_empty_path_rejected() {
        let pkgs = vec!["bash".into()];
        let err = resolve_packages(&pkgs, mock_resolve_empty).unwrap_err();
        assert!(err.message().contains("empty store path"));
    }

    #[test]
    fn generate_seed_valid_structure() {
        let entries = vec![
            ("bash".into(), "/nix/store/aaaa-bash".into()),
            ("gcc".into(), "/nix/store/bbbb-gcc".into()),
        ];
        let ncl = generate_seed_ncl(&entries);

        // Header
        assert!(ncl.starts_with("# Generated by `crunch bootstrap`\n"));

        // Contains import
        assert!(ncl.contains("import \"contracts.ncl\""));

        // Contains both entries with correct field names and paths
        assert!(ncl.contains("bash | StorePath"));
        assert!(ncl.contains("\"/nix/store/aaaa-bash\""));
        assert!(ncl.contains("gcc | StorePath"));
        assert!(ncl.contains("\"/nix/store/bbbb-gcc\""));

        // GC root comments
        assert!(ncl.contains("nix-store --add-root"));

        // Ends with closing brace
        assert!(ncl.trim_end().ends_with('}'));
    }

    #[test]
    fn generate_seed_sanitizes_hyphens() {
        let entries = vec![("my-cool-pkg".into(), "/nix/store/xxxx-my-cool-pkg".into())];
        let ncl = generate_seed_ncl(&entries);

        // Field name should use underscores
        assert!(ncl.contains("my_cool_pkg | StorePath"));
        // doc string keeps original name
        assert!(ncl.contains("\"Store path for my-cool-pkg\""));
    }

    #[test]
    fn generate_seed_empty_packages() {
        let entries: Vec<(String, String)> = vec![];
        let ncl = generate_seed_ncl(&entries);
        // Should still be valid — header + empty record
        assert!(ncl.contains("{\n}\n"));
    }

    // -- Fetch bootstrap tests --

    #[test]
    fn fetch_seeds_non_empty() {
        assert!(!FETCH_SEEDS.is_empty(), "must have at least one seed");
    }

    #[test]
    fn fetch_seed_musl_gcc_pinned() {
        let gcc = FETCH_SEEDS.iter().find(|s| s.field == "gcc").unwrap();
        assert_eq!(gcc.name, "musl-gcc");
        assert!(gcc.url.contains("musl.cc"));
        assert!(gcc.hash.starts_with("sha256-"));
    }

    #[test]
    fn make_fetch_derivation_structure() {
        let seed = &FETCH_SEEDS[0];
        let drv = make_fetch_derivation(seed);

        assert_eq!(drv.name, seed.name);
        assert_eq!(drv.builder, "builtin:fetchurl");
        assert_eq!(drv.system, "x86_64-linux");
        assert_eq!(drv.outputs, vec!["out".to_string()]);
        assert_eq!(drv.env.get("url").unwrap(), seed.url);
        assert_eq!(drv.env.get("unpack").unwrap(), "1");
        assert!(drv.inputs.is_empty());
        assert_eq!(drv.addressing_mode, "input-addressed");

        let fo = drv.fixed_output.as_ref().unwrap();
        assert_eq!(fo.hash, seed.hash);
        assert_eq!(fo.algo, "sha256");
        assert_eq!(fo.mode, "recursive");
    }

    #[test]
    fn make_fetch_derivation_converts_to_fod() {
        let seed = &FETCH_SEEDS[0];
        let drv = make_fetch_derivation(seed);
        let mut kp = crunch_glue::ConversionCache::new(LOGICAL_STORE_DIR);

        let (drv_path, nix_drv) = crunch_glue::convert(&drv, &mut kp).unwrap();

        // FOD: drv path has .drv suffix
        assert!(
            drv_path.to_absolute_path().ends_with("-musl-gcc.drv"),
            "drv path: {}", drv_path.to_absolute_path()
        );

        // FOD: output path is deterministic (from declared hash)
        let out = nix_drv.outputs.get("out").unwrap();
        assert!(out.path.is_some(), "FOD must have output path");
        assert!(out.ca_hash.is_some(), "FOD must have ca_hash");

        // Output path is a valid store path
        let out_path = out.path.as_ref().unwrap();
        assert!(
            out_path.to_absolute_path().starts_with("/nix/store/"),
            "output path must be in store: {}",
            out_path.to_absolute_path()
        );
        assert!(
            out_path.to_absolute_path().ends_with("-musl-gcc"),
            "output path must end with -musl-gcc: {}",
            out_path.to_absolute_path()
        );
    }

    #[test]
    fn make_fetch_derivation_same_hash_same_path() {
        // Reproducibility: same hash → same output path.
        let seed = &FETCH_SEEDS[0];
        let drv1 = make_fetch_derivation(seed);
        let drv2 = make_fetch_derivation(seed);

        let mut kp1 = crunch_glue::ConversionCache::new(LOGICAL_STORE_DIR);
        let mut kp2 = crunch_glue::ConversionCache::new(LOGICAL_STORE_DIR);

        let (_, nix1) = crunch_glue::convert(&drv1, &mut kp1).unwrap();
        let (_, nix2) = crunch_glue::convert(&drv2, &mut kp2).unwrap();

        let path1 = nix1.outputs["out"].path.as_ref().unwrap();
        let path2 = nix2.outputs["out"].path.as_ref().unwrap();
        assert_eq!(path1, path2);
    }

    #[test]
    fn generate_fetch_seed_ncl_structure() {
        let entries = vec![
            ("gcc".into(), "/nix/store/xxx-musl-gcc".into(), "Static musl-gcc".into()),
        ];
        let ncl = generate_fetch_seed_ncl(&entries);

        assert!(ncl.starts_with("# Generated by `crunch bootstrap --fetch`\n"));
        assert!(ncl.contains("No Nix dependency"));
        assert!(ncl.contains("import \"contracts.ncl\""));
        assert!(ncl.contains("gcc | StorePath"));
        assert!(ncl.contains("\"/nix/store/xxx-musl-gcc\""));
        assert!(ncl.contains("Static musl-gcc"));
        // No GC root comments (unlike the Nix-based seed)
        assert!(!ncl.contains("nix-store --add-root"));
        assert!(ncl.trim_end().ends_with('}'));
    }

    #[test]
    fn generate_fetch_seed_ncl_empty() {
        let entries: Vec<(String, String, String)> = vec![];
        let ncl = generate_fetch_seed_ncl(&entries);
        assert!(ncl.contains("{\n}\n"));
    }
}
