//! Bootstrap logic: resolve Nix packages and generate seed.ncl.
//!
//! Two modes:
//! - `--from-nix` (default): shells out to `nix-build` to resolve package names to `/nix/store`
//!   paths.
//! - `--fetch`: evaluates the explicit legacy compatibility provider in
//!   `bootstrap/seed-legacy.ncl`, builds its normalized seed derivation, and writes a generated
//!   `seed.ncl`. The selected self-build provider remains `bootstrap/seed.ncl`.
//!
//! The resolution step is parameterized by a closure so tests can
//! supply a mock resolver instead of shelling out to nix-build.

use std::ffi::OsString;
use std::path::Path;
use std::path::PathBuf;

use serde::Deserialize;

use crate::errors::RunError;

const MAX_SOURCE_TREE_SEARCH_ANCESTORS: usize = 12;
const MAX_REDUCTION_PERMISSION_ENTRIES: usize = 65_536;
#[cfg(unix)]
const UNIX_OWNER_DIRECTORY_ACCESS_MODE: u32 = 0o700;

/// Resolve packages to store paths using the given resolver function.
///
/// `resolve` takes a package name and returns its store path or an error.
pub fn resolve_packages<F>(packages: &[String], resolve: F) -> Result<Vec<(String, String)>, RunError>
where F: Fn(&str) -> Result<String, RunError> {
    let mut entries = Vec::with_capacity(packages.len());
    for pkg in packages {
        let store_path = resolve(pkg)?;
        if store_path.is_empty() {
            return Err(RunError::Internal(format!("empty store path for {pkg}")));
        }
        entries.push((pkg.clone(), store_path));
    }
    Ok(entries)
}

/// Generate seed.ncl content from resolved (name, store_path) pairs.
pub fn generate_seed_ncl(entries: &[(String, String)]) -> String {
    let mut ncl = String::new();
    ncl.push_str("# Generated by `crunch bootstrap`\n");
    ncl.push_str("# Re-run to update paths after nixpkgs changes.\n");
    ncl.push_str("#\n");
    ncl.push_str("# Pin these paths as GC roots:\n");
    for (_, path) in entries {
        ncl.push_str(&format!("#   nix-store --add-root /nix/var/nix/gcroots/crunch-seed -r {path}\n"));
    }
    ncl.push_str("\nlet { StorePath, .. } = import \"contracts.ncl\" in\n\n{\n");

    for (name, path) in entries {
        let field = name.replace('-', "_");
        ncl.push_str(&format!("  {field} | StorePath\n    | doc \"Store path for {name}\"\n    = \"{path}\",\n\n"));
    }

    ncl.push_str("}\n");
    ncl
}

/// Resolve a package using nix-build, falling back to `nix build`.
pub fn nix_resolve(pkg: &str) -> Result<String, RunError> {
    use std::process::Command as Cmd;
    debug_assert!(!pkg.is_empty());
    debug_assert!(!pkg.contains('/'));

    let result = Cmd::new("nix-build").args(["<nixpkgs>", "-A", pkg, "--no-out-link"]).output();

    match result {
        Ok(out) if out.status.success() => {
            let path = String::from_utf8_lossy(&out.stdout).trim().to_string();
            if path.is_empty() {
                Err(RunError::Internal(format!("empty store path for {pkg}")))
            } else {
                Ok(path)
            }
        }
        _ => {
            let out = Cmd::new("nix")
                .args(["build", &format!("nixpkgs#{pkg}"), "--no-link", "--print-out-paths"])
                .output()
                .map_err(|e| RunError::Internal(format!("failed to run nix: {e}")))?;

            if !out.status.success() {
                let stderr = String::from_utf8_lossy(&out.stderr);
                return Err(RunError::Internal(format!("failed to resolve {pkg}: {stderr}")));
            }
            let path = String::from_utf8_lossy(&out.stdout).trim().to_string();
            if path.is_empty() {
                Err(RunError::Internal(format!("empty store path for {pkg}")))
            } else {
                Ok(path)
            }
        }
    }
}

// ── Fetch-based bootstrap ──────────────────────────────────────────────

/// The logical store prefix — must match orchestrate.rs.
const LOGICAL_STORE_DIR: &str = "/crunch/store";
const SOURCE_ROOT_PROVIDER_TARGET: &str = "x86_64-linux-musl";
const SOURCE_ROOT_PROVIDER_DYNAMIC_LINKER: &str = "ld-musl-x86_64.so.1";
const REDUCED_BINUTILS_TOOLS: &[&str] = &[
    "addr2line",
    "ar",
    "as",
    "c++filt",
    "elfedit",
    "ld",
    "ld.bfd",
    "nm",
    "objcopy",
    "objdump",
    "ranlib",
    "readelf",
    "size",
    "strings",
    "strip",
];
const DROPPED_BIN_NAMES: &[&str] = &[
    "lto-dump",
    "gcov",
    "gcov-dump",
    "gcov-tool",
    "x86_64-linux-musl-gfortran",
    "gfortran",
    "ld.gold",
    "x86_64-linux-musl-ld.gold",
    "dwp",
    "x86_64-linux-musl-dwp",
    "gprof",
    "x86_64-linux-musl-gprof",
];
const DROPPED_LIB_NAMES: &[&str] = &[
    "libgfortran.a",
    "libgfortran.so",
    "libgfortran.so.5",
    "libgfortran.so.5.0.0",
];
const DROPPED_GCC_INTERNAL_NAMES: &[&str] = &["f951", "lto1", "lto-wrapper", "g++-mapper-server"];

#[derive(Debug, Clone, Deserialize)]
struct FetchSeedRawArtifact {
    name: String,
    url: String,
    hash: String,
}

#[derive(Debug, Clone, Deserialize)]
struct FetchSeedProviderMetadata {
    id: String,
    summary: String,
    raw: FetchSeedRawArtifact,
    retained_tools: Vec<String>,
    dropped_components: Vec<String>,
    notes: Vec<String>,
}

#[derive(Debug, Clone, Deserialize)]
struct FetchSeedProvider {
    name: String,
    target: String,
    dynamic_linker: String,
    toolchain: crunch_glue::CrunchDerivation,
    provider: FetchSeedProviderMetadata,
}

fn make_raw_fetch_derivation(raw: &FetchSeedRawArtifact) -> crunch_glue::CrunchDerivation {
    debug_assert!(!raw.url.is_empty());
    debug_assert!(!raw.hash.is_empty());
    let mut env = std::collections::HashMap::new();
    env.insert("url".to_string(), raw.url.clone());
    env.insert("unpack".to_string(), "1".to_string());

    crunch_glue::CrunchDerivation {
        name: raw.name.clone(),
        builder: "builtin:fetchurl".to_string(),
        system: "x86_64-linux".to_string(),
        args: vec![],
        outputs: vec!["out".to_string()],
        dynamic_plan_outputs: vec![],
        env,
        inputs: vec![],
        fixed_output: Some(crunch_glue::FixedOutput {
            hash: raw.hash.clone(),
            algo: "sha256".to_string(),
            mode: "recursive".to_string(),
        }),
        addressing_mode: "input-addressed".to_string(),
        provenance: None,
    }
}

fn source_tree_file_candidates(current_dir: Option<&Path>, relative_path: &Path) -> Vec<PathBuf> {
    assert!(relative_path.is_relative(), "source-tree file path must be relative");
    let mut candidates = Vec::new();
    if let Some(dir) = current_dir {
        for ancestor in dir.ancestors().take(MAX_SOURCE_TREE_SEARCH_ANCESTORS) {
            candidates.push(ancestor.join(relative_path));
        }
    }
    candidates
}

fn find_source_tree_file(current_dir: Option<&Path>, relative_path: &Path) -> Option<PathBuf> {
    source_tree_file_candidates(current_dir, relative_path)
        .into_iter()
        .find(|candidate| candidate.is_file())
}

fn fetch_seed_provider_path() -> PathBuf {
    let relative_path = Path::new("bootstrap").join("seed-legacy.ncl");
    let current_dir = std::env::current_dir().ok();
    find_source_tree_file(current_dir.as_deref(), &relative_path).unwrap_or(relative_path)
}

fn nickel_search_entries() -> Result<Vec<OsString>, RunError> {
    let stdlib = crunch_eval::stdlib::stdlib_import_path()
        .map_err(|e| RunError::Internal(format!("resolving stdlib import path: {e}")))?;
    Ok(vec![stdlib.into_os_string()])
}

fn validate_fetch_seed_provider(provider: &FetchSeedProvider) -> Result<(), RunError> {
    debug_assert!(!provider.target.is_empty());
    debug_assert!(!provider.provider.id.is_empty());
    if provider.name.is_empty() {
        return Err(RunError::Internal("bootstrap seed provider name is empty".to_string()));
    }
    if provider.target.is_empty() {
        return Err(RunError::Internal("bootstrap seed provider target is empty".to_string()));
    }
    if provider.dynamic_linker.is_empty() {
        return Err(RunError::Internal("bootstrap seed provider dynamic linker is empty".to_string()));
    }
    if provider.toolchain.name != provider.name {
        return Err(RunError::Internal(format!(
            "bootstrap seed provider toolchain name mismatch: {} vs {}",
            provider.toolchain.name, provider.name
        )));
    }
    if provider.toolchain.inputs.is_empty() {
        return Err(RunError::Internal(
            "bootstrap seed provider toolchain must depend on the raw seed artifact".to_string(),
        ));
    }
    if provider.provider.id.is_empty() {
        return Err(RunError::Internal("bootstrap seed provider id is empty".to_string()));
    }
    if provider.provider.summary.is_empty() {
        return Err(RunError::Internal("bootstrap seed provider summary is empty".to_string()));
    }
    if provider.provider.raw.name.is_empty() {
        return Err(RunError::Internal("bootstrap seed provider raw artifact name is empty".to_string()));
    }
    if provider.provider.raw.url.is_empty() {
        return Err(RunError::Internal("bootstrap seed provider raw artifact url is empty".to_string()));
    }
    if provider.provider.raw.hash.is_empty() {
        return Err(RunError::Internal("bootstrap seed provider raw artifact hash is empty".to_string()));
    }
    if provider.provider.retained_tools.is_empty() {
        return Err(RunError::Internal("bootstrap seed provider retained tool list is empty".to_string()));
    }
    if provider.provider.dropped_components.is_empty() {
        return Err(RunError::Internal("bootstrap seed provider dropped component list is empty".to_string()));
    }
    if provider.provider.notes.is_empty() {
        return Err(RunError::Internal("bootstrap seed provider notes are empty".to_string()));
    }
    Ok(())
}

fn load_fetch_seed_provider() -> Result<FetchSeedProvider, RunError> {
    let path = fetch_seed_provider_path();
    let search = nickel_search_entries()?;
    let provider: FetchSeedProvider = crunch_eval::evaluate_and_deserialize(&path, &search)
        .map_err(|e| RunError::Eval(format!("loading {}: {e}", path.display())))?;
    validate_fetch_seed_provider(&provider)?;
    Ok(provider)
}

fn fetch_seed_metadata_logical_path(logical_store_path: &str) -> String {
    assert!(!logical_store_path.is_empty(), "logical store path must not be empty");
    format!("{logical_store_path}/share/crunch-bootstrap/provider.json")
}

fn provider_comment_lines(provider: &FetchSeedProvider, metadata_path: &str) -> Vec<String> {
    assert!(!metadata_path.is_empty(), "metadata path must not be empty");
    assert!(!provider.provider.id.is_empty(), "provider id must not be empty");

    let dropped = provider.provider.dropped_components.join(", ");
    let retained = provider.provider.retained_tools.join(", ");

    vec![
        "Generated by `crunch bootstrap --fetch`".to_string(),
        format!("Provider: {} — {}", provider.provider.id, provider.provider.summary),
        format!("Target: {} ({})", provider.target, provider.dynamic_linker),
        format!("Raw artifact: {} ({})", provider.provider.raw.url, provider.provider.raw.hash),
        format!("Retained tools: {retained}"),
        format!("Dropped surface: {dropped}"),
        format!("Metadata: {metadata_path}"),
        "No Nix dependency required.".to_string(),
    ]
}

fn fetch_seed_entries(provider: &FetchSeedProvider, logical_store_path: &str) -> Vec<(String, String, String)> {
    assert!(!logical_store_path.is_empty(), "logical store path must not be empty");
    assert!(!provider.provider.summary.is_empty(), "provider summary must not be empty");

    let toolchain_doc = format!("{} ({})", provider.provider.summary, provider.provider.id);
    let alias_doc = format!("Compatibility alias for {} — prefer seed.toolchain in new code", provider.provider.id);

    vec![
        ("toolchain".to_string(), logical_store_path.to_string(), toolchain_doc),
        ("gcc".to_string(), logical_store_path.to_string(), alias_doc),
    ]
}

fn generate_fetch_seed_ncl(provider: &FetchSeedProvider, logical_store_path: &str) -> String {
    let metadata_path = fetch_seed_metadata_logical_path(logical_store_path);
    let comment_lines = provider_comment_lines(provider, &metadata_path);
    let entries = fetch_seed_entries(provider, logical_store_path);

    generate_seed_contract_ncl(comment_lines, entries)
}

struct SourceRootSeedNclInput<'a> {
    logical_store_path: &'a str,
    manifest_digest: &'a str,
    output_digest: &'a str,
}

pub fn generate_source_root_seed_ncl(
    logical_store_path: impl AsRef<str>,
    manifest_digest: impl std::fmt::Display,
    output_digest: impl AsRef<str>,
) -> String {
    let manifest_digest = manifest_digest.to_string();
    generate_source_root_seed_ncl_from_input(SourceRootSeedNclInput {
        logical_store_path: logical_store_path.as_ref(),
        manifest_digest: &manifest_digest,
        output_digest: output_digest.as_ref(),
    })
}

fn generate_source_root_seed_ncl_from_input(input: SourceRootSeedNclInput<'_>) -> String {
    assert!(!input.logical_store_path.is_empty(), "logical store path must not be empty");
    assert!(!input.manifest_digest.is_empty(), "manifest digest must not be empty");
    assert!(!input.output_digest.is_empty(), "output digest must not be empty");

    let metadata_path = fetch_seed_metadata_logical_path(input.logical_store_path);
    let comment_lines = vec![
        "Generated by `mantle bootstrap --source-root`".to_string(),
        "Provider: source-root-v1 — normalized host-assisted source materialization (not a full-source bootstrap)"
            .to_string(),
        format!("Target: {} ({})", SOURCE_ROOT_PROVIDER_TARGET, SOURCE_ROOT_PROVIDER_DYNAMIC_LINKER),
        format!("Source-root manifest digest: blake3:{}", input.manifest_digest),
        format!("Provider output digest: blake3:{}", input.output_digest),
        format!("Metadata: {metadata_path}"),
        "No legacy musl.cc binary toolchain tarball was used.".to_string(),
    ];
    let toolchain_doc = format!("source-root-v1 normalized {} provider", SOURCE_ROOT_PROVIDER_TARGET);
    let alias_doc = "Compatibility alias for source-root-v1 — prefer seed.toolchain in new code".to_string();
    let entries = vec![
        ("toolchain".to_string(), input.logical_store_path.to_string(), toolchain_doc),
        ("gcc".to_string(), input.logical_store_path.to_string(), alias_doc),
    ];

    generate_seed_contract_ncl(comment_lines, entries)
}

fn generate_seed_contract_ncl(comment_lines: Vec<String>, entries: Vec<(String, String, String)>) -> String {
    assert!(!comment_lines.is_empty(), "seed contract comments must not be empty");
    assert!(!entries.is_empty(), "seed contract entries must not be empty");

    let mut ncl = String::new();
    for line in comment_lines {
        ncl.push_str("# ");
        ncl.push_str(&line);
        ncl.push('\n');
    }
    ncl.push_str("\nlet { StorePath, .. } = import \"contracts.ncl\" in\n\n{\n");

    for (field, path, doc) in entries {
        ncl.push_str(&format!("  {field} | StorePath\n    | doc \"{doc}\"\n    = \"{path}\",\n\n"));
    }

    ncl.push_str("}\n");
    ncl
}

fn reduced_seed_store_name(provider: &FetchSeedProvider) -> Result<String, RunError> {
    if provider.name.is_empty() {
        return Err(RunError::Internal("bootstrap seed provider name is empty".to_string()));
    }
    if provider.provider.id.is_empty() {
        return Err(RunError::Internal("bootstrap seed provider id is empty".to_string()));
    }

    let fingerprint = format!(
        "{}\n{}\n{}\n{}",
        provider.provider.id, provider.name, provider.provider.raw.url, provider.provider.raw.hash
    );
    let digest = blake3::hash(fingerprint.as_bytes());
    let hash_part = nix_compat::nixbase32::encode(&digest.as_bytes()[..20]);
    Ok(format!("{hash_part}-{}", provider.name))
}

fn copy_symlink(src: &Path, dst: &Path) -> Result<(), RunError> {
    let target =
        std::fs::read_link(src).map_err(|e| RunError::Internal(format!("reading symlink {}: {e}", src.display())))?;
    if let Some(parent) = dst.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| RunError::Internal(format!("creating {}: {e}", parent.display())))?;
    }
    remove_path_if_exists(dst)?;
    #[cfg(unix)]
    {
        std::os::unix::fs::symlink(&target, dst)
            .map_err(|e| RunError::Internal(format!("creating symlink {}: {e}", dst.display())))?;
    }
    #[cfg(not(unix))]
    {
        return Err(RunError::Internal(format!("symlink copy is only supported on unix hosts: {}", src.display())));
    }
    Ok(())
}

#[allow(tigerstyle::no_recursion)] // filesystem tree walk bounded by actual directory depth
fn copy_path_recursively(src: &Path, dst: &Path) -> Result<(), RunError> {
    debug_assert!(src.is_absolute() || !src.as_os_str().is_empty());
    debug_assert!(dst.is_absolute() || !dst.as_os_str().is_empty());
    let metadata =
        std::fs::symlink_metadata(src).map_err(|e| RunError::Internal(format!("stat {}: {e}", src.display())))?;
    let file_type = metadata.file_type();

    if file_type.is_symlink() {
        return copy_symlink(src, dst);
    }
    if file_type.is_file() {
        if let Some(parent) = dst.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| RunError::Internal(format!("creating {}: {e}", parent.display())))?;
        }
        remove_path_if_exists(dst)?;
        std::fs::copy(src, dst).map_err(|e| RunError::Internal(format!("copying {}: {e}", src.display())))?;
        std::fs::set_permissions(dst, metadata.permissions())
            .map_err(|e| RunError::Internal(format!("chmod {}: {e}", dst.display())))?;
        return Ok(());
    }

    std::fs::create_dir_all(dst).map_err(|e| RunError::Internal(format!("creating {}: {e}", dst.display())))?;
    for entry in std::fs::read_dir(src).map_err(|e| RunError::Internal(format!("reading {}: {e}", src.display())))? {
        let entry = entry.map_err(|e| RunError::Internal(format!("reading {}: {e}", src.display())))?;
        copy_path_recursively(&entry.path(), &dst.join(entry.file_name()))?;
    }
    std::fs::set_permissions(dst, metadata.permissions())
        .map_err(|e| RunError::Internal(format!("chmod {}: {e}", dst.display())))?;
    Ok(())
}

fn remove_path_if_exists(path: &Path) -> Result<(), RunError> {
    let metadata = match std::fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(e) => return Err(RunError::Internal(format!("stat {}: {e}", path.display()))),
    };

    if metadata.is_dir() && !metadata.file_type().is_symlink() {
        std::fs::remove_dir_all(path).map_err(|e| RunError::Internal(format!("removing {}: {e}", path.display())))?;
    } else {
        std::fs::remove_file(path).map_err(|e| RunError::Internal(format!("removing {}: {e}", path.display())))?;
    }
    Ok(())
}

#[allow(tigerstyle::no_recursion)] // filesystem tree walk bounded by actual directory depth
fn directory_size_bytes(path: &Path) -> Result<u64, RunError> {
    let metadata =
        std::fs::symlink_metadata(path).map_err(|e| RunError::Internal(format!("stat {}: {e}", path.display())))?;
    let file_type = metadata.file_type();
    if file_type.is_symlink() || file_type.is_file() {
        return Ok(metadata.len());
    }

    let mut total_bytes: u64 = 0;
    for entry in std::fs::read_dir(path).map_err(|e| RunError::Internal(format!("reading {}: {e}", path.display())))? {
        let entry = entry.map_err(|e| RunError::Internal(format!("reading {}: {e}", path.display())))?;
        total_bytes = total_bytes
            .checked_add(directory_size_bytes(&entry.path())?)
            .ok_or_else(|| RunError::Internal(format!("directory size overflow for {}", path.display())))?;
    }
    Ok(total_bytes)
}

fn copy_if_exists(src: &Path, dst: &Path) -> Result<(), RunError> {
    if src.exists() {
        copy_path_recursively(src, dst)?;
    }
    Ok(())
}

fn make_reduction_directories_writable(root: &Path) -> Result<(), RunError> {
    let mut pending = vec![root.to_path_buf()];
    for _ in 0..MAX_REDUCTION_PERMISSION_ENTRIES {
        let Some(directory) = pending.pop() else {
            assert!(pending.is_empty());
            assert!(root.is_dir());
            return Ok(());
        };
        let permissions = std::fs::symlink_metadata(&directory)
            .map_err(|err| RunError::Internal(format!("stat {}: {err}", directory.display())))?
            .permissions();
        let writable_permissions = reduction_directory_permissions(permissions);
        std::fs::set_permissions(&directory, writable_permissions)
            .map_err(|err| RunError::Internal(format!("chmod {}: {err}", directory.display())))?;
        for entry in std::fs::read_dir(&directory)
            .map_err(|err| RunError::Internal(format!("reading {}: {err}", directory.display())))?
        {
            let entry = entry.map_err(|err| RunError::Internal(format!("reading {}: {err}", directory.display())))?;
            let metadata = entry
                .file_type()
                .map_err(|err| RunError::Internal(format!("stat {}: {err}", entry.path().display())))?;
            if metadata.is_dir() && !metadata.is_symlink() {
                pending.push(entry.path());
            }
        }
    }
    Err(RunError::Internal(format!(
        "bootstrap reduction directory walk exceeds {MAX_REDUCTION_PERMISSION_ENTRIES} entries"
    )))
}

#[cfg(unix)]
fn reduction_directory_permissions(permissions: std::fs::Permissions) -> std::fs::Permissions {
    use std::os::unix::fs::PermissionsExt as _;

    let mode = permissions.mode() | UNIX_OWNER_DIRECTORY_ACCESS_MODE;
    assert_eq!(mode & UNIX_OWNER_DIRECTORY_ACCESS_MODE, UNIX_OWNER_DIRECTORY_ACCESS_MODE);
    if permissions.readonly() {
        assert_ne!(mode, permissions.mode());
    }
    std::fs::Permissions::from_mode(mode)
}

#[cfg(not(unix))]
fn reduction_directory_permissions(mut permissions: std::fs::Permissions) -> std::fs::Permissions {
    permissions.set_readonly(false);
    assert!(!permissions.readonly());
    permissions
}

fn stage_reduced_seed_provider(
    raw_root: &Path,
    stage_root: &Path,
    provider: &FetchSeedProvider,
) -> Result<(), RunError> {
    debug_assert!(raw_root.exists());
    debug_assert!(!provider.target.is_empty());
    let target_dir = stage_root.join(&provider.target);
    std::fs::create_dir_all(stage_root)
        .map_err(|e| RunError::Internal(format!("creating {}: {e}", stage_root.display())))?;
    std::fs::create_dir_all(stage_root.join("bin"))
        .map_err(|e| RunError::Internal(format!("creating {}: {e}", stage_root.join("bin").display())))?;
    std::fs::create_dir_all(&target_dir)
        .map_err(|e| RunError::Internal(format!("creating {}: {e}", target_dir.display())))?;
    std::fs::create_dir_all(target_dir.join("lib"))
        .map_err(|e| RunError::Internal(format!("creating {}: {e}", target_dir.join("lib").display())))?;

    copy_if_exists(&raw_root.join("include"), &stage_root.join("include"))?;
    copy_if_exists(&raw_root.join("lib"), &stage_root.join("lib"))?;
    copy_if_exists(&raw_root.join("libexec"), &stage_root.join("libexec"))?;
    copy_if_exists(&raw_root.join(&provider.target), &target_dir)?;
    make_reduction_directories_writable(stage_root)?;

    let raw_bin = raw_root.join("bin");
    if raw_bin.exists() {
        for entry in std::fs::read_dir(&raw_bin)
            .map_err(|e| RunError::Internal(format!("reading {}: {e}", raw_bin.display())))?
        {
            let entry = entry.map_err(|e| RunError::Internal(format!("reading {}: {e}", raw_bin.display())))?;
            let name = entry.file_name().to_string_lossy().to_string();
            let is_driver = name == format!("{}-gcc", provider.target)
                || name == format!("{}-g++", provider.target)
                || name == format!("{}-c++", provider.target)
                || name == format!("{}-cpp", provider.target)
                || name == format!("{}-gcc-ar", provider.target)
                || name == format!("{}-gcc-nm", provider.target)
                || name == format!("{}-gcc-ranlib", provider.target)
                || name.starts_with(&format!("{}-gcc-", provider.target));
            if is_driver {
                copy_path_recursively(&entry.path(), &stage_root.join("bin").join(&name))?;
            }
        }
    }

    let raw_target_bin = raw_root.join(&provider.target).join("bin");
    for tool in REDUCED_BINUTILS_TOOLS {
        let raw_candidate = raw_bin.join(tool);
        let target_candidate = raw_target_bin.join(tool);
        let source = if raw_candidate.exists() {
            raw_candidate
        } else {
            target_candidate
        };
        if source.exists() {
            copy_path_recursively(&source, &stage_root.join("bin").join(tool))?;
            copy_path_recursively(&source, &stage_root.join("bin").join(format!("{}-{}", provider.target, tool)))?;
        }
    }

    let normalized_include = target_dir.join("include");
    remove_path_if_exists(&normalized_include)?;
    if stage_root.join("include").exists() {
        copy_path_recursively(&stage_root.join("include"), &normalized_include)?;
    } else if target_dir.join("sys-include").exists() {
        copy_path_recursively(&target_dir.join("sys-include"), &normalized_include)?;
    }

    copy_runtime_libs(stage_root, &target_dir)?;
    strip_dropped_components(stage_root, &provider.target)
}

const RUNTIME_LIB_NAMES: &[&str] = &[
    "libgcc_s.so",
    "libgcc_s.so.1",
    "libc.so",
    "libstdc++.a",
    "libstdc++.so",
    "libstdc++.so.6",
    "libsupc++.a",
];

fn copy_runtime_libs(stage_root: &Path, target_dir: &Path) -> Result<(), RunError> {
    debug_assert!(stage_root.exists());
    debug_assert!(target_dir.exists());
    for lib_name in RUNTIME_LIB_NAMES {
        let src = stage_root.join("lib").join(lib_name);
        if src.exists() {
            copy_path_recursively(&src, &target_dir.join("lib").join(lib_name))?;
        }
    }
    Ok(())
}

fn strip_dropped_components(stage_root: &Path, target: &str) -> Result<(), RunError> {
    debug_assert!(!target.is_empty());
    debug_assert!(stage_root.exists());
    remove_path_if_exists(&stage_root.join("share"))?;
    for name in DROPPED_BIN_NAMES {
        remove_path_if_exists(&stage_root.join("bin").join(name))?;
    }
    for name in DROPPED_LIB_NAMES {
        remove_path_if_exists(&stage_root.join("lib").join(name))?;
    }

    let gcc_internal_root = stage_root.join("libexec").join("gcc").join(target);
    if gcc_internal_root.exists() {
        for entry in std::fs::read_dir(&gcc_internal_root)
            .map_err(|e| RunError::Internal(format!("reading {}: {e}", gcc_internal_root.display())))?
        {
            let entry =
                entry.map_err(|e| RunError::Internal(format!("reading {}: {e}", gcc_internal_root.display())))?;
            let version_dir = entry.path();
            remove_path_if_exists(&version_dir.join("install-tools"))?;
            for name in DROPPED_GCC_INTERNAL_NAMES {
                remove_path_if_exists(&version_dir.join(name))?;
            }
        }
    }

    Ok(())
}

fn write_provider_metadata(
    provider: &FetchSeedProvider,
    raw_root: &Path,
    stage_root: &Path,
    metadata_path: &Path,
) -> Result<(), RunError> {
    debug_assert!(!provider.provider.id.is_empty());
    debug_assert!(metadata_path.extension().is_some_and(|ext| ext == "json"));
    let raw_size_bytes = directory_size_bytes(raw_root)?;
    let reduced_size_bytes = directory_size_bytes(stage_root)?;
    if raw_size_bytes == 0 {
        return Err(RunError::Internal(format!("raw seed size is zero for {}", raw_root.display())));
    }
    if reduced_size_bytes == 0 {
        return Err(RunError::Internal(format!("reduced seed size is zero for {}", stage_root.display())));
    }
    if reduced_size_bytes >= raw_size_bytes {
        return Err(RunError::Internal(format!(
            "reduced seed provider is not smaller than raw input: {} >= {} bytes",
            reduced_size_bytes, raw_size_bytes
        )));
    }

    if let Some(parent) = metadata_path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| RunError::Internal(format!("creating {}: {e}", parent.display())))?;
    }

    let json = serde_json::json!({
        "provider_id": provider.provider.id,
        "name": provider.name,
        "target": provider.target,
        "dynamic_linker": provider.dynamic_linker,
        "raw": {
            "name": provider.provider.raw.name,
            "url": provider.provider.raw.url,
            "hash": provider.provider.raw.hash,
        },
        "reduction": {
            "raw_size_bytes": raw_size_bytes,
            "reduced_size_bytes": reduced_size_bytes,
            "retained_tools": provider.provider.retained_tools,
            "dropped_components": provider.provider.dropped_components,
        },
        "notes": provider.provider.notes,
    });

    let content = serde_json::to_string_pretty(&json)
        .map_err(|e| RunError::Internal(format!("serializing provider metadata: {e}")))?;
    std::fs::write(metadata_path, content)
        .map_err(|e| RunError::Internal(format!("writing {}: {e}", metadata_path.display())))?;
    Ok(())
}

fn validate_reduced_seed_output(path: &Path, provider: &FetchSeedProvider) -> Result<(), RunError> {
    let checks = [
        path.join("bin").join(format!("{}-gcc", provider.target)),
        path.join("bin").join(format!("{}-g++", provider.target)),
        path.join("bin").join(format!("{}-ar", provider.target)),
        path.join("bin").join(format!("{}-ld", provider.target)),
        path.join(&provider.target).join("lib").join("libgcc_s.so.1"),
        path.join(&provider.target).join("include"),
        path.join("share").join("crunch-bootstrap").join("provider.json"),
    ];

    for check in checks {
        if !check.exists() {
            return Err(RunError::Internal(format!("reduced seed provider missing {}", check.display())));
        }
    }
    Ok(())
}

fn materialize_reduced_seed_provider(
    provider: &FetchSeedProvider,
    raw_root: &Path,
    store_dir: &Path,
) -> Result<(String, String, bool), RunError> {
    debug_assert!(!provider.name.is_empty());
    debug_assert!(raw_root.exists(), "raw root must exist before reduction");
    let store_name = reduced_seed_store_name(provider)?;
    let logical_path = format!("{LOGICAL_STORE_DIR}/{store_name}");
    let physical_path = store_dir.join(&store_name);

    if physical_path.exists() {
        validate_reduced_seed_output(&physical_path, provider)?;
        return Ok((logical_path, physical_path.display().to_string(), true));
    }

    let staging_parent = tempfile::Builder::new()
        .prefix("crunch-seed-stage-")
        .tempdir_in(store_dir)
        .map_err(|e| RunError::Internal(format!("creating staging dir in {}: {e}", store_dir.display())))?;
    let staging_root = staging_parent.path().join(&store_name);

    stage_reduced_seed_provider(raw_root, &staging_root, provider)?;
    write_provider_metadata(
        provider,
        raw_root,
        &staging_root,
        &staging_root.join("share").join("crunch-bootstrap").join("provider.json"),
    )?;
    validate_reduced_seed_output(&staging_root, provider)?;

    std::fs::rename(&staging_root, &physical_path).map_err(|e| {
        RunError::Internal(format!("moving reduced seed provider into {}: {e}", physical_path.display()))
    })?;

    Ok((logical_path, physical_path.display().to_string(), false))
}

/// Resolve the crunch state directory (same logic as main.rs).
fn resolve_state_dir() -> PathBuf {
    std::env::var("CRUNCH_STATE_DIR").map(PathBuf::from).unwrap_or_else(|_| {
        let state = std::env::var("XDG_STATE_HOME").map(PathBuf::from).unwrap_or_else(|_| {
            let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".to_string());
            PathBuf::from(home).join(".local/state")
        });
        state.join("crunch")
    })
}

struct FetchRawSeedRequest<'a> {
    drv_path: &'a nix_compat::store_path::StorePath<String>,
    cache: &'a crunch_glue::ConversionCache,
    store_dir: &'a Path,
    is_verbose: bool,
    display_prefix: &'a str,
    source_fetch_overrides: Vec<crunch_build::FetchSourceOverride>,
}

async fn fetch_raw_seed(request: FetchRawSeedRequest<'_>) -> Result<String, RunError> {
    use snix_castore::directoryservice::RedbDirectoryService;
    use snix_castore::directoryservice::RedbDirectoryServiceConfig;
    debug_assert!(request.store_dir.is_absolute());
    debug_assert!(!request.display_prefix.is_empty());

    let state_dir = resolve_state_dir();
    let _mutation_guard = crunch_store::StoreMutationGuard::acquire_wait(&state_dir)
        .map_err(|e| RunError::Internal(format!("acquiring store mutation lock: {e}")))?;
    std::fs::create_dir_all(&state_dir)
        .map_err(|e| RunError::Internal(format!("creating state dir {}: {e}", state_dir.display())))?;

    let blob_service = {
        use snix_castore::blobservice::ObjectStoreBlobService;
        let blob_dir = state_dir.join("blobs");
        std::fs::create_dir_all(&blob_dir).map_err(|e| RunError::Internal(format!("creating blob dir: {e}")))?;
        std::sync::Arc::new(
            ObjectStoreBlobService::new_local(&blob_dir)
                .map_err(|e| RunError::Internal(format!("blob service: {e}")))?,
        )
    };
    let directory_service = RedbDirectoryService::new_temporary("bootstrap".to_string(), RedbDirectoryServiceConfig {
        path: None,
        read_only: false,
        cache_size: None,
    })
    .map_err(|e| RunError::Internal(format!("directory service: {e}")))?;

    let pathinfo_service = open_bootstrap_pathinfo(&state_dir).await?;
    let source_policy = if request.source_fetch_overrides.is_empty() {
        crunch_build::FetchSourcePolicy::AllowNetwork
    } else {
        crunch_build::FetchSourcePolicy::RequireOverride
    };
    let fetch_service = crunch_build::FetchBuildService::new(blob_service.clone(), directory_service.clone())
        .with_source_overrides(request.source_fetch_overrides)
        .with_source_policy(source_policy);

    let (bootstrap_keypair, _bootstrap_key_line) = crunch_build::generate_keypair();
    let bootstrap_trusted = crunch_build::build_trusted_keys(&bootstrap_keypair, None);

    let mut builder = crunch_build::Builder::with_state_dir(
        blob_service as std::sync::Arc<dyn snix_castore::blobservice::BlobService>,
        std::sync::Arc::new(directory_service) as std::sync::Arc<dyn snix_castore::directoryservice::DirectoryService>,
        fetch_service,
        std::sync::Arc::new(pathinfo_service) as std::sync::Arc<dyn snix_store::pathinfoservice::PathInfoService>,
        request.store_dir.to_path_buf(),
        Some(state_dir),
        None,
        LOGICAL_STORE_DIR,
        bootstrap_keypair,
        bootstrap_trusted,
        false,
        request.is_verbose,
    );
    builder.set_root_retention_source(Some(crunch_store::GcRootSource::Bootstrap));

    let mut known_paths = crunch_build::DerivationRegistry::new(LOGICAL_STORE_DIR);
    crunch_build::populate_registry(&mut known_paths, request.cache.iter_entries());

    let root_paths = vec![request.drv_path.clone()];
    let outcomes = builder
        .build_all(&root_paths, &mut known_paths, 1)
        .await
        .map_err(|e| RunError::Build(format!("fetching bootstrap raw seed: {e}")))?;

    let (raw_display_path, is_cached) = raw_seed_outcome_path(outcomes, request.display_prefix)?;
    if is_cached {
        eprintln!("  {} (cached)", raw_display_path);
    } else {
        eprintln!("  {} (fetched)", raw_display_path);
    }
    Ok(raw_display_path)
}

fn raw_seed_outcome_path(
    outcomes: Vec<crunch_build::BuildOutcome>,
    display_prefix: &str,
) -> Result<(String, bool), RunError> {
    let outcome = outcomes
        .into_iter()
        .next()
        .ok_or_else(|| RunError::Build("bootstrap raw seed fetch produced no outcomes".to_string()))?;
    let out_info = outcome
        .outputs
        .get("out")
        .ok_or_else(|| RunError::Build("bootstrap raw seed fetch produced no 'out' output".to_string()))?;
    let raw_display_path = out_info.store_path.to_absolute_path_with_prefix(display_prefix);
    Ok((raw_display_path, outcome.cached))
}

/// Return the pinned raw seed provider URL without fetching it.
pub fn fetch_seed_provider_raw_url() -> Result<String, RunError> {
    let provider = load_fetch_seed_provider()?;
    Ok(provider.provider.raw.url)
}

/// Download the shared bootstrap seed provider, persist it, and generate seed.ncl.
///
/// This is the explicit legacy-compatibility `mantle bootstrap --fetch`
/// implementation. It evaluates `bootstrap/seed-legacy.ncl`, fetches the pinned
/// raw tarball through the normal fixed-output pipeline, reduces that raw tree
/// on the host into the normalized provider shape, and writes a small generated
/// `seed.ncl` that points at the resulting store path. It never changes the
/// checked-in full-source selector.
pub async fn bootstrap_fetch(
    store_dir: &Path,
    output: &Path,
    is_verbose: bool,
    source_fetch_overrides: Vec<crunch_build::FetchSourceOverride>,
) -> Result<(), RunError> {
    debug_assert!(store_dir.is_absolute());
    debug_assert!(!output.as_os_str().is_empty());
    let provider = load_fetch_seed_provider()?;
    let raw_fetch = make_raw_fetch_derivation(&provider.provider.raw);

    eprintln!("Fetching bootstrap seed provider {}...", provider.provider.id);

    // 1. Convert the raw fetch derivation and download it through the normal fetch pipeline.
    let mut cache = crunch_glue::ConversionCache::new(LOGICAL_STORE_DIR);
    let (drv_path, nix_drv) = crunch_glue::convert(&raw_fetch, &mut cache)
        .map_err(|e| RunError::Build(format!("converting {}: {e}", raw_fetch.name)))?;

    let display_prefix = store_dir.to_str().unwrap_or(LOGICAL_STORE_DIR);
    if let Some(planned_output) = nix_drv.outputs.get("out").and_then(|o| o.path.as_ref()) {
        eprintln!("  raw {} -> {}", raw_fetch.name, planned_output.to_absolute_path_with_prefix(display_prefix));
    }

    // 2-3. Set up services, build the raw tarball, and extract its output path.
    let raw_display_path = fetch_raw_seed(FetchRawSeedRequest {
        drv_path: &drv_path,
        cache: &cache,
        store_dir,
        is_verbose,
        display_prefix,
        source_fetch_overrides,
    })
    .await?;

    // 4. Reduce the raw tree on the host into the normalized provider layout.
    let (logical_path, physical_path, reduced_cached) =
        materialize_reduced_seed_provider(&provider, Path::new(&raw_display_path), store_dir)?;
    if reduced_cached {
        eprintln!("  {} (reduced provider cached)", physical_path);
    } else {
        eprintln!("  {} (reduced provider built)", physical_path);
    }
    eprintln!("  provider metadata -> {}/share/crunch-bootstrap/provider.json", physical_path);

    // 5. Generate seed.ncl.
    let ncl = generate_fetch_seed_ncl(&provider, &logical_path);
    std::fs::write(output, &ncl).map_err(|e| RunError::Internal(format!("writing {}: {e}", output.display())))?;

    eprintln!("Wrote {}", output.display());
    Ok(())
}

/// Open PathInfo database for bootstrap (reused from main).
async fn open_bootstrap_pathinfo(
    state_dir: &Path,
) -> Result<snix_store::pathinfoservice::RedbPathInfoService, RunError> {
    use snix_store::pathinfoservice::RedbPathInfoService;
    use snix_store::pathinfoservice::RedbPathInfoServiceConfig;
    debug_assert!(!state_dir.as_os_str().is_empty());
    debug_assert!(state_dir.is_absolute());

    let db_path = state_dir.join("pathinfo.redb");
    match RedbPathInfoService::new("crunch".to_string(), RedbPathInfoServiceConfig {
        path: Some(db_path.clone()),
        read_only: false,
        cache_size: None,
    })
    .await
    {
        Ok(svc) => Ok(svc),
        Err(e) => {
            tracing::warn!(
                path = %db_path.display(),
                err = %e,
                "failed to open PathInfo database, using in-memory fallback"
            );
            RedbPathInfoService::new_temporary("crunch".to_string(), RedbPathInfoServiceConfig {
                path: None,
                read_only: false,
                cache_size: None,
            })
            .map_err(|e| RunError::Internal(format!("in-memory PathInfo: {e}")))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn mock_resolve_ok(pkg: &str) -> Result<String, RunError> {
        Ok(format!("/nix/store/aaaa-{pkg}"))
    }

    fn mock_resolve_fail(pkg: &str) -> Result<String, RunError> {
        Err(RunError::Internal(format!("package not found: {pkg}")))
    }

    fn mock_resolve_empty(_pkg: &str) -> Result<String, RunError> {
        Ok(String::new())
    }

    #[test]
    fn source_tree_file_candidates_walk_up_from_current_dir() {
        let relative = Path::new("bootstrap").join("seed.ncl");
        let candidates = source_tree_file_candidates(Some(Path::new("/workspace/project/crates/cli")), &relative);

        assert!(candidates.contains(&PathBuf::from("/workspace/project/crates/cli/bootstrap/seed.ncl")));
        assert!(candidates.contains(&PathBuf::from("/workspace/project/bootstrap/seed.ncl")));
        assert!(candidates.contains(&PathBuf::from("/workspace/bootstrap/seed.ncl")));
    }

    #[test]
    fn source_tree_file_candidates_empty_without_current_dir() {
        let relative = Path::new("bootstrap").join("seed.ncl");
        let candidates = source_tree_file_candidates(None, &relative);

        assert!(candidates.is_empty());
    }

    #[test]
    fn resolve_success() {
        let pkgs = vec!["bash".into(), "coreutils".into()];
        let entries = resolve_packages(&pkgs, mock_resolve_ok).unwrap();
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[0], ("bash".into(), "/nix/store/aaaa-bash".into()));
        assert_eq!(entries[1], ("coreutils".into(), "/nix/store/aaaa-coreutils".into()));
    }

    #[test]
    fn resolve_failure_reports_package() {
        let pkgs = vec!["bash".into(), "nonexistent".into()];
        let err = resolve_packages(&pkgs, mock_resolve_fail).unwrap_err();
        let msg = err.message().to_string();
        assert!(msg.contains("bash"), "error should name the package: {msg}");
    }

    #[test]
    fn resolve_empty_path_rejected() {
        let pkgs = vec!["bash".into()];
        let err = resolve_packages(&pkgs, mock_resolve_empty).unwrap_err();
        assert!(err.message().contains("empty store path"));
    }

    #[test]
    fn generate_seed_valid_structure() {
        let entries = vec![
            ("bash".into(), "/nix/store/aaaa-bash".into()),
            ("gcc".into(), "/nix/store/bbbb-gcc".into()),
        ];
        let ncl = generate_seed_ncl(&entries);

        assert!(ncl.starts_with("# Generated by `crunch bootstrap`\n"));
        assert!(ncl.contains("import \"contracts.ncl\""));
        assert!(ncl.contains("bash | StorePath"));
        assert!(ncl.contains("\"/nix/store/aaaa-bash\""));
        assert!(ncl.contains("gcc | StorePath"));
        assert!(ncl.contains("\"/nix/store/bbbb-gcc\""));
        assert!(ncl.contains("nix-store --add-root"));
        assert!(ncl.trim_end().ends_with('}'));
    }

    #[test]
    fn generate_seed_sanitizes_hyphens() {
        let entries = vec![("my-cool-pkg".into(), "/nix/store/xxxx-my-cool-pkg".into())];
        let ncl = generate_seed_ncl(&entries);

        assert!(ncl.contains("my_cool_pkg | StorePath"));
        assert!(ncl.contains("\"Store path for my-cool-pkg\""));
    }

    #[test]
    fn generate_seed_empty_packages() {
        let entries: Vec<(String, String)> = vec![];
        let ncl = generate_seed_ncl(&entries);
        assert!(ncl.contains("{\n}\n"));
    }

    #[test]
    fn fetch_seed_provider_loads_explicit_legacy_compatibility_module() {
        let provider = load_fetch_seed_provider().unwrap();
        assert_eq!(provider.name, "musl-seed-toolchain");
        assert_eq!(provider.toolchain.name, "musl-seed-toolchain");
        assert_eq!(provider.target, "x86_64-linux-musl");
        assert!(provider.provider.id.contains("reduced"));
        assert!(provider.provider.raw.url.contains("musl.cc"));
        assert!(provider.provider.raw.hash.starts_with("sha256-"));
    }

    #[test]
    fn fetch_seed_provider_records_reduction_surface() {
        let provider = load_fetch_seed_provider().unwrap();
        let dropped = provider.provider.dropped_components.join(" | ");
        let retained = provider.provider.retained_tools.join(" | ");

        assert!(dropped.contains("Fortran"), "dropped list: {dropped}");
        assert!(dropped.contains("LTO"), "dropped list: {dropped}");
        assert!(retained.contains("x86_64-linux-musl-gcc"), "retained list: {retained}");
        assert!(retained.contains("x86_64-linux-musl-ld"), "retained list: {retained}");
    }

    #[test]
    fn fetch_seed_provider_loads_with_embedded_stdlib() {
        let dir = tempfile::tempdir().unwrap();
        let stdlib_dir = crunch_eval::stdlib::write_stdlib(Some(dir.path())).unwrap();
        let import_paths = vec![stdlib_dir.into_os_string()];
        let provider: FetchSeedProvider =
            crunch_eval::evaluate_and_deserialize(&fetch_seed_provider_path(), &import_paths).unwrap();

        assert_eq!(provider.name, "musl-seed-toolchain");
        assert_eq!(provider.provider.raw.name, "musl-gcc-raw");
    }

    #[test]
    fn generate_fetch_seed_ncl_structure() {
        let provider = load_fetch_seed_provider().unwrap();
        let logical_path = "/crunch/store/xxx-musl-seed-toolchain";
        let ncl = generate_fetch_seed_ncl(&provider, logical_path);

        assert!(ncl.starts_with("# Generated by `crunch bootstrap --fetch`\n"));
        assert!(ncl.contains("Provider: musl.cc-native-reduced-v1"));
        assert!(ncl.contains("Raw artifact: https://musl.cc/x86_64-linux-musl-native.tgz"));
        assert!(ncl.contains("Metadata: /crunch/store/xxx-musl-seed-toolchain/share/crunch-bootstrap/provider.json"));
        assert!(ncl.contains("toolchain | StorePath"));
        assert!(ncl.contains("gcc | StorePath"));
        assert!(ncl.contains("\"/crunch/store/xxx-musl-seed-toolchain\""));
        assert!(!ncl.contains("nix-store --add-root"));
        assert!(ncl.trim_end().ends_with('}'));
    }

    #[test]
    fn generate_source_root_seed_ncl_structure() {
        let logical_path = "/mantle/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-musl-seed-toolchain";
        let manifest_digest = blake3::hash(b"manifest").to_hex().to_string();
        let output_digest = blake3::hash(b"output").to_hex().to_string();
        let ncl = generate_source_root_seed_ncl(logical_path, &manifest_digest, &output_digest);

        assert!(ncl.starts_with("# Generated by `mantle bootstrap --source-root`\n"));
        assert!(ncl.contains("Provider: source-root-v1"));
        assert!(ncl.contains("not a full-source bootstrap"));
        assert!(ncl.contains(&format!("Source-root manifest digest: blake3:{manifest_digest}")));
        assert!(ncl.contains(&format!("Provider output digest: blake3:{output_digest}")));
        assert!(ncl.contains("Metadata: /mantle/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-musl-seed-toolchain/share/crunch-bootstrap/provider.json"));
        assert!(ncl.contains("toolchain | StorePath"));
        assert!(ncl.contains("gcc | StorePath"));
        assert!(ncl.contains(logical_path));
        assert!(ncl.contains("No legacy musl.cc binary toolchain tarball was used."));
        assert!(!ncl.contains("https://musl.cc/x86_64-linux-musl-native.tgz"));
        assert!(ncl.trim_end().ends_with('}'));
    }

    #[test]
    fn fetch_seed_metadata_logical_path_appends_provider_json() {
        let path = fetch_seed_metadata_logical_path("/crunch/store/abc-seed");
        assert_eq!(path, "/crunch/store/abc-seed/share/crunch-bootstrap/provider.json");
    }

    #[test]
    fn write_provider_metadata_records_shared_schema() {
        let dir = tempfile::tempdir().unwrap();
        let raw_root = dir.path().join("raw");
        let reduced_root = dir.path().join("reduced");
        std::fs::create_dir_all(&raw_root).unwrap();
        std::fs::create_dir_all(&reduced_root).unwrap();
        std::fs::write(raw_root.join("payload.bin"), vec![0u8; 16]).unwrap();
        std::fs::write(reduced_root.join("payload.bin"), vec![0u8; 8]).unwrap();

        let provider = load_fetch_seed_provider().unwrap();
        let metadata_path = reduced_root.join("share").join("crunch-bootstrap").join("provider.json");
        write_provider_metadata(&provider, &raw_root, &reduced_root, &metadata_path).unwrap();

        let text = std::fs::read_to_string(&metadata_path).unwrap();
        let json: serde_json::Value = serde_json::from_str(&text).unwrap();
        assert_eq!(json["reduction"]["raw_size_bytes"].as_u64(), Some(16));
        assert_eq!(json["reduction"]["reduced_size_bytes"].as_u64(), Some(8));
        assert!(json["reduction"]["retained_tools"].is_array());
        assert!(json["notes"].is_array());
    }

    #[cfg(unix)]
    #[test]
    fn copy_path_recursively_materializes_read_only_source_directory() {
        use std::os::unix::fs::PermissionsExt as _;

        const PERMISSION_BITS_MASK: u32 = 0o777;
        const READ_ONLY_DIRECTORY_MODE: u32 = 0o555;
        let dir = tempfile::tempdir().unwrap();
        let source = dir.path().join("source");
        let destination = dir.path().join("destination");
        std::fs::create_dir_all(&source).unwrap();
        std::fs::write(source.join("payload"), b"payload\n").unwrap();
        std::fs::set_permissions(&source, std::fs::Permissions::from_mode(READ_ONLY_DIRECTORY_MODE)).unwrap();

        copy_path_recursively(&source, &destination).unwrap();

        assert_eq!(std::fs::read(destination.join("payload")).unwrap(), b"payload\n");
        assert_eq!(
            std::fs::symlink_metadata(&destination).unwrap().permissions().mode() & PERMISSION_BITS_MASK,
            READ_ONLY_DIRECTORY_MODE
        );
    }

    #[cfg(unix)]
    #[test]
    fn reduction_directory_preparation_makes_nested_read_only_tree_mutable() {
        use std::os::unix::fs::PermissionsExt as _;

        const PERMISSION_BITS_MASK: u32 = 0o777;
        const READ_ONLY_DIRECTORY_MODE: u32 = 0o555;
        const OWNER_WRITABLE_MASK: u32 = 0o200;
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("root");
        let nested = root.join("nested");
        std::fs::create_dir_all(&nested).unwrap();
        std::fs::set_permissions(&nested, std::fs::Permissions::from_mode(READ_ONLY_DIRECTORY_MODE)).unwrap();
        std::fs::set_permissions(&root, std::fs::Permissions::from_mode(READ_ONLY_DIRECTORY_MODE)).unwrap();

        make_reduction_directories_writable(&root).unwrap();

        let root_mode = std::fs::symlink_metadata(&root).unwrap().permissions().mode() & PERMISSION_BITS_MASK;
        let nested_mode = std::fs::symlink_metadata(&nested).unwrap().permissions().mode() & PERMISSION_BITS_MASK;
        assert_ne!(root_mode & OWNER_WRITABLE_MASK, 0);
        assert_ne!(nested_mode & OWNER_WRITABLE_MASK, 0);
    }

    #[test]
    fn stage_reduced_seed_provider_materializes_kernel_headers_in_target_include() {
        let dir = tempfile::tempdir().unwrap();
        let raw_root = dir.path().join("raw");
        let stage_root = dir.path().join("stage");
        let linux_dir = raw_root.join("include").join("linux");
        std::fs::create_dir_all(&linux_dir).unwrap();
        std::fs::write(linux_dir.join("capability.h"), b"capability\n").unwrap();
        std::fs::write(linux_dir.join("loop.h"), b"loop\n").unwrap();

        let provider = load_fetch_seed_provider().unwrap();
        stage_reduced_seed_provider(&raw_root, &stage_root, &provider).unwrap();

        let target_include = stage_root.join(&provider.target).join("include").join("linux");
        assert!(target_include.join("capability.h").exists());
        assert!(target_include.join("loop.h").exists());
    }
}
