//! Self-build: crunch builds itself from source.
//!
//! Copies the source tree (with vendored Cargo deps) directly into
//! the output store, generates a Nickel derivation that references it
//! as a plain source input, and delegates to the normal build pipeline.
//!
//! No tarball hashing, no NAR serialization, no FOD. The source tree
//! is just a directory in the store, like any other Nix source path.
//!
//! The output is a statically-linked crunch binary compiled inside a
//! bwrap sandbox using only the bootstrap toolchain.

use std::path::{Path, PathBuf};
use std::process::Command;

use crate::build_cmd::{build_import_paths, report_build_result, run_build};
use crate::errors::RunError;

/// Maximum source tree size: 2 GiB.
const MAX_SOURCE_BYTES: u64 = 2 * 1024 * 1024 * 1024;

/// Stage the crunch source tree into the output store.
///
/// 1. `cargo vendor --locked vendor-deps`
/// 2. `git archive HEAD | tar -x` into staging
/// 3. Copy vendor-deps/ into staging
/// 4. Move staging into `$store_dir/$hash-crunch-src/`
///
/// Returns the store path name (e.g., "abcdef...-crunch-src").
pub fn stage_source(
    src_dir: &Path,
    store_dir: &Path,
) -> Result<String, RunError> {
    let staging = tempfile::tempdir()
        .map_err(|e| RunError::Internal(format!("tmpdir: {e}")))?;
    let stage_root = staging.path().join("crunch-src");
    std::fs::create_dir_all(&stage_root)
        .map_err(|e| RunError::Internal(format!("mkdir staging: {e}")))?;

    // 1. Vendor dependencies.
    eprintln!("  vendoring cargo dependencies...");
    run_cmd(
        Command::new("cargo")
            .args(["vendor", "--locked", "vendor-deps"])
            .current_dir(src_dir),
        "cargo vendor",
    )?;

    // 2. Git-tracked files → staging.
    eprintln!("  exporting git-tracked files...");
    run_cmd(
        Command::new("sh")
            .args(["-c", &format!(
                "cd '{}' && git archive HEAD | tar -x -C '{}'",
                src_dir.display(),
                stage_root.display(),
            )]),
        "git archive | tar extract",
    )?;

    // 3. Copy vendor-deps.
    eprintln!("  copying vendored deps...");
    assert!(
        src_dir.join("vendor-deps").exists(),
        "vendor-deps/ must exist after cargo vendor"
    );
    run_cmd(
        Command::new("cp")
            .args(["-a"])
            .arg(src_dir.join("vendor-deps"))
            .arg(stage_root.join("vendor-deps")),
        "cp vendor-deps",
    )?;

    // Size check.
    let size = dir_size(&stage_root);
    assert!(
        size <= MAX_SOURCE_BYTES,
        "source tree {} MiB exceeds {} MiB limit",
        size / (1024 * 1024),
        MAX_SOURCE_BYTES / (1024 * 1024),
    );
    eprintln!("  source tree: {} MiB", size / (1024 * 1024));

    // 4. Compute a content fingerprint for the store path name.
    //
    // Not a NAR hash — just a quick fingerprint for a unique name.
    // Hash the file listing (paths + sizes) with blake3, then encode
    // the first 20 bytes as nix-base32 (the store path digest format).
    let fingerprint = tree_fingerprint(&stage_root);
    let digest_bytes = data_encoding::HEXLOWER.decode(fingerprint.as_bytes())
        .unwrap_or_else(|_| vec![0u8; 32]);
    let store_hash = nix_compat::nixbase32::encode(&digest_bytes[..20]);
    let store_name = format!("{store_hash}-crunch-src");
    let dest = store_dir.join(&store_name);

    if dest.exists() {
        eprintln!("  source already staged: {}", dest.display());
        return Ok(store_name);
    }

    // Move staging into store. Use cp + rm since rename() doesn't
    // work across filesystems (tmpfs → disk).
    run_cmd(
        Command::new("cp")
            .args(["-a"])
            .arg(&stage_root)
            .arg(&dest),
        "cp to store",
    )?;

    eprintln!("  staged: {}", dest.display());
    Ok(store_name)
}

/// Generate the Nickel derivation for building crunch.
///
/// The source tree is referenced as a plain input path (not a FOD).
pub fn generate_self_build_ncl(
    src_store_path: &str,
    store_prefix: &str,
) -> String {
    format!(
        r#"# Auto-generated by `crunch self-build`.
let crunch = import "lib.ncl" in

let toolchain = crunch.fetchTarball {{
  url = "https://musl.cc/x86_64-linux-musl-native.tgz",
  hash = "sha256-XpcI34j9YwAQj7qw4DpvXqT1CX00vHcUQbAk/do46jw=",
  name = "musl-gcc",
}} in

let gnumake = (import "make.ncl") in
let dash = (import "dash.ncl") in
let binutils = (import "binutils.ncl") in
let musl = (import "musl.ncl") in
let gcc = (import "gcc.ncl") in
let rust = (import "rust.ncl") in
let busybox = (import "busybox.ncl") in
let bwrap = (import "bwrap.ncl") in

{{
  name = "crunch",
  builder = "/bin/sh",
  args = [
    "-c",
    m%"
      set -e
      BB=/bin/busybox
      $BB mkdir -p /tmp/tools
      for cmd in cat mkdir cp chmod ln ls echo rm mv sed grep awk \
                 tr head tail sort wc expr test basename dirname \
                 install find xargs readlink touch true false tee \
                 du cut uname id whoami env printenv; do
        $BB ln -sf $BB /tmp/tools/$cmd
      done

      GCC=""
      for d in $NIX_STORE/*-gcc; do
        if [ -x "$d/bin/gcc" ]; then GCC="$d"; break; fi
      done
      BINUTILS=""
      for d in $NIX_STORE/*-binutils; do
        if [ -d "$d/bin" ]; then BINUTILS="$d"; break; fi
      done
      MUSL=""
      for d in $NIX_STORE/*-musl; do
        if [ -d "$d/include" ]; then MUSL="$d"; break; fi
      done
      DASH=""
      for d in $NIX_STORE/*-dash; do
        if [ -x "$d/bin/dash" ]; then DASH="$d"; break; fi
      done
      MAKE=""
      for d in $NIX_STORE/*-gnumake; do
        if [ -x "$d/bin/make" ]; then MAKE="$d"; break; fi
      done
      RUST=""
      for d in $NIX_STORE/*-rust; do
        if [ -x "$d/bin/rustc" ]; then RUST="$d"; break; fi
      done

      CRUNCH_SRC="$NIX_STORE/{src_store_path}"
      if [ ! -f "$CRUNCH_SRC/Cargo.toml" ]; then
        echo "ERROR: CRUNCH_SRC not found at $CRUNCH_SRC" >&2
        exit 1
      fi

      for tool in GCC BINUTILS MUSL DASH MAKE RUST; do
        eval val=\$$tool
        if [ -z "$val" ]; then
          echo "ERROR: $tool not found" >&2; exit 1
        fi
        echo "$tool=$val"
      done
      echo "CRUNCH_SRC=$CRUNCH_SRC"

      $BB mkdir -p /lib 2>/dev/null || true
      $BB ln -sf $MUSL/lib/libc.so /lib/ld-musl-x86_64.so.1 2>/dev/null || true

      MUSL_GCC=""
      for d in $NIX_STORE/*-musl-gcc; do
        if [ -f "$d/lib/libgcc_s.so.1" ]; then MUSL_GCC="$d"; break; fi
      done
      if [ -n "$MUSL_GCC" ]; then
        export LD_LIBRARY_PATH="$MUSL_GCC/lib${{LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}}"
      elif [ -f "$GCC/lib/libgcc_s.so.1" ]; then
        export LD_LIBRARY_PATH="$GCC/lib${{LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}}"
      fi

      $BB ln -sf "$DASH/bin/dash" /tmp/tools/sh

      for tool in as ld ld.bfd ar nm objcopy objdump ranlib readelf strip; do
        if [ -x "$BINUTILS/bin/x86_64-linux-musl-$tool" ] && [ ! -e "/tmp/tools/$tool" ]; then
          $BB ln -sf "$BINUTILS/bin/x86_64-linux-musl-$tool" /tmp/tools/$tool
        fi
      done

      # Find crunch-built bwrap for PATH.
      BWRAP_BIN=""
      for d in $NIX_STORE/*-bwrap; do
        if [ -x "$d/bin/bwrap" ]; then BWRAP_BIN="$d/bin"; break; fi
      done

      # Add bwrap to PATH if available.
      BWRAP_PATH=""
      if [ -n "$BWRAP_BIN" ]; then BWRAP_PATH="$BWRAP_BIN:"; fi
      export PATH="/tmp/tools:${{BWRAP_PATH}}$RUST/bin:$GCC/bin:$BINUTILS/bin:$MAKE/bin"

      echo "=== Tool versions ==="
      rustc --version
      cargo --version
      gcc --version | head -1
      make --version | head -1

      $BB mkdir -p /tmp/build
      cp -r "$CRUNCH_SRC" /tmp/build/crunch 2>/dev/null
      chmod -R u+w /tmp/build/crunch
      cd /tmp/build/crunch

      GCC_LIB=""
      if [ -n "$MUSL_GCC" ]; then GCC_LIB="$MUSL_GCC/lib"
      elif [ -f "$GCC/lib/libgcc_s.so" ]; then GCC_LIB="$GCC/lib"
      fi

      $BB mkdir -p .cargo
      cat > .cargo/config.toml << CARGOEOF
[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/tvlfyi/wu-manber.git"]
git = "https://github.com/tvlfyi/wu-manber.git"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor-deps"

[build]
target = "x86_64-unknown-linux-musl"

[target.x86_64-unknown-linux-musl]
linker = "gcc"
rustflags = ["-C", "link-arg=-Wl,--allow-multiple-definition", "-C", "link-arg=-L${{GCC_LIB}}"]
CARGOEOF

      export CARGO_HOME=/tmp/cargo-home
      export CARGO_TARGET_DIR=/tmp/cargo-target
      # Use crunch-built busybox as the sandbox shell baked into the binary.
      # Find it from the inputs.
      BUSYBOX_BIN=""
      for d in $NIX_STORE/*-busybox; do
        if [ -x "$d/bin/busybox" ]; then BUSYBOX_BIN="$d/bin/busybox"; break; fi
      done
      if [ -n "$BUSYBOX_BIN" ]; then
        export SNIX_BUILD_SANDBOX_SHELL="$BUSYBOX_BIN"
      else
        export SNIX_BUILD_SANDBOX_SHELL=/bin/sh
      fi

      export CC=gcc
      export AR=ar
      export TARGET_CC=gcc
      export TARGET_AR=ar
      export HOST_CC=gcc

      if [ -n "$GCC_LIB" ]; then
        export LIBRARY_PATH="$GCC_LIB${{LIBRARY_PATH:+:$LIBRARY_PATH}}"
      fi

      echo "=== Building crunch ==="
      cargo build --release --locked -j 4 2>&1 || exit 1

      echo "=== Installing ==="
      mkdir -p $out/bin
      cp /tmp/cargo-target/x86_64-unknown-linux-musl/release/crunch $out/bin/

      echo "=== Verify ==="
      ls -la $out/bin/crunch
      file $out/bin/crunch 2>/dev/null || true
      $out/bin/crunch --version 2>/dev/null || $out/bin/crunch --help 2>&1 | head -3
    "%,
  ],
  inputs = [
    toolchain, gnumake, dash, binutils, musl, gcc, rust,
    busybox, bwrap,
    "{store_prefix}/{src_store_path}",
  ],
}} | crunch.Derivation
"#
    )
}

/// Verify the self-built binary by running `--help`.
pub fn verify_binary(binary_path: &Path) -> Result<(), RunError> {
    eprintln!("verifying {}...", binary_path.display());

    let out = Command::new(binary_path)
        .arg("--help")
        .output()
        .map_err(|e| RunError::Internal(format!(
            "failed to run self-built binary: {e}"
        )))?;

    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        return Err(RunError::Build(format!(
            "self-built binary exited {} on --help:\n{stderr}",
            out.status.code().unwrap_or(-1),
        )));
    }

    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(
        stdout.contains("crunch"),
        "self-built binary --help doesn't mention 'crunch'"
    );

    eprintln!("  binary OK");
    Ok(())
}

// ── helpers ────────────────────────────────────────────────────────────

/// Run a command, returning an error with stderr on failure.
fn run_cmd(cmd: &mut Command, label: &str) -> Result<(), RunError> {
    let out = cmd.output().map_err(|e| {
        RunError::Internal(format!("failed to run `{label}`: {e}"))
    })?;

    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        return Err(RunError::Internal(format!(
            "{label} failed (exit {}):\n{stderr}",
            out.status.code().unwrap_or(-1),
        )));
    }

    Ok(())
}

/// Quick blake3 fingerprint of a directory tree (paths + sizes).
///
/// Not a NAR hash — just enough to get a unique store path name.
/// We created this tree ourselves, so integrity verification against
/// a known hash is pointless.
fn tree_fingerprint(dir: &Path) -> String {
    use std::io::Write;

    let mut hasher = blake3::Hasher::new();
    let mut entries: Vec<PathBuf> = Vec::new();

    collect_paths(dir, dir, &mut entries);
    entries.sort();

    for entry in &entries {
        let meta = std::fs::symlink_metadata(entry).ok();
        let size = meta.as_ref().map(|m| m.len()).unwrap_or(0);
        let rel = entry.strip_prefix(dir).unwrap_or(entry);
        let _ = write!(hasher, "{}:{}\n", rel.display(), size);
    }

    let hash = hasher.finalize();
    hash.to_hex().to_string()
}

fn collect_paths(base: &Path, dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries {
        let Ok(entry) = entry else { continue };
        let path = entry.path();
        out.push(path.clone());
        if path.is_dir() && !path.is_symlink() {
            collect_paths(base, &path, out);
        }
    }
}

/// Total size of a directory tree in bytes.
fn dir_size(dir: &Path) -> u64 {
    let mut total: u64 = 0;
    let mut paths: Vec<PathBuf> = Vec::new();
    collect_paths(dir, dir, &mut paths);
    for p in &paths {
        if let Ok(meta) = std::fs::symlink_metadata(p) {
            total = total.saturating_add(meta.len());
        }
    }
    total
}

pub fn cmd_self_build(
    output_dir: &Path,
    state_dir: &Path,
    store_dir: &str,
    verbose: bool,
    max_jobs: u32,
    no_substitute: bool,
    no_verify: bool,
) -> Result<(), RunError> {
    eprintln!("=== crunch self-build ===");

    let src_dir = find_source_dir()?;
    eprintln!("source: {}", src_dir.display());

    let bootstrap_dir = src_dir.join("bootstrap");
    if !bootstrap_dir.exists() {
        return Err(RunError::Internal(format!(
            "bootstrap/ directory not found at {}",
            bootstrap_dir.display(),
        )));
    }

    eprintln!("\n[1/3] Staging source...");
    let store_name = stage_source(&src_dir, output_dir)?;

    eprintln!("\n[2/3] Building...");
    let ncl_content = generate_self_build_ncl(&store_name, store_dir);

    let tmp_dir = tempfile::tempdir()
        .map_err(|e| RunError::Internal(format!("tmpdir: {e}")))?;
    let ncl_path = tmp_dir.path().join("self-build.ncl");
    std::fs::write(&ncl_path, &ncl_content)
        .map_err(|e| RunError::Internal(format!("writing ncl: {e}")))?;

    let lib_dir = src_dir.join("lib");
    let import_paths: Vec<std::ffi::OsString> = {
        let mut paths = build_import_paths(&[lib_dir])?;
        paths.push(bootstrap_dir.into());
        paths
    };

    let config = crunch_pipeline::BuildConfig {
        file: ncl_path.clone(),
        import_paths,
        output_dir: output_dir.to_path_buf(),
        state_dir: state_dir.to_path_buf(),
        store_dir: store_dir.to_string(),
        verbose,
        max_jobs,
        substituter_url: if no_substitute {
            None
        } else {
            Some("https://cache.nixos.org".to_string())
        },
    };

    let result = run_build(&config)?;
    report_build_result(&config, &result, false)?;

    if !no_verify {
        eprintln!("\n[3/3] Verifying output...");
        let crunch_bin = find_self_built_binary(output_dir)?;
        verify_binary(&crunch_bin)?;
    } else {
        eprintln!("\n[3/3] Verification skipped (--no-verify).");
    }

    eprintln!("\n=== self-build complete ===");
    Ok(())
}

fn find_source_dir() -> Result<PathBuf, RunError> {
    let cwd = std::env::current_dir()
        .map_err(|e| RunError::Internal(format!("cwd: {e}")))?;

    if cwd.join("Cargo.toml").exists() && cwd.join("bootstrap").exists() {
        return Ok(cwd);
    }

    let mut dir = cwd.as_path();
    for _ in 0..8_u32 {
        if dir.join("Cargo.toml").exists() && dir.join("bootstrap").exists() {
            return Ok(dir.to_path_buf());
        }
        match dir.parent() {
            Some(parent) => dir = parent,
            None => break,
        }
    }

    Err(RunError::Internal(
        "could not locate crunch source directory.\nRun `crunch self-build` from the crunch repo root."
            .to_string(),
    ))
}

fn find_self_built_binary(output_dir: &Path) -> Result<PathBuf, RunError> {
    let entries = std::fs::read_dir(output_dir).map_err(|e| {
        RunError::Internal(format!(
            "reading output dir {}: {e}",
            output_dir.display(),
        ))
    })?;

    for entry in entries {
        let entry = match entry {
            Ok(entry) => entry,
            Err(_) => continue,
        };
        let name = entry.file_name();
        let name_str = name.to_string_lossy();
        if name_str.ends_with("-crunch") {
            let binary = entry.path().join("bin").join("crunch");
            if binary.exists() {
                return Ok(binary);
            }
        }
    }

    Err(RunError::Internal(format!(
        "could not find self-built crunch binary in {}",
        output_dir.display(),
    )))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_ncl_has_source_path() {
        let ncl = generate_self_build_ncl("abc123-crunch-src", "/nix/store");
        assert!(ncl.contains("/nix/store/abc123-crunch-src"));
        assert!(ncl.contains("crunch.Derivation"));
    }

    #[test]
    fn generate_ncl_source_is_plain_input() {
        // The source tree should be a string input (source path),
        // not a fetchTarball FOD.
        let ncl = generate_self_build_ncl("abc123-crunch-src", "/nix/store");
        assert!(!ncl.contains("crunch-src\",\n  hash"));
        assert!(ncl.contains("\"/nix/store/abc123-crunch-src\""));
    }

    #[test]
    fn generate_ncl_has_all_bootstrap_deps() {
        let ncl = generate_self_build_ncl("x", "/nix/store");
        assert!(ncl.contains("import \"make.ncl\""));
        assert!(ncl.contains("import \"dash.ncl\""));
        assert!(ncl.contains("import \"binutils.ncl\""));
        assert!(ncl.contains("import \"musl.ncl\""));
        assert!(ncl.contains("import \"gcc.ncl\""));
        assert!(ncl.contains("import \"rust.ncl\""));
        assert!(ncl.contains("import \"busybox.ncl\""));
        assert!(ncl.contains("import \"bwrap.ncl\""));
    }

    #[test]
    fn generate_ncl_has_build_essentials() {
        let ncl = generate_self_build_ncl("x", "/nix/store");
        assert!(ncl.contains("cargo build"));
        assert!(ncl.contains("--release"));
        assert!(ncl.contains("$out/bin/crunch"));
        assert!(ncl.contains("SNIX_BUILD_SANDBOX_SHELL"));
    }

    #[test]
    fn generate_ncl_uses_nix_store_env_var() {
        let ncl = generate_self_build_ncl("x", "/nix/store");
        // Shell globs must use $NIX_STORE, not hardcoded /nix/store.
        assert!(ncl.contains("$NIX_STORE/*-gcc"));
        assert!(ncl.contains("$NIX_STORE/*-rust"));
        assert!(ncl.contains("$NIX_STORE/*-musl-gcc"));
        assert!(ncl.contains("$NIX_STORE/*-busybox"));
        // No hardcoded /nix/store in shell globs.
        assert!(!ncl.contains("for d in /nix/store/"));
    }

    #[test]
    fn generate_ncl_respects_store_prefix() {
        let ncl = generate_self_build_ncl("abc-src", "/crunch/store");
        // The input path in the Nickel record should use the prefix.
        assert!(ncl.contains("\"/crunch/store/abc-src\""));
        assert!(!ncl.contains("/nix/store/abc-src"));
    }

    #[test]
    fn tree_fingerprint_deterministic() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("a.txt"), "hello").unwrap();
        std::fs::create_dir_all(dir.path().join("sub")).unwrap();
        std::fs::write(dir.path().join("sub/b.txt"), "world").unwrap();

        let h1 = tree_fingerprint(dir.path());
        let h2 = tree_fingerprint(dir.path());
        assert_eq!(h1, h2);
        assert_eq!(h1.len(), 64); // blake3 hex
    }

    #[test]
    fn tree_fingerprint_changes_with_content() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("a.txt"), "hello").unwrap();
        let h1 = tree_fingerprint(dir.path());

        // Different file content → different size → different hash.
        std::fs::write(dir.path().join("a.txt"), "hello world").unwrap();
        let h2 = tree_fingerprint(dir.path());
        assert_ne!(h1, h2);
    }

    #[test]
    fn run_cmd_reports_failure() {
        let err = run_cmd(
            Command::new("false").arg(""),
            "test-false",
        ).unwrap_err();
        assert!(err.message().contains("test-false"));
    }

    #[test]
    fn dir_size_basic() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("a"), "12345").unwrap();
        std::fs::write(dir.path().join("b"), "67").unwrap();
        let s = dir_size(dir.path());
        assert_eq!(s, 7);
    }
}
