[package]
name = "crunch-glue"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nix-compat = { path = "../../vendor/nix-compat", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
bstr = "1.10"
data-encoding = "2.6"
blake3 = "=1.8.2"

[dev-dependencies]
pretty_assertions = "1.0"
