#![cfg_attr(not(kani), feature(register_tool))]
#![register_tool(tigerstyle)]
//! crunch-store: Store operations for crunch.
//!
//! Owns service construction, cache checking, realization (castore -> disk
//! export), CA mapping persistence, and store queries. Build and pipeline
//! consumers receive narrow capability values. Shell code can retain the
//! compatibility `StoreHandle` for explicit orchestration.

mod action_result;
mod archive;
mod attestation;
mod audit;
mod build_io;
mod ca_mapping;
mod capability;
mod closure;
mod completeness;
mod error;
mod export;
mod gc;
mod handle;
mod http_closure;
pub mod layer;
pub mod metadata_cache;
mod mutation_lock;
mod overlay;
mod path_identity;
mod policy;
mod provenance;
mod publisher;
mod pull;
mod push;
mod query;
mod repair;
mod retention;
mod roots;

pub use action_result::ActionResultDiscoveryReport;
pub use action_result::ActionResultLookup;
pub use action_result::ActionResultPublicationReport;
pub use action_result::ActionResultPublicationStatus;
pub use action_result::ActionResultRuntimePolicy;
pub use action_result::ActionResultStore;
pub use action_result::ActionResultStoreSet;
pub use action_result::HttpActionResultStore;
pub use action_result::LocalActionResultStore;
pub use action_result::action_result_runtime_policy;
pub use archive::ARCHIVE_COMPATIBILITY;
pub use archive::ARCHIVE_FORMAT_NAME;
pub use archive::ARCHIVE_VERSION;
pub use archive::ArchiveExportOptions;
pub use archive::ArchiveExportReport;
pub use archive::ArchiveImportAction;
pub use archive::ArchiveImportDecision;
pub use archive::ArchiveImportFacts;
pub use archive::ArchiveImportOptions;
pub use archive::ArchiveImportReport;
pub use archive::ArchiveListReport;
pub use archive::ArchiveListedPath;
pub use archive::ArchivePathSummary;
pub use archive::export_store_archive;
pub use archive::import_store_archive;
pub use archive::list_store_archive;
pub use archive::plan_archive_import_action;
pub use attestation::ArtifactProvenance;
pub use attestation::StoredArtifactAttestation;
pub use attestation::StoredClosureAttestation;
pub use attestation::artifact_attestation_digest_for_pathinfo;
pub use attestation::artifact_attestation_file_path;
pub use attestation::closure_attestation_file_path;
pub use attestation::persist_artifact_attestation;
pub use audit::StoreAuditEvent;
pub use audit::StoreAuditKind;
pub use build_io::hash_host_path;
pub use ca_mapping::CaMappings;
pub use ca_mapping::OutputMap;
pub use capability::ActionResultPort;
pub use capability::BuildServiceStore;
pub use capability::BuildStore;
pub use capability::BuilderStoreParts;
pub use capability::OutputLookup;
pub use capability::PipelineStoreParts;
pub use capability::RootRegistry;
pub use capability::SourceAdmission;
pub use capability::StoreAdmin;
pub use closure::ClosureResolution;
pub use closure::MAX_CLOSURE_DEPTH;
pub use closure::resolve_closure;
pub use completeness::MAX_CASTORE_TREE_NODES;
pub use completeness::recursive_castore_completeness;
pub use error::Error;
pub use export::MAX_EXPORT_DEPTH;
pub use export::export_castore_to_disk;
pub use gc::GcBaseReachability;
pub use gc::GcContext;
pub use gc::GcOperationKind;
pub use gc::GcReclaimObservation;
pub use gc::GcReport;
pub use gc::GcUsageReport;
pub use handle::ActionResultOutputProbe;
pub use handle::CacheHit;
pub use handle::OutputSubstitutionMode;
pub use handle::OutputSubstitutionReport;
pub use handle::PersistOutputRequest;
pub use handle::StoreConfig;
pub use handle::StoreHandle;
pub use handle::StoreHandleServices;
pub use handle::VerifiedSourceIngestRequest;
pub use handle::parse_remote_trusted_public_keys;
pub use http_closure::HTTP_CLOSURE_PLAN_SCHEMA;
pub use http_closure::HttpClosureLimits;
pub use http_closure::HttpClosureObservation;
pub use http_closure::HttpClosurePlan;
pub use http_closure::HttpClosurePlanBuilder;
pub use http_closure::HttpClosurePlanError;
pub use http_closure::HttpClosurePlanMember;
pub use http_closure::HttpClosureRequest;
pub use http_closure::MAX_HTTP_CLOSURE_DEPTH;
pub use http_closure::MAX_HTTP_CLOSURE_MEMBERS;
pub use http_closure::MAX_HTTP_CLOSURE_NARINFO_BYTES;
pub use http_closure::MAX_HTTP_CLOSURE_REFERENCES;
pub use http_closure::MAX_HTTP_CLOSURE_TOTAL_NAR_BYTES;
pub use http_closure::verify_http_closure_plan_identity;
pub use metadata_cache::AdmissionSummary;
pub use metadata_cache::AdvisoryMetadataCache;
pub use metadata_cache::DEFAULT_METADATA_TTL_SECS;
pub use metadata_cache::MAX_METADATA_CACHE_ENTRIES;
pub use metadata_cache::MetadataCacheEntry;
pub use metadata_cache::MetadataCacheKey;
pub use metadata_cache::MetadataCacheKeyInput;
pub use metadata_cache::MetadataClass;
pub use metadata_cache::MetadataSchemaVersion;
pub use metadata_cache::MetadataValidity;
pub use metadata_cache::NEGATIVE_MISS_TTL_SECS;
pub use metadata_cache::RefreshPolicy;
pub use metadata_cache::build_metadata_cache_key;
pub use metadata_cache::check_metadata_validity;
pub use metadata_cache::metadata_cache_key;
pub use metadata_cache::metadata_ttl_for_class;
pub use metadata_cache::new_metadata_entry;
pub use mutation_lock::StoreMutationGuard;
pub use overlay::STORE_OVERLAY_REPORT_SCHEMA;
pub use overlay::STORE_STATE_SCHEMA;
pub use overlay::StoreOverlayBaseReport;
pub use overlay::StoreOverlayReport;
pub use overlay::StoreOverlayRuntimePolicy;
pub use overlay::store_overlay_policy_blake3;
pub use overlay::store_overlay_runtime_policy;
pub use policy::StoreFallbackMode;
pub use provenance::CastoreProvenanceRequest;
pub use provenance::CastoreProvenanceScan;
pub use provenance::FOREIGN_PROVENANCE_POLICY_SCHEMA;
pub use provenance::ForeignProvenancePolicy;
pub use provenance::ProvenanceExpectedPathInfo;
pub use provenance::ProvenanceFinding;
pub use provenance::ProvenancePathInfoObservation;
pub use provenance::ProvenancePayloadClass;
pub use provenance::ProvenancePayloadObservation;
pub use provenance::ProvenanceReferenceKind;
pub use provenance::ProvenanceReferenceObservation;
pub use provenance::PurePayloadInput;
pub use provenance::classify_payload;
pub use provenance::scan_castore_provenance;
pub use provenance::validate_foreign_provenance_policy;
pub use publisher::NoopPublisher;
pub use publisher::Publisher;
#[cfg(test)]
pub use publisher::RecordingPublisher;
pub use pull::HttpClosurePullReport;
pub use pull::PullOptions;
pub use pull::PullReport;
pub use pull::PullSource;
pub use pull::PulledPath;
pub use pull::import_http_cache_closure;
pub use pull::import_http_cache_closure_with_validator;
pub use pull::import_paths_from_cache_dir;
pub use pull::import_paths_from_http_cache;
pub use push::PushOptions;
pub use push::PushReport;
pub use push::PushedPath;
pub use push::export_paths_to_cache_dir;
pub use query::PathInfoDetail;
pub use query::SignResult;
pub use query::SignatureVerifyResult;
pub use query::VerifyResult;
pub use query::store_info;
pub use query::store_list;
pub use query::store_sign;
pub use query::store_verify;
pub use query::store_verify_signatures;
pub use repair::ArtifactAttestationRepairStatus;
pub use repair::FinalNarFacts;
pub use repair::FinalNarRepairInspection;
pub use repair::FinalNarRepairPlan;
pub use repair::FinalNarRepairPlanningFacts;
pub use repair::FinalNarRepairRejection;
pub use repair::FinalNarRepairReport;
pub use repair::FinalNarRepairStatus;
pub use repair::execute_final_nar_repair;
pub use repair::inspect_final_nar_repair;
pub use repair::plan_final_nar_repair;
pub use retention::GcRootClass;
pub use retention::GcRootLease;
pub use retention::RootRegistration;
pub use retention::StoreRetentionLimits;
pub use retention::StoreRetentionRuntimePolicy;
pub use retention::core_retention_policy;
pub use retention::store_retention_policy_blake3;
pub use retention::store_retention_runtime_policy;
pub use roots::GcRootRecord;
pub use roots::GcRootSource;
pub use snix_store::path_info::PathInfo;
